
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `membership_tiers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model membership_tiers
 * 
 */
export type membership_tiersModel = runtime.Types.Result.DefaultSelection<Prisma.$membership_tiersPayload>

export type AggregateMembership_tiers = {
  _count: Membership_tiersCountAggregateOutputType | null
  _avg: Membership_tiersAvgAggregateOutputType | null
  _sum: Membership_tiersSumAggregateOutputType | null
  _min: Membership_tiersMinAggregateOutputType | null
  _max: Membership_tiersMaxAggregateOutputType | null
}

export type Membership_tiersAvgAggregateOutputType = {
  cost: number | null
}

export type Membership_tiersSumAggregateOutputType = {
  cost: number | null
}

export type Membership_tiersMinAggregateOutputType = {
  id: string | null
  organization_id: string | null
  name: string | null
  display_name: string | null
  description: string | null
  cost: number | null
  currency: string | null
}

export type Membership_tiersMaxAggregateOutputType = {
  id: string | null
  organization_id: string | null
  name: string | null
  display_name: string | null
  description: string | null
  cost: number | null
  currency: string | null
}

export type Membership_tiersCountAggregateOutputType = {
  id: number
  organization_id: number
  name: number
  display_name: number
  description: number
  cost: number
  currency: number
  _all: number
}


export type Membership_tiersAvgAggregateInputType = {
  cost?: true
}

export type Membership_tiersSumAggregateInputType = {
  cost?: true
}

export type Membership_tiersMinAggregateInputType = {
  id?: true
  organization_id?: true
  name?: true
  display_name?: true
  description?: true
  cost?: true
  currency?: true
}

export type Membership_tiersMaxAggregateInputType = {
  id?: true
  organization_id?: true
  name?: true
  display_name?: true
  description?: true
  cost?: true
  currency?: true
}

export type Membership_tiersCountAggregateInputType = {
  id?: true
  organization_id?: true
  name?: true
  display_name?: true
  description?: true
  cost?: true
  currency?: true
  _all?: true
}

export type Membership_tiersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which membership_tiers to aggregate.
   */
  where?: Prisma.membership_tiersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of membership_tiers to fetch.
   */
  orderBy?: Prisma.membership_tiersOrderByWithRelationInput | Prisma.membership_tiersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.membership_tiersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` membership_tiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` membership_tiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned membership_tiers
  **/
  _count?: true | Membership_tiersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Membership_tiersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Membership_tiersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Membership_tiersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Membership_tiersMaxAggregateInputType
}

export type GetMembership_tiersAggregateType<T extends Membership_tiersAggregateArgs> = {
      [P in keyof T & keyof AggregateMembership_tiers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMembership_tiers[P]>
    : Prisma.GetScalarType<T[P], AggregateMembership_tiers[P]>
}




export type membership_tiersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.membership_tiersWhereInput
  orderBy?: Prisma.membership_tiersOrderByWithAggregationInput | Prisma.membership_tiersOrderByWithAggregationInput[]
  by: Prisma.Membership_tiersScalarFieldEnum[] | Prisma.Membership_tiersScalarFieldEnum
  having?: Prisma.membership_tiersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Membership_tiersCountAggregateInputType | true
  _avg?: Membership_tiersAvgAggregateInputType
  _sum?: Membership_tiersSumAggregateInputType
  _min?: Membership_tiersMinAggregateInputType
  _max?: Membership_tiersMaxAggregateInputType
}

export type Membership_tiersGroupByOutputType = {
  id: string
  organization_id: string
  name: string | null
  display_name: string | null
  description: string | null
  cost: number | null
  currency: string | null
  _count: Membership_tiersCountAggregateOutputType | null
  _avg: Membership_tiersAvgAggregateOutputType | null
  _sum: Membership_tiersSumAggregateOutputType | null
  _min: Membership_tiersMinAggregateOutputType | null
  _max: Membership_tiersMaxAggregateOutputType | null
}

type GetMembership_tiersGroupByPayload<T extends membership_tiersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Membership_tiersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Membership_tiersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Membership_tiersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Membership_tiersGroupByOutputType[P]>
      }
    >
  >



export type membership_tiersWhereInput = {
  AND?: Prisma.membership_tiersWhereInput | Prisma.membership_tiersWhereInput[]
  OR?: Prisma.membership_tiersWhereInput[]
  NOT?: Prisma.membership_tiersWhereInput | Prisma.membership_tiersWhereInput[]
  id?: Prisma.UuidFilter<"membership_tiers"> | string
  organization_id?: Prisma.UuidFilter<"membership_tiers"> | string
  name?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  display_name?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  description?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  cost?: Prisma.FloatNullableFilter<"membership_tiers"> | number | null
  currency?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  organizations?: Prisma.XOR<Prisma.OrganizationsScalarRelationFilter, Prisma.organizationsWhereInput>
  user_organizations?: Prisma.User_organizationsListRelationFilter
}

export type membership_tiersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  display_name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  cost?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrderInput | Prisma.SortOrder
  organizations?: Prisma.organizationsOrderByWithRelationInput
  user_organizations?: Prisma.user_organizationsOrderByRelationAggregateInput
}

export type membership_tiersWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.membership_tiersWhereInput | Prisma.membership_tiersWhereInput[]
  OR?: Prisma.membership_tiersWhereInput[]
  NOT?: Prisma.membership_tiersWhereInput | Prisma.membership_tiersWhereInput[]
  organization_id?: Prisma.UuidFilter<"membership_tiers"> | string
  name?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  display_name?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  description?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  cost?: Prisma.FloatNullableFilter<"membership_tiers"> | number | null
  currency?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  organizations?: Prisma.XOR<Prisma.OrganizationsScalarRelationFilter, Prisma.organizationsWhereInput>
  user_organizations?: Prisma.User_organizationsListRelationFilter
}, "id">

export type membership_tiersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  display_name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  cost?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.membership_tiersCountOrderByAggregateInput
  _avg?: Prisma.membership_tiersAvgOrderByAggregateInput
  _max?: Prisma.membership_tiersMaxOrderByAggregateInput
  _min?: Prisma.membership_tiersMinOrderByAggregateInput
  _sum?: Prisma.membership_tiersSumOrderByAggregateInput
}

export type membership_tiersScalarWhereWithAggregatesInput = {
  AND?: Prisma.membership_tiersScalarWhereWithAggregatesInput | Prisma.membership_tiersScalarWhereWithAggregatesInput[]
  OR?: Prisma.membership_tiersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.membership_tiersScalarWhereWithAggregatesInput | Prisma.membership_tiersScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"membership_tiers"> | string
  organization_id?: Prisma.UuidWithAggregatesFilter<"membership_tiers"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"membership_tiers"> | string | null
  display_name?: Prisma.StringNullableWithAggregatesFilter<"membership_tiers"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"membership_tiers"> | string | null
  cost?: Prisma.FloatNullableWithAggregatesFilter<"membership_tiers"> | number | null
  currency?: Prisma.StringNullableWithAggregatesFilter<"membership_tiers"> | string | null
}

export type membership_tiersCreateInput = {
  id: string
  name?: string | null
  display_name?: string | null
  description?: string | null
  cost?: number | null
  currency?: string | null
  organizations: Prisma.organizationsCreateNestedOneWithoutMembership_tiersInput
  user_organizations?: Prisma.user_organizationsCreateNestedManyWithoutMembership_tiersInput
}

export type membership_tiersUncheckedCreateInput = {
  id: string
  organization_id: string
  name?: string | null
  display_name?: string | null
  description?: string | null
  cost?: number | null
  currency?: string | null
  user_organizations?: Prisma.user_organizationsUncheckedCreateNestedManyWithoutMembership_tiersInput
}

export type membership_tiersUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizations?: Prisma.organizationsUpdateOneRequiredWithoutMembership_tiersNestedInput
  user_organizations?: Prisma.user_organizationsUpdateManyWithoutMembership_tiersNestedInput
}

export type membership_tiersUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_organizations?: Prisma.user_organizationsUncheckedUpdateManyWithoutMembership_tiersNestedInput
}

export type membership_tiersCreateManyInput = {
  id: string
  organization_id: string
  name?: string | null
  display_name?: string | null
  description?: string | null
  cost?: number | null
  currency?: string | null
}

export type membership_tiersUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type membership_tiersUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type membership_tiersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  display_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currency?: Prisma.SortOrder
}

export type membership_tiersAvgOrderByAggregateInput = {
  cost?: Prisma.SortOrder
}

export type membership_tiersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  display_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currency?: Prisma.SortOrder
}

export type membership_tiersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  display_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  currency?: Prisma.SortOrder
}

export type membership_tiersSumOrderByAggregateInput = {
  cost?: Prisma.SortOrder
}

export type Membership_tiersListRelationFilter = {
  every?: Prisma.membership_tiersWhereInput
  some?: Prisma.membership_tiersWhereInput
  none?: Prisma.membership_tiersWhereInput
}

export type membership_tiersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Membership_tiersNullableScalarRelationFilter = {
  is?: Prisma.membership_tiersWhereInput | null
  isNot?: Prisma.membership_tiersWhereInput | null
}

export type membership_tiersCreateNestedManyWithoutOrganizationsInput = {
  create?: Prisma.XOR<Prisma.membership_tiersCreateWithoutOrganizationsInput, Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput> | Prisma.membership_tiersCreateWithoutOrganizationsInput[] | Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.membership_tiersCreateOrConnectWithoutOrganizationsInput | Prisma.membership_tiersCreateOrConnectWithoutOrganizationsInput[]
  createMany?: Prisma.membership_tiersCreateManyOrganizationsInputEnvelope
  connect?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
}

export type membership_tiersUncheckedCreateNestedManyWithoutOrganizationsInput = {
  create?: Prisma.XOR<Prisma.membership_tiersCreateWithoutOrganizationsInput, Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput> | Prisma.membership_tiersCreateWithoutOrganizationsInput[] | Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.membership_tiersCreateOrConnectWithoutOrganizationsInput | Prisma.membership_tiersCreateOrConnectWithoutOrganizationsInput[]
  createMany?: Prisma.membership_tiersCreateManyOrganizationsInputEnvelope
  connect?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
}

export type membership_tiersUpdateManyWithoutOrganizationsNestedInput = {
  create?: Prisma.XOR<Prisma.membership_tiersCreateWithoutOrganizationsInput, Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput> | Prisma.membership_tiersCreateWithoutOrganizationsInput[] | Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.membership_tiersCreateOrConnectWithoutOrganizationsInput | Prisma.membership_tiersCreateOrConnectWithoutOrganizationsInput[]
  upsert?: Prisma.membership_tiersUpsertWithWhereUniqueWithoutOrganizationsInput | Prisma.membership_tiersUpsertWithWhereUniqueWithoutOrganizationsInput[]
  createMany?: Prisma.membership_tiersCreateManyOrganizationsInputEnvelope
  set?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
  disconnect?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
  delete?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
  connect?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
  update?: Prisma.membership_tiersUpdateWithWhereUniqueWithoutOrganizationsInput | Prisma.membership_tiersUpdateWithWhereUniqueWithoutOrganizationsInput[]
  updateMany?: Prisma.membership_tiersUpdateManyWithWhereWithoutOrganizationsInput | Prisma.membership_tiersUpdateManyWithWhereWithoutOrganizationsInput[]
  deleteMany?: Prisma.membership_tiersScalarWhereInput | Prisma.membership_tiersScalarWhereInput[]
}

export type membership_tiersUncheckedUpdateManyWithoutOrganizationsNestedInput = {
  create?: Prisma.XOR<Prisma.membership_tiersCreateWithoutOrganizationsInput, Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput> | Prisma.membership_tiersCreateWithoutOrganizationsInput[] | Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.membership_tiersCreateOrConnectWithoutOrganizationsInput | Prisma.membership_tiersCreateOrConnectWithoutOrganizationsInput[]
  upsert?: Prisma.membership_tiersUpsertWithWhereUniqueWithoutOrganizationsInput | Prisma.membership_tiersUpsertWithWhereUniqueWithoutOrganizationsInput[]
  createMany?: Prisma.membership_tiersCreateManyOrganizationsInputEnvelope
  set?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
  disconnect?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
  delete?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
  connect?: Prisma.membership_tiersWhereUniqueInput | Prisma.membership_tiersWhereUniqueInput[]
  update?: Prisma.membership_tiersUpdateWithWhereUniqueWithoutOrganizationsInput | Prisma.membership_tiersUpdateWithWhereUniqueWithoutOrganizationsInput[]
  updateMany?: Prisma.membership_tiersUpdateManyWithWhereWithoutOrganizationsInput | Prisma.membership_tiersUpdateManyWithWhereWithoutOrganizationsInput[]
  deleteMany?: Prisma.membership_tiersScalarWhereInput | Prisma.membership_tiersScalarWhereInput[]
}

export type membership_tiersCreateNestedOneWithoutUser_organizationsInput = {
  create?: Prisma.XOR<Prisma.membership_tiersCreateWithoutUser_organizationsInput, Prisma.membership_tiersUncheckedCreateWithoutUser_organizationsInput>
  connectOrCreate?: Prisma.membership_tiersCreateOrConnectWithoutUser_organizationsInput
  connect?: Prisma.membership_tiersWhereUniqueInput
}

export type membership_tiersUpdateOneWithoutUser_organizationsNestedInput = {
  create?: Prisma.XOR<Prisma.membership_tiersCreateWithoutUser_organizationsInput, Prisma.membership_tiersUncheckedCreateWithoutUser_organizationsInput>
  connectOrCreate?: Prisma.membership_tiersCreateOrConnectWithoutUser_organizationsInput
  upsert?: Prisma.membership_tiersUpsertWithoutUser_organizationsInput
  disconnect?: Prisma.membership_tiersWhereInput | boolean
  delete?: Prisma.membership_tiersWhereInput | boolean
  connect?: Prisma.membership_tiersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.membership_tiersUpdateToOneWithWhereWithoutUser_organizationsInput, Prisma.membership_tiersUpdateWithoutUser_organizationsInput>, Prisma.membership_tiersUncheckedUpdateWithoutUser_organizationsInput>
}

export type membership_tiersCreateWithoutOrganizationsInput = {
  id: string
  name?: string | null
  display_name?: string | null
  description?: string | null
  cost?: number | null
  currency?: string | null
  user_organizations?: Prisma.user_organizationsCreateNestedManyWithoutMembership_tiersInput
}

export type membership_tiersUncheckedCreateWithoutOrganizationsInput = {
  id: string
  name?: string | null
  display_name?: string | null
  description?: string | null
  cost?: number | null
  currency?: string | null
  user_organizations?: Prisma.user_organizationsUncheckedCreateNestedManyWithoutMembership_tiersInput
}

export type membership_tiersCreateOrConnectWithoutOrganizationsInput = {
  where: Prisma.membership_tiersWhereUniqueInput
  create: Prisma.XOR<Prisma.membership_tiersCreateWithoutOrganizationsInput, Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput>
}

export type membership_tiersCreateManyOrganizationsInputEnvelope = {
  data: Prisma.membership_tiersCreateManyOrganizationsInput | Prisma.membership_tiersCreateManyOrganizationsInput[]
  skipDuplicates?: boolean
}

export type membership_tiersUpsertWithWhereUniqueWithoutOrganizationsInput = {
  where: Prisma.membership_tiersWhereUniqueInput
  update: Prisma.XOR<Prisma.membership_tiersUpdateWithoutOrganizationsInput, Prisma.membership_tiersUncheckedUpdateWithoutOrganizationsInput>
  create: Prisma.XOR<Prisma.membership_tiersCreateWithoutOrganizationsInput, Prisma.membership_tiersUncheckedCreateWithoutOrganizationsInput>
}

export type membership_tiersUpdateWithWhereUniqueWithoutOrganizationsInput = {
  where: Prisma.membership_tiersWhereUniqueInput
  data: Prisma.XOR<Prisma.membership_tiersUpdateWithoutOrganizationsInput, Prisma.membership_tiersUncheckedUpdateWithoutOrganizationsInput>
}

export type membership_tiersUpdateManyWithWhereWithoutOrganizationsInput = {
  where: Prisma.membership_tiersScalarWhereInput
  data: Prisma.XOR<Prisma.membership_tiersUpdateManyMutationInput, Prisma.membership_tiersUncheckedUpdateManyWithoutOrganizationsInput>
}

export type membership_tiersScalarWhereInput = {
  AND?: Prisma.membership_tiersScalarWhereInput | Prisma.membership_tiersScalarWhereInput[]
  OR?: Prisma.membership_tiersScalarWhereInput[]
  NOT?: Prisma.membership_tiersScalarWhereInput | Prisma.membership_tiersScalarWhereInput[]
  id?: Prisma.UuidFilter<"membership_tiers"> | string
  organization_id?: Prisma.UuidFilter<"membership_tiers"> | string
  name?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  display_name?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  description?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
  cost?: Prisma.FloatNullableFilter<"membership_tiers"> | number | null
  currency?: Prisma.StringNullableFilter<"membership_tiers"> | string | null
}

export type membership_tiersCreateWithoutUser_organizationsInput = {
  id: string
  name?: string | null
  display_name?: string | null
  description?: string | null
  cost?: number | null
  currency?: string | null
  organizations: Prisma.organizationsCreateNestedOneWithoutMembership_tiersInput
}

export type membership_tiersUncheckedCreateWithoutUser_organizationsInput = {
  id: string
  organization_id: string
  name?: string | null
  display_name?: string | null
  description?: string | null
  cost?: number | null
  currency?: string | null
}

export type membership_tiersCreateOrConnectWithoutUser_organizationsInput = {
  where: Prisma.membership_tiersWhereUniqueInput
  create: Prisma.XOR<Prisma.membership_tiersCreateWithoutUser_organizationsInput, Prisma.membership_tiersUncheckedCreateWithoutUser_organizationsInput>
}

export type membership_tiersUpsertWithoutUser_organizationsInput = {
  update: Prisma.XOR<Prisma.membership_tiersUpdateWithoutUser_organizationsInput, Prisma.membership_tiersUncheckedUpdateWithoutUser_organizationsInput>
  create: Prisma.XOR<Prisma.membership_tiersCreateWithoutUser_organizationsInput, Prisma.membership_tiersUncheckedCreateWithoutUser_organizationsInput>
  where?: Prisma.membership_tiersWhereInput
}

export type membership_tiersUpdateToOneWithWhereWithoutUser_organizationsInput = {
  where?: Prisma.membership_tiersWhereInput
  data: Prisma.XOR<Prisma.membership_tiersUpdateWithoutUser_organizationsInput, Prisma.membership_tiersUncheckedUpdateWithoutUser_organizationsInput>
}

export type membership_tiersUpdateWithoutUser_organizationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizations?: Prisma.organizationsUpdateOneRequiredWithoutMembership_tiersNestedInput
}

export type membership_tiersUncheckedUpdateWithoutUser_organizationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type membership_tiersCreateManyOrganizationsInput = {
  id: string
  name?: string | null
  display_name?: string | null
  description?: string | null
  cost?: number | null
  currency?: string | null
}

export type membership_tiersUpdateWithoutOrganizationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_organizations?: Prisma.user_organizationsUpdateManyWithoutMembership_tiersNestedInput
}

export type membership_tiersUncheckedUpdateWithoutOrganizationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_organizations?: Prisma.user_organizationsUncheckedUpdateManyWithoutMembership_tiersNestedInput
}

export type membership_tiersUncheckedUpdateManyWithoutOrganizationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type Membership_tiersCountOutputType
 */

export type Membership_tiersCountOutputType = {
  user_organizations: number
}

export type Membership_tiersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user_organizations?: boolean | Membership_tiersCountOutputTypeCountUser_organizationsArgs
}

/**
 * Membership_tiersCountOutputType without action
 */
export type Membership_tiersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Membership_tiersCountOutputType
   */
  select?: Prisma.Membership_tiersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Membership_tiersCountOutputType without action
 */
export type Membership_tiersCountOutputTypeCountUser_organizationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_organizationsWhereInput
}


export type membership_tiersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organization_id?: boolean
  name?: boolean
  display_name?: boolean
  description?: boolean
  cost?: boolean
  currency?: boolean
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
  user_organizations?: boolean | Prisma.membership_tiers$user_organizationsArgs<ExtArgs>
  _count?: boolean | Prisma.Membership_tiersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["membership_tiers"]>

export type membership_tiersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organization_id?: boolean
  name?: boolean
  display_name?: boolean
  description?: boolean
  cost?: boolean
  currency?: boolean
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["membership_tiers"]>

export type membership_tiersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organization_id?: boolean
  name?: boolean
  display_name?: boolean
  description?: boolean
  cost?: boolean
  currency?: boolean
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["membership_tiers"]>

export type membership_tiersSelectScalar = {
  id?: boolean
  organization_id?: boolean
  name?: boolean
  display_name?: boolean
  description?: boolean
  cost?: boolean
  currency?: boolean
}

export type membership_tiersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "organization_id" | "name" | "display_name" | "description" | "cost" | "currency", ExtArgs["result"]["membership_tiers"]>
export type membership_tiersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
  user_organizations?: boolean | Prisma.membership_tiers$user_organizationsArgs<ExtArgs>
  _count?: boolean | Prisma.Membership_tiersCountOutputTypeDefaultArgs<ExtArgs>
}
export type membership_tiersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
}
export type membership_tiersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
}

export type $membership_tiersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "membership_tiers"
  objects: {
    organizations: Prisma.$organizationsPayload<ExtArgs>
    user_organizations: Prisma.$user_organizationsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    organization_id: string
    name: string | null
    display_name: string | null
    description: string | null
    cost: number | null
    currency: string | null
  }, ExtArgs["result"]["membership_tiers"]>
  composites: {}
}

export type membership_tiersGetPayload<S extends boolean | null | undefined | membership_tiersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload, S>

export type membership_tiersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<membership_tiersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Membership_tiersCountAggregateInputType | true
  }

export interface membership_tiersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['membership_tiers'], meta: { name: 'membership_tiers' } }
  /**
   * Find zero or one Membership_tiers that matches the filter.
   * @param {membership_tiersFindUniqueArgs} args - Arguments to find a Membership_tiers
   * @example
   * // Get one Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends membership_tiersFindUniqueArgs>(args: Prisma.SelectSubset<T, membership_tiersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Membership_tiers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {membership_tiersFindUniqueOrThrowArgs} args - Arguments to find a Membership_tiers
   * @example
   * // Get one Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends membership_tiersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, membership_tiersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Membership_tiers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membership_tiersFindFirstArgs} args - Arguments to find a Membership_tiers
   * @example
   * // Get one Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends membership_tiersFindFirstArgs>(args?: Prisma.SelectSubset<T, membership_tiersFindFirstArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Membership_tiers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membership_tiersFindFirstOrThrowArgs} args - Arguments to find a Membership_tiers
   * @example
   * // Get one Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends membership_tiersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, membership_tiersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Membership_tiers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membership_tiersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.findMany()
   * 
   * // Get first 10 Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const membership_tiersWithIdOnly = await prisma.membership_tiers.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends membership_tiersFindManyArgs>(args?: Prisma.SelectSubset<T, membership_tiersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Membership_tiers.
   * @param {membership_tiersCreateArgs} args - Arguments to create a Membership_tiers.
   * @example
   * // Create one Membership_tiers
   * const Membership_tiers = await prisma.membership_tiers.create({
   *   data: {
   *     // ... data to create a Membership_tiers
   *   }
   * })
   * 
   */
  create<T extends membership_tiersCreateArgs>(args: Prisma.SelectSubset<T, membership_tiersCreateArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Membership_tiers.
   * @param {membership_tiersCreateManyArgs} args - Arguments to create many Membership_tiers.
   * @example
   * // Create many Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends membership_tiersCreateManyArgs>(args?: Prisma.SelectSubset<T, membership_tiersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Membership_tiers and returns the data saved in the database.
   * @param {membership_tiersCreateManyAndReturnArgs} args - Arguments to create many Membership_tiers.
   * @example
   * // Create many Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Membership_tiers and only return the `id`
   * const membership_tiersWithIdOnly = await prisma.membership_tiers.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends membership_tiersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, membership_tiersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Membership_tiers.
   * @param {membership_tiersDeleteArgs} args - Arguments to delete one Membership_tiers.
   * @example
   * // Delete one Membership_tiers
   * const Membership_tiers = await prisma.membership_tiers.delete({
   *   where: {
   *     // ... filter to delete one Membership_tiers
   *   }
   * })
   * 
   */
  delete<T extends membership_tiersDeleteArgs>(args: Prisma.SelectSubset<T, membership_tiersDeleteArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Membership_tiers.
   * @param {membership_tiersUpdateArgs} args - Arguments to update one Membership_tiers.
   * @example
   * // Update one Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends membership_tiersUpdateArgs>(args: Prisma.SelectSubset<T, membership_tiersUpdateArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Membership_tiers.
   * @param {membership_tiersDeleteManyArgs} args - Arguments to filter Membership_tiers to delete.
   * @example
   * // Delete a few Membership_tiers
   * const { count } = await prisma.membership_tiers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends membership_tiersDeleteManyArgs>(args?: Prisma.SelectSubset<T, membership_tiersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Membership_tiers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membership_tiersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends membership_tiersUpdateManyArgs>(args: Prisma.SelectSubset<T, membership_tiersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Membership_tiers and returns the data updated in the database.
   * @param {membership_tiersUpdateManyAndReturnArgs} args - Arguments to update many Membership_tiers.
   * @example
   * // Update many Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Membership_tiers and only return the `id`
   * const membership_tiersWithIdOnly = await prisma.membership_tiers.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends membership_tiersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, membership_tiersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Membership_tiers.
   * @param {membership_tiersUpsertArgs} args - Arguments to update or create a Membership_tiers.
   * @example
   * // Update or create a Membership_tiers
   * const membership_tiers = await prisma.membership_tiers.upsert({
   *   create: {
   *     // ... data to create a Membership_tiers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Membership_tiers we want to update
   *   }
   * })
   */
  upsert<T extends membership_tiersUpsertArgs>(args: Prisma.SelectSubset<T, membership_tiersUpsertArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Membership_tiers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membership_tiersCountArgs} args - Arguments to filter Membership_tiers to count.
   * @example
   * // Count the number of Membership_tiers
   * const count = await prisma.membership_tiers.count({
   *   where: {
   *     // ... the filter for the Membership_tiers we want to count
   *   }
   * })
  **/
  count<T extends membership_tiersCountArgs>(
    args?: Prisma.Subset<T, membership_tiersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Membership_tiersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Membership_tiers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Membership_tiersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Membership_tiersAggregateArgs>(args: Prisma.Subset<T, Membership_tiersAggregateArgs>): Prisma.PrismaPromise<GetMembership_tiersAggregateType<T>>

  /**
   * Group by Membership_tiers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membership_tiersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends membership_tiersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: membership_tiersGroupByArgs['orderBy'] }
      : { orderBy?: membership_tiersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, membership_tiersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMembership_tiersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the membership_tiers model
 */
readonly fields: membership_tiersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for membership_tiers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__membership_tiersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organizations<T extends Prisma.organizationsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.organizationsDefaultArgs<ExtArgs>>): Prisma.Prisma__organizationsClient<runtime.Types.Result.GetResult<Prisma.$organizationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user_organizations<T extends Prisma.membership_tiers$user_organizationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.membership_tiers$user_organizationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the membership_tiers model
 */
export interface membership_tiersFieldRefs {
  readonly id: Prisma.FieldRef<"membership_tiers", 'String'>
  readonly organization_id: Prisma.FieldRef<"membership_tiers", 'String'>
  readonly name: Prisma.FieldRef<"membership_tiers", 'String'>
  readonly display_name: Prisma.FieldRef<"membership_tiers", 'String'>
  readonly description: Prisma.FieldRef<"membership_tiers", 'String'>
  readonly cost: Prisma.FieldRef<"membership_tiers", 'Float'>
  readonly currency: Prisma.FieldRef<"membership_tiers", 'String'>
}
    

// Custom InputTypes
/**
 * membership_tiers findUnique
 */
export type membership_tiersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * Filter, which membership_tiers to fetch.
   */
  where: Prisma.membership_tiersWhereUniqueInput
}

/**
 * membership_tiers findUniqueOrThrow
 */
export type membership_tiersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * Filter, which membership_tiers to fetch.
   */
  where: Prisma.membership_tiersWhereUniqueInput
}

/**
 * membership_tiers findFirst
 */
export type membership_tiersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * Filter, which membership_tiers to fetch.
   */
  where?: Prisma.membership_tiersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of membership_tiers to fetch.
   */
  orderBy?: Prisma.membership_tiersOrderByWithRelationInput | Prisma.membership_tiersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for membership_tiers.
   */
  cursor?: Prisma.membership_tiersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` membership_tiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` membership_tiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of membership_tiers.
   */
  distinct?: Prisma.Membership_tiersScalarFieldEnum | Prisma.Membership_tiersScalarFieldEnum[]
}

/**
 * membership_tiers findFirstOrThrow
 */
export type membership_tiersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * Filter, which membership_tiers to fetch.
   */
  where?: Prisma.membership_tiersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of membership_tiers to fetch.
   */
  orderBy?: Prisma.membership_tiersOrderByWithRelationInput | Prisma.membership_tiersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for membership_tiers.
   */
  cursor?: Prisma.membership_tiersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` membership_tiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` membership_tiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of membership_tiers.
   */
  distinct?: Prisma.Membership_tiersScalarFieldEnum | Prisma.Membership_tiersScalarFieldEnum[]
}

/**
 * membership_tiers findMany
 */
export type membership_tiersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * Filter, which membership_tiers to fetch.
   */
  where?: Prisma.membership_tiersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of membership_tiers to fetch.
   */
  orderBy?: Prisma.membership_tiersOrderByWithRelationInput | Prisma.membership_tiersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing membership_tiers.
   */
  cursor?: Prisma.membership_tiersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` membership_tiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` membership_tiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of membership_tiers.
   */
  distinct?: Prisma.Membership_tiersScalarFieldEnum | Prisma.Membership_tiersScalarFieldEnum[]
}

/**
 * membership_tiers create
 */
export type membership_tiersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * The data needed to create a membership_tiers.
   */
  data: Prisma.XOR<Prisma.membership_tiersCreateInput, Prisma.membership_tiersUncheckedCreateInput>
}

/**
 * membership_tiers createMany
 */
export type membership_tiersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many membership_tiers.
   */
  data: Prisma.membership_tiersCreateManyInput | Prisma.membership_tiersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * membership_tiers createManyAndReturn
 */
export type membership_tiersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * The data used to create many membership_tiers.
   */
  data: Prisma.membership_tiersCreateManyInput | Prisma.membership_tiersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * membership_tiers update
 */
export type membership_tiersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * The data needed to update a membership_tiers.
   */
  data: Prisma.XOR<Prisma.membership_tiersUpdateInput, Prisma.membership_tiersUncheckedUpdateInput>
  /**
   * Choose, which membership_tiers to update.
   */
  where: Prisma.membership_tiersWhereUniqueInput
}

/**
 * membership_tiers updateMany
 */
export type membership_tiersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update membership_tiers.
   */
  data: Prisma.XOR<Prisma.membership_tiersUpdateManyMutationInput, Prisma.membership_tiersUncheckedUpdateManyInput>
  /**
   * Filter which membership_tiers to update
   */
  where?: Prisma.membership_tiersWhereInput
  /**
   * Limit how many membership_tiers to update.
   */
  limit?: number
}

/**
 * membership_tiers updateManyAndReturn
 */
export type membership_tiersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * The data used to update membership_tiers.
   */
  data: Prisma.XOR<Prisma.membership_tiersUpdateManyMutationInput, Prisma.membership_tiersUncheckedUpdateManyInput>
  /**
   * Filter which membership_tiers to update
   */
  where?: Prisma.membership_tiersWhereInput
  /**
   * Limit how many membership_tiers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * membership_tiers upsert
 */
export type membership_tiersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * The filter to search for the membership_tiers to update in case it exists.
   */
  where: Prisma.membership_tiersWhereUniqueInput
  /**
   * In case the membership_tiers found by the `where` argument doesn't exist, create a new membership_tiers with this data.
   */
  create: Prisma.XOR<Prisma.membership_tiersCreateInput, Prisma.membership_tiersUncheckedCreateInput>
  /**
   * In case the membership_tiers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.membership_tiersUpdateInput, Prisma.membership_tiersUncheckedUpdateInput>
}

/**
 * membership_tiers delete
 */
export type membership_tiersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  /**
   * Filter which membership_tiers to delete.
   */
  where: Prisma.membership_tiersWhereUniqueInput
}

/**
 * membership_tiers deleteMany
 */
export type membership_tiersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which membership_tiers to delete
   */
  where?: Prisma.membership_tiersWhereInput
  /**
   * Limit how many membership_tiers to delete.
   */
  limit?: number
}

/**
 * membership_tiers.user_organizations
 */
export type membership_tiers$user_organizationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  where?: Prisma.user_organizationsWhereInput
  orderBy?: Prisma.user_organizationsOrderByWithRelationInput | Prisma.user_organizationsOrderByWithRelationInput[]
  cursor?: Prisma.user_organizationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.User_organizationsScalarFieldEnum | Prisma.User_organizationsScalarFieldEnum[]
}

/**
 * membership_tiers without action
 */
export type membership_tiersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
}
