
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `coupon_redemptions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model coupon_redemptions
 * 
 */
export type coupon_redemptionsModel = runtime.Types.Result.DefaultSelection<Prisma.$coupon_redemptionsPayload>

export type AggregateCoupon_redemptions = {
  _count: Coupon_redemptionsCountAggregateOutputType | null
  _avg: Coupon_redemptionsAvgAggregateOutputType | null
  _sum: Coupon_redemptionsSumAggregateOutputType | null
  _min: Coupon_redemptionsMinAggregateOutputType | null
  _max: Coupon_redemptionsMaxAggregateOutputType | null
}

export type Coupon_redemptionsAvgAggregateOutputType = {
  user_id: number | null
  original_cost: number | null
  discount_amount: number | null
  amount_paid: number | null
}

export type Coupon_redemptionsSumAggregateOutputType = {
  user_id: number | null
  original_cost: number | null
  discount_amount: number | null
  amount_paid: number | null
}

export type Coupon_redemptionsMinAggregateOutputType = {
  id: string | null
  coupon_code_id: string | null
  user_id: number | null
  original_cost: number | null
  discount_amount: number | null
  amount_paid: number | null
  currency: string | null
  item_type: string | null
  item_id: string | null
  redeemed_at: Date | null
}

export type Coupon_redemptionsMaxAggregateOutputType = {
  id: string | null
  coupon_code_id: string | null
  user_id: number | null
  original_cost: number | null
  discount_amount: number | null
  amount_paid: number | null
  currency: string | null
  item_type: string | null
  item_id: string | null
  redeemed_at: Date | null
}

export type Coupon_redemptionsCountAggregateOutputType = {
  id: number
  coupon_code_id: number
  user_id: number
  original_cost: number
  discount_amount: number
  amount_paid: number
  currency: number
  item_type: number
  item_id: number
  redeemed_at: number
  _all: number
}


export type Coupon_redemptionsAvgAggregateInputType = {
  user_id?: true
  original_cost?: true
  discount_amount?: true
  amount_paid?: true
}

export type Coupon_redemptionsSumAggregateInputType = {
  user_id?: true
  original_cost?: true
  discount_amount?: true
  amount_paid?: true
}

export type Coupon_redemptionsMinAggregateInputType = {
  id?: true
  coupon_code_id?: true
  user_id?: true
  original_cost?: true
  discount_amount?: true
  amount_paid?: true
  currency?: true
  item_type?: true
  item_id?: true
  redeemed_at?: true
}

export type Coupon_redemptionsMaxAggregateInputType = {
  id?: true
  coupon_code_id?: true
  user_id?: true
  original_cost?: true
  discount_amount?: true
  amount_paid?: true
  currency?: true
  item_type?: true
  item_id?: true
  redeemed_at?: true
}

export type Coupon_redemptionsCountAggregateInputType = {
  id?: true
  coupon_code_id?: true
  user_id?: true
  original_cost?: true
  discount_amount?: true
  amount_paid?: true
  currency?: true
  item_type?: true
  item_id?: true
  redeemed_at?: true
  _all?: true
}

export type Coupon_redemptionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which coupon_redemptions to aggregate.
   */
  where?: Prisma.coupon_redemptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of coupon_redemptions to fetch.
   */
  orderBy?: Prisma.coupon_redemptionsOrderByWithRelationInput | Prisma.coupon_redemptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.coupon_redemptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` coupon_redemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` coupon_redemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned coupon_redemptions
  **/
  _count?: true | Coupon_redemptionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Coupon_redemptionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Coupon_redemptionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Coupon_redemptionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Coupon_redemptionsMaxAggregateInputType
}

export type GetCoupon_redemptionsAggregateType<T extends Coupon_redemptionsAggregateArgs> = {
      [P in keyof T & keyof AggregateCoupon_redemptions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCoupon_redemptions[P]>
    : Prisma.GetScalarType<T[P], AggregateCoupon_redemptions[P]>
}




export type coupon_redemptionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.coupon_redemptionsWhereInput
  orderBy?: Prisma.coupon_redemptionsOrderByWithAggregationInput | Prisma.coupon_redemptionsOrderByWithAggregationInput[]
  by: Prisma.Coupon_redemptionsScalarFieldEnum[] | Prisma.Coupon_redemptionsScalarFieldEnum
  having?: Prisma.coupon_redemptionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Coupon_redemptionsCountAggregateInputType | true
  _avg?: Coupon_redemptionsAvgAggregateInputType
  _sum?: Coupon_redemptionsSumAggregateInputType
  _min?: Coupon_redemptionsMinAggregateInputType
  _max?: Coupon_redemptionsMaxAggregateInputType
}

export type Coupon_redemptionsGroupByOutputType = {
  id: string
  coupon_code_id: string | null
  user_id: number | null
  original_cost: number | null
  discount_amount: number | null
  amount_paid: number | null
  currency: string | null
  item_type: string | null
  item_id: string | null
  redeemed_at: Date | null
  _count: Coupon_redemptionsCountAggregateOutputType | null
  _avg: Coupon_redemptionsAvgAggregateOutputType | null
  _sum: Coupon_redemptionsSumAggregateOutputType | null
  _min: Coupon_redemptionsMinAggregateOutputType | null
  _max: Coupon_redemptionsMaxAggregateOutputType | null
}

type GetCoupon_redemptionsGroupByPayload<T extends coupon_redemptionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Coupon_redemptionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Coupon_redemptionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Coupon_redemptionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Coupon_redemptionsGroupByOutputType[P]>
      }
    >
  >



export type coupon_redemptionsWhereInput = {
  AND?: Prisma.coupon_redemptionsWhereInput | Prisma.coupon_redemptionsWhereInput[]
  OR?: Prisma.coupon_redemptionsWhereInput[]
  NOT?: Prisma.coupon_redemptionsWhereInput | Prisma.coupon_redemptionsWhereInput[]
  id?: Prisma.UuidFilter<"coupon_redemptions"> | string
  coupon_code_id?: Prisma.UuidNullableFilter<"coupon_redemptions"> | string | null
  user_id?: Prisma.IntNullableFilter<"coupon_redemptions"> | number | null
  original_cost?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  discount_amount?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  amount_paid?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  currency?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  item_type?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  item_id?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  redeemed_at?: Prisma.DateTimeNullableFilter<"coupon_redemptions"> | Date | string | null
  coupon_codes?: Prisma.XOR<Prisma.Coupon_codesNullableScalarRelationFilter, Prisma.coupon_codesWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}

export type coupon_redemptionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  coupon_code_id?: Prisma.SortOrderInput | Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  original_cost?: Prisma.SortOrderInput | Prisma.SortOrder
  discount_amount?: Prisma.SortOrderInput | Prisma.SortOrder
  amount_paid?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrderInput | Prisma.SortOrder
  item_type?: Prisma.SortOrderInput | Prisma.SortOrder
  item_id?: Prisma.SortOrderInput | Prisma.SortOrder
  redeemed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  coupon_codes?: Prisma.coupon_codesOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type coupon_redemptionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.coupon_redemptionsWhereInput | Prisma.coupon_redemptionsWhereInput[]
  OR?: Prisma.coupon_redemptionsWhereInput[]
  NOT?: Prisma.coupon_redemptionsWhereInput | Prisma.coupon_redemptionsWhereInput[]
  coupon_code_id?: Prisma.UuidNullableFilter<"coupon_redemptions"> | string | null
  user_id?: Prisma.IntNullableFilter<"coupon_redemptions"> | number | null
  original_cost?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  discount_amount?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  amount_paid?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  currency?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  item_type?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  item_id?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  redeemed_at?: Prisma.DateTimeNullableFilter<"coupon_redemptions"> | Date | string | null
  coupon_codes?: Prisma.XOR<Prisma.Coupon_codesNullableScalarRelationFilter, Prisma.coupon_codesWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}, "id">

export type coupon_redemptionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  coupon_code_id?: Prisma.SortOrderInput | Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  original_cost?: Prisma.SortOrderInput | Prisma.SortOrder
  discount_amount?: Prisma.SortOrderInput | Prisma.SortOrder
  amount_paid?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrderInput | Prisma.SortOrder
  item_type?: Prisma.SortOrderInput | Prisma.SortOrder
  item_id?: Prisma.SortOrderInput | Prisma.SortOrder
  redeemed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.coupon_redemptionsCountOrderByAggregateInput
  _avg?: Prisma.coupon_redemptionsAvgOrderByAggregateInput
  _max?: Prisma.coupon_redemptionsMaxOrderByAggregateInput
  _min?: Prisma.coupon_redemptionsMinOrderByAggregateInput
  _sum?: Prisma.coupon_redemptionsSumOrderByAggregateInput
}

export type coupon_redemptionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.coupon_redemptionsScalarWhereWithAggregatesInput | Prisma.coupon_redemptionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.coupon_redemptionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.coupon_redemptionsScalarWhereWithAggregatesInput | Prisma.coupon_redemptionsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"coupon_redemptions"> | string
  coupon_code_id?: Prisma.UuidNullableWithAggregatesFilter<"coupon_redemptions"> | string | null
  user_id?: Prisma.IntNullableWithAggregatesFilter<"coupon_redemptions"> | number | null
  original_cost?: Prisma.FloatNullableWithAggregatesFilter<"coupon_redemptions"> | number | null
  discount_amount?: Prisma.FloatNullableWithAggregatesFilter<"coupon_redemptions"> | number | null
  amount_paid?: Prisma.FloatNullableWithAggregatesFilter<"coupon_redemptions"> | number | null
  currency?: Prisma.StringNullableWithAggregatesFilter<"coupon_redemptions"> | string | null
  item_type?: Prisma.StringNullableWithAggregatesFilter<"coupon_redemptions"> | string | null
  item_id?: Prisma.StringNullableWithAggregatesFilter<"coupon_redemptions"> | string | null
  redeemed_at?: Prisma.DateTimeNullableWithAggregatesFilter<"coupon_redemptions"> | Date | string | null
}

export type coupon_redemptionsCreateInput = {
  id: string
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
  coupon_codes?: Prisma.coupon_codesCreateNestedOneWithoutCoupon_redemptionsInput
  users?: Prisma.usersCreateNestedOneWithoutCoupon_redemptionsInput
}

export type coupon_redemptionsUncheckedCreateInput = {
  id: string
  coupon_code_id?: string | null
  user_id?: number | null
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
}

export type coupon_redemptionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  coupon_codes?: Prisma.coupon_codesUpdateOneWithoutCoupon_redemptionsNestedInput
  users?: Prisma.usersUpdateOneWithoutCoupon_redemptionsNestedInput
}

export type coupon_redemptionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coupon_code_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type coupon_redemptionsCreateManyInput = {
  id: string
  coupon_code_id?: string | null
  user_id?: number | null
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
}

export type coupon_redemptionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type coupon_redemptionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coupon_code_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Coupon_redemptionsListRelationFilter = {
  every?: Prisma.coupon_redemptionsWhereInput
  some?: Prisma.coupon_redemptionsWhereInput
  none?: Prisma.coupon_redemptionsWhereInput
}

export type coupon_redemptionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type coupon_redemptionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  coupon_code_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  original_cost?: Prisma.SortOrder
  discount_amount?: Prisma.SortOrder
  amount_paid?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  item_type?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  redeemed_at?: Prisma.SortOrder
}

export type coupon_redemptionsAvgOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  original_cost?: Prisma.SortOrder
  discount_amount?: Prisma.SortOrder
  amount_paid?: Prisma.SortOrder
}

export type coupon_redemptionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  coupon_code_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  original_cost?: Prisma.SortOrder
  discount_amount?: Prisma.SortOrder
  amount_paid?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  item_type?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  redeemed_at?: Prisma.SortOrder
}

export type coupon_redemptionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  coupon_code_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  original_cost?: Prisma.SortOrder
  discount_amount?: Prisma.SortOrder
  amount_paid?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  item_type?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  redeemed_at?: Prisma.SortOrder
}

export type coupon_redemptionsSumOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  original_cost?: Prisma.SortOrder
  discount_amount?: Prisma.SortOrder
  amount_paid?: Prisma.SortOrder
}

export type coupon_redemptionsCreateNestedManyWithoutCoupon_codesInput = {
  create?: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput, Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput> | Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput[] | Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput[]
  connectOrCreate?: Prisma.coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput | Prisma.coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput[]
  createMany?: Prisma.coupon_redemptionsCreateManyCoupon_codesInputEnvelope
  connect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
}

export type coupon_redemptionsUncheckedCreateNestedManyWithoutCoupon_codesInput = {
  create?: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput, Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput> | Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput[] | Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput[]
  connectOrCreate?: Prisma.coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput | Prisma.coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput[]
  createMany?: Prisma.coupon_redemptionsCreateManyCoupon_codesInputEnvelope
  connect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
}

export type coupon_redemptionsUpdateManyWithoutCoupon_codesNestedInput = {
  create?: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput, Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput> | Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput[] | Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput[]
  connectOrCreate?: Prisma.coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput | Prisma.coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput[]
  upsert?: Prisma.coupon_redemptionsUpsertWithWhereUniqueWithoutCoupon_codesInput | Prisma.coupon_redemptionsUpsertWithWhereUniqueWithoutCoupon_codesInput[]
  createMany?: Prisma.coupon_redemptionsCreateManyCoupon_codesInputEnvelope
  set?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  disconnect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  delete?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  connect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  update?: Prisma.coupon_redemptionsUpdateWithWhereUniqueWithoutCoupon_codesInput | Prisma.coupon_redemptionsUpdateWithWhereUniqueWithoutCoupon_codesInput[]
  updateMany?: Prisma.coupon_redemptionsUpdateManyWithWhereWithoutCoupon_codesInput | Prisma.coupon_redemptionsUpdateManyWithWhereWithoutCoupon_codesInput[]
  deleteMany?: Prisma.coupon_redemptionsScalarWhereInput | Prisma.coupon_redemptionsScalarWhereInput[]
}

export type coupon_redemptionsUncheckedUpdateManyWithoutCoupon_codesNestedInput = {
  create?: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput, Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput> | Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput[] | Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput[]
  connectOrCreate?: Prisma.coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput | Prisma.coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput[]
  upsert?: Prisma.coupon_redemptionsUpsertWithWhereUniqueWithoutCoupon_codesInput | Prisma.coupon_redemptionsUpsertWithWhereUniqueWithoutCoupon_codesInput[]
  createMany?: Prisma.coupon_redemptionsCreateManyCoupon_codesInputEnvelope
  set?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  disconnect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  delete?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  connect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  update?: Prisma.coupon_redemptionsUpdateWithWhereUniqueWithoutCoupon_codesInput | Prisma.coupon_redemptionsUpdateWithWhereUniqueWithoutCoupon_codesInput[]
  updateMany?: Prisma.coupon_redemptionsUpdateManyWithWhereWithoutCoupon_codesInput | Prisma.coupon_redemptionsUpdateManyWithWhereWithoutCoupon_codesInput[]
  deleteMany?: Prisma.coupon_redemptionsScalarWhereInput | Prisma.coupon_redemptionsScalarWhereInput[]
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type coupon_redemptionsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutUsersInput, Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput> | Prisma.coupon_redemptionsCreateWithoutUsersInput[] | Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.coupon_redemptionsCreateOrConnectWithoutUsersInput | Prisma.coupon_redemptionsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.coupon_redemptionsCreateManyUsersInputEnvelope
  connect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
}

export type coupon_redemptionsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutUsersInput, Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput> | Prisma.coupon_redemptionsCreateWithoutUsersInput[] | Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.coupon_redemptionsCreateOrConnectWithoutUsersInput | Prisma.coupon_redemptionsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.coupon_redemptionsCreateManyUsersInputEnvelope
  connect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
}

export type coupon_redemptionsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutUsersInput, Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput> | Prisma.coupon_redemptionsCreateWithoutUsersInput[] | Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.coupon_redemptionsCreateOrConnectWithoutUsersInput | Prisma.coupon_redemptionsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.coupon_redemptionsUpsertWithWhereUniqueWithoutUsersInput | Prisma.coupon_redemptionsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.coupon_redemptionsCreateManyUsersInputEnvelope
  set?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  disconnect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  delete?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  connect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  update?: Prisma.coupon_redemptionsUpdateWithWhereUniqueWithoutUsersInput | Prisma.coupon_redemptionsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.coupon_redemptionsUpdateManyWithWhereWithoutUsersInput | Prisma.coupon_redemptionsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.coupon_redemptionsScalarWhereInput | Prisma.coupon_redemptionsScalarWhereInput[]
}

export type coupon_redemptionsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutUsersInput, Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput> | Prisma.coupon_redemptionsCreateWithoutUsersInput[] | Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.coupon_redemptionsCreateOrConnectWithoutUsersInput | Prisma.coupon_redemptionsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.coupon_redemptionsUpsertWithWhereUniqueWithoutUsersInput | Prisma.coupon_redemptionsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.coupon_redemptionsCreateManyUsersInputEnvelope
  set?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  disconnect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  delete?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  connect?: Prisma.coupon_redemptionsWhereUniqueInput | Prisma.coupon_redemptionsWhereUniqueInput[]
  update?: Prisma.coupon_redemptionsUpdateWithWhereUniqueWithoutUsersInput | Prisma.coupon_redemptionsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.coupon_redemptionsUpdateManyWithWhereWithoutUsersInput | Prisma.coupon_redemptionsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.coupon_redemptionsScalarWhereInput | Prisma.coupon_redemptionsScalarWhereInput[]
}

export type coupon_redemptionsCreateWithoutCoupon_codesInput = {
  id: string
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
  users?: Prisma.usersCreateNestedOneWithoutCoupon_redemptionsInput
}

export type coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput = {
  id: string
  user_id?: number | null
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
}

export type coupon_redemptionsCreateOrConnectWithoutCoupon_codesInput = {
  where: Prisma.coupon_redemptionsWhereUniqueInput
  create: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput, Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput>
}

export type coupon_redemptionsCreateManyCoupon_codesInputEnvelope = {
  data: Prisma.coupon_redemptionsCreateManyCoupon_codesInput | Prisma.coupon_redemptionsCreateManyCoupon_codesInput[]
  skipDuplicates?: boolean
}

export type coupon_redemptionsUpsertWithWhereUniqueWithoutCoupon_codesInput = {
  where: Prisma.coupon_redemptionsWhereUniqueInput
  update: Prisma.XOR<Prisma.coupon_redemptionsUpdateWithoutCoupon_codesInput, Prisma.coupon_redemptionsUncheckedUpdateWithoutCoupon_codesInput>
  create: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutCoupon_codesInput, Prisma.coupon_redemptionsUncheckedCreateWithoutCoupon_codesInput>
}

export type coupon_redemptionsUpdateWithWhereUniqueWithoutCoupon_codesInput = {
  where: Prisma.coupon_redemptionsWhereUniqueInput
  data: Prisma.XOR<Prisma.coupon_redemptionsUpdateWithoutCoupon_codesInput, Prisma.coupon_redemptionsUncheckedUpdateWithoutCoupon_codesInput>
}

export type coupon_redemptionsUpdateManyWithWhereWithoutCoupon_codesInput = {
  where: Prisma.coupon_redemptionsScalarWhereInput
  data: Prisma.XOR<Prisma.coupon_redemptionsUpdateManyMutationInput, Prisma.coupon_redemptionsUncheckedUpdateManyWithoutCoupon_codesInput>
}

export type coupon_redemptionsScalarWhereInput = {
  AND?: Prisma.coupon_redemptionsScalarWhereInput | Prisma.coupon_redemptionsScalarWhereInput[]
  OR?: Prisma.coupon_redemptionsScalarWhereInput[]
  NOT?: Prisma.coupon_redemptionsScalarWhereInput | Prisma.coupon_redemptionsScalarWhereInput[]
  id?: Prisma.UuidFilter<"coupon_redemptions"> | string
  coupon_code_id?: Prisma.UuidNullableFilter<"coupon_redemptions"> | string | null
  user_id?: Prisma.IntNullableFilter<"coupon_redemptions"> | number | null
  original_cost?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  discount_amount?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  amount_paid?: Prisma.FloatNullableFilter<"coupon_redemptions"> | number | null
  currency?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  item_type?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  item_id?: Prisma.StringNullableFilter<"coupon_redemptions"> | string | null
  redeemed_at?: Prisma.DateTimeNullableFilter<"coupon_redemptions"> | Date | string | null
}

export type coupon_redemptionsCreateWithoutUsersInput = {
  id: string
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
  coupon_codes?: Prisma.coupon_codesCreateNestedOneWithoutCoupon_redemptionsInput
}

export type coupon_redemptionsUncheckedCreateWithoutUsersInput = {
  id: string
  coupon_code_id?: string | null
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
}

export type coupon_redemptionsCreateOrConnectWithoutUsersInput = {
  where: Prisma.coupon_redemptionsWhereUniqueInput
  create: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutUsersInput, Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput>
}

export type coupon_redemptionsCreateManyUsersInputEnvelope = {
  data: Prisma.coupon_redemptionsCreateManyUsersInput | Prisma.coupon_redemptionsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type coupon_redemptionsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.coupon_redemptionsWhereUniqueInput
  update: Prisma.XOR<Prisma.coupon_redemptionsUpdateWithoutUsersInput, Prisma.coupon_redemptionsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.coupon_redemptionsCreateWithoutUsersInput, Prisma.coupon_redemptionsUncheckedCreateWithoutUsersInput>
}

export type coupon_redemptionsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.coupon_redemptionsWhereUniqueInput
  data: Prisma.XOR<Prisma.coupon_redemptionsUpdateWithoutUsersInput, Prisma.coupon_redemptionsUncheckedUpdateWithoutUsersInput>
}

export type coupon_redemptionsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.coupon_redemptionsScalarWhereInput
  data: Prisma.XOR<Prisma.coupon_redemptionsUpdateManyMutationInput, Prisma.coupon_redemptionsUncheckedUpdateManyWithoutUsersInput>
}

export type coupon_redemptionsCreateManyCoupon_codesInput = {
  id: string
  user_id?: number | null
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
}

export type coupon_redemptionsUpdateWithoutCoupon_codesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneWithoutCoupon_redemptionsNestedInput
}

export type coupon_redemptionsUncheckedUpdateWithoutCoupon_codesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type coupon_redemptionsUncheckedUpdateManyWithoutCoupon_codesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type coupon_redemptionsCreateManyUsersInput = {
  id: string
  coupon_code_id?: string | null
  original_cost?: number | null
  discount_amount?: number | null
  amount_paid?: number | null
  currency?: string | null
  item_type?: string | null
  item_id?: string | null
  redeemed_at?: Date | string | null
}

export type coupon_redemptionsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  coupon_codes?: Prisma.coupon_codesUpdateOneWithoutCoupon_redemptionsNestedInput
}

export type coupon_redemptionsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coupon_code_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type coupon_redemptionsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  coupon_code_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  original_cost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discount_amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  amount_paid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type coupon_redemptionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  coupon_code_id?: boolean
  user_id?: boolean
  original_cost?: boolean
  discount_amount?: boolean
  amount_paid?: boolean
  currency?: boolean
  item_type?: boolean
  item_id?: boolean
  redeemed_at?: boolean
  coupon_codes?: boolean | Prisma.coupon_redemptions$coupon_codesArgs<ExtArgs>
  users?: boolean | Prisma.coupon_redemptions$usersArgs<ExtArgs>
}, ExtArgs["result"]["coupon_redemptions"]>

export type coupon_redemptionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  coupon_code_id?: boolean
  user_id?: boolean
  original_cost?: boolean
  discount_amount?: boolean
  amount_paid?: boolean
  currency?: boolean
  item_type?: boolean
  item_id?: boolean
  redeemed_at?: boolean
  coupon_codes?: boolean | Prisma.coupon_redemptions$coupon_codesArgs<ExtArgs>
  users?: boolean | Prisma.coupon_redemptions$usersArgs<ExtArgs>
}, ExtArgs["result"]["coupon_redemptions"]>

export type coupon_redemptionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  coupon_code_id?: boolean
  user_id?: boolean
  original_cost?: boolean
  discount_amount?: boolean
  amount_paid?: boolean
  currency?: boolean
  item_type?: boolean
  item_id?: boolean
  redeemed_at?: boolean
  coupon_codes?: boolean | Prisma.coupon_redemptions$coupon_codesArgs<ExtArgs>
  users?: boolean | Prisma.coupon_redemptions$usersArgs<ExtArgs>
}, ExtArgs["result"]["coupon_redemptions"]>

export type coupon_redemptionsSelectScalar = {
  id?: boolean
  coupon_code_id?: boolean
  user_id?: boolean
  original_cost?: boolean
  discount_amount?: boolean
  amount_paid?: boolean
  currency?: boolean
  item_type?: boolean
  item_id?: boolean
  redeemed_at?: boolean
}

export type coupon_redemptionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "coupon_code_id" | "user_id" | "original_cost" | "discount_amount" | "amount_paid" | "currency" | "item_type" | "item_id" | "redeemed_at", ExtArgs["result"]["coupon_redemptions"]>
export type coupon_redemptionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coupon_codes?: boolean | Prisma.coupon_redemptions$coupon_codesArgs<ExtArgs>
  users?: boolean | Prisma.coupon_redemptions$usersArgs<ExtArgs>
}
export type coupon_redemptionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coupon_codes?: boolean | Prisma.coupon_redemptions$coupon_codesArgs<ExtArgs>
  users?: boolean | Prisma.coupon_redemptions$usersArgs<ExtArgs>
}
export type coupon_redemptionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coupon_codes?: boolean | Prisma.coupon_redemptions$coupon_codesArgs<ExtArgs>
  users?: boolean | Prisma.coupon_redemptions$usersArgs<ExtArgs>
}

export type $coupon_redemptionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "coupon_redemptions"
  objects: {
    coupon_codes: Prisma.$coupon_codesPayload<ExtArgs> | null
    users: Prisma.$usersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    coupon_code_id: string | null
    user_id: number | null
    original_cost: number | null
    discount_amount: number | null
    amount_paid: number | null
    currency: string | null
    item_type: string | null
    item_id: string | null
    redeemed_at: Date | null
  }, ExtArgs["result"]["coupon_redemptions"]>
  composites: {}
}

export type coupon_redemptionsGetPayload<S extends boolean | null | undefined | coupon_redemptionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload, S>

export type coupon_redemptionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<coupon_redemptionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Coupon_redemptionsCountAggregateInputType | true
  }

export interface coupon_redemptionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['coupon_redemptions'], meta: { name: 'coupon_redemptions' } }
  /**
   * Find zero or one Coupon_redemptions that matches the filter.
   * @param {coupon_redemptionsFindUniqueArgs} args - Arguments to find a Coupon_redemptions
   * @example
   * // Get one Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends coupon_redemptionsFindUniqueArgs>(args: Prisma.SelectSubset<T, coupon_redemptionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__coupon_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Coupon_redemptions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {coupon_redemptionsFindUniqueOrThrowArgs} args - Arguments to find a Coupon_redemptions
   * @example
   * // Get one Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends coupon_redemptionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, coupon_redemptionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__coupon_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Coupon_redemptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coupon_redemptionsFindFirstArgs} args - Arguments to find a Coupon_redemptions
   * @example
   * // Get one Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends coupon_redemptionsFindFirstArgs>(args?: Prisma.SelectSubset<T, coupon_redemptionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__coupon_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Coupon_redemptions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coupon_redemptionsFindFirstOrThrowArgs} args - Arguments to find a Coupon_redemptions
   * @example
   * // Get one Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends coupon_redemptionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, coupon_redemptionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__coupon_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Coupon_redemptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coupon_redemptionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.findMany()
   * 
   * // Get first 10 Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const coupon_redemptionsWithIdOnly = await prisma.coupon_redemptions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends coupon_redemptionsFindManyArgs>(args?: Prisma.SelectSubset<T, coupon_redemptionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Coupon_redemptions.
   * @param {coupon_redemptionsCreateArgs} args - Arguments to create a Coupon_redemptions.
   * @example
   * // Create one Coupon_redemptions
   * const Coupon_redemptions = await prisma.coupon_redemptions.create({
   *   data: {
   *     // ... data to create a Coupon_redemptions
   *   }
   * })
   * 
   */
  create<T extends coupon_redemptionsCreateArgs>(args: Prisma.SelectSubset<T, coupon_redemptionsCreateArgs<ExtArgs>>): Prisma.Prisma__coupon_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Coupon_redemptions.
   * @param {coupon_redemptionsCreateManyArgs} args - Arguments to create many Coupon_redemptions.
   * @example
   * // Create many Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends coupon_redemptionsCreateManyArgs>(args?: Prisma.SelectSubset<T, coupon_redemptionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Coupon_redemptions and returns the data saved in the database.
   * @param {coupon_redemptionsCreateManyAndReturnArgs} args - Arguments to create many Coupon_redemptions.
   * @example
   * // Create many Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Coupon_redemptions and only return the `id`
   * const coupon_redemptionsWithIdOnly = await prisma.coupon_redemptions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends coupon_redemptionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, coupon_redemptionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Coupon_redemptions.
   * @param {coupon_redemptionsDeleteArgs} args - Arguments to delete one Coupon_redemptions.
   * @example
   * // Delete one Coupon_redemptions
   * const Coupon_redemptions = await prisma.coupon_redemptions.delete({
   *   where: {
   *     // ... filter to delete one Coupon_redemptions
   *   }
   * })
   * 
   */
  delete<T extends coupon_redemptionsDeleteArgs>(args: Prisma.SelectSubset<T, coupon_redemptionsDeleteArgs<ExtArgs>>): Prisma.Prisma__coupon_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Coupon_redemptions.
   * @param {coupon_redemptionsUpdateArgs} args - Arguments to update one Coupon_redemptions.
   * @example
   * // Update one Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends coupon_redemptionsUpdateArgs>(args: Prisma.SelectSubset<T, coupon_redemptionsUpdateArgs<ExtArgs>>): Prisma.Prisma__coupon_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Coupon_redemptions.
   * @param {coupon_redemptionsDeleteManyArgs} args - Arguments to filter Coupon_redemptions to delete.
   * @example
   * // Delete a few Coupon_redemptions
   * const { count } = await prisma.coupon_redemptions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends coupon_redemptionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, coupon_redemptionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Coupon_redemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coupon_redemptionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends coupon_redemptionsUpdateManyArgs>(args: Prisma.SelectSubset<T, coupon_redemptionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Coupon_redemptions and returns the data updated in the database.
   * @param {coupon_redemptionsUpdateManyAndReturnArgs} args - Arguments to update many Coupon_redemptions.
   * @example
   * // Update many Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Coupon_redemptions and only return the `id`
   * const coupon_redemptionsWithIdOnly = await prisma.coupon_redemptions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends coupon_redemptionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, coupon_redemptionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Coupon_redemptions.
   * @param {coupon_redemptionsUpsertArgs} args - Arguments to update or create a Coupon_redemptions.
   * @example
   * // Update or create a Coupon_redemptions
   * const coupon_redemptions = await prisma.coupon_redemptions.upsert({
   *   create: {
   *     // ... data to create a Coupon_redemptions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Coupon_redemptions we want to update
   *   }
   * })
   */
  upsert<T extends coupon_redemptionsUpsertArgs>(args: Prisma.SelectSubset<T, coupon_redemptionsUpsertArgs<ExtArgs>>): Prisma.Prisma__coupon_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$coupon_redemptionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Coupon_redemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coupon_redemptionsCountArgs} args - Arguments to filter Coupon_redemptions to count.
   * @example
   * // Count the number of Coupon_redemptions
   * const count = await prisma.coupon_redemptions.count({
   *   where: {
   *     // ... the filter for the Coupon_redemptions we want to count
   *   }
   * })
  **/
  count<T extends coupon_redemptionsCountArgs>(
    args?: Prisma.Subset<T, coupon_redemptionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Coupon_redemptionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Coupon_redemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Coupon_redemptionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Coupon_redemptionsAggregateArgs>(args: Prisma.Subset<T, Coupon_redemptionsAggregateArgs>): Prisma.PrismaPromise<GetCoupon_redemptionsAggregateType<T>>

  /**
   * Group by Coupon_redemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coupon_redemptionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends coupon_redemptionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: coupon_redemptionsGroupByArgs['orderBy'] }
      : { orderBy?: coupon_redemptionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, coupon_redemptionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCoupon_redemptionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the coupon_redemptions model
 */
readonly fields: coupon_redemptionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for coupon_redemptions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__coupon_redemptionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  coupon_codes<T extends Prisma.coupon_redemptions$coupon_codesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.coupon_redemptions$coupon_codesArgs<ExtArgs>>): Prisma.Prisma__coupon_codesClient<runtime.Types.Result.GetResult<Prisma.$coupon_codesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.coupon_redemptions$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.coupon_redemptions$usersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the coupon_redemptions model
 */
export interface coupon_redemptionsFieldRefs {
  readonly id: Prisma.FieldRef<"coupon_redemptions", 'String'>
  readonly coupon_code_id: Prisma.FieldRef<"coupon_redemptions", 'String'>
  readonly user_id: Prisma.FieldRef<"coupon_redemptions", 'Int'>
  readonly original_cost: Prisma.FieldRef<"coupon_redemptions", 'Float'>
  readonly discount_amount: Prisma.FieldRef<"coupon_redemptions", 'Float'>
  readonly amount_paid: Prisma.FieldRef<"coupon_redemptions", 'Float'>
  readonly currency: Prisma.FieldRef<"coupon_redemptions", 'String'>
  readonly item_type: Prisma.FieldRef<"coupon_redemptions", 'String'>
  readonly item_id: Prisma.FieldRef<"coupon_redemptions", 'String'>
  readonly redeemed_at: Prisma.FieldRef<"coupon_redemptions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * coupon_redemptions findUnique
 */
export type coupon_redemptionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which coupon_redemptions to fetch.
   */
  where: Prisma.coupon_redemptionsWhereUniqueInput
}

/**
 * coupon_redemptions findUniqueOrThrow
 */
export type coupon_redemptionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which coupon_redemptions to fetch.
   */
  where: Prisma.coupon_redemptionsWhereUniqueInput
}

/**
 * coupon_redemptions findFirst
 */
export type coupon_redemptionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which coupon_redemptions to fetch.
   */
  where?: Prisma.coupon_redemptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of coupon_redemptions to fetch.
   */
  orderBy?: Prisma.coupon_redemptionsOrderByWithRelationInput | Prisma.coupon_redemptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for coupon_redemptions.
   */
  cursor?: Prisma.coupon_redemptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` coupon_redemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` coupon_redemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of coupon_redemptions.
   */
  distinct?: Prisma.Coupon_redemptionsScalarFieldEnum | Prisma.Coupon_redemptionsScalarFieldEnum[]
}

/**
 * coupon_redemptions findFirstOrThrow
 */
export type coupon_redemptionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which coupon_redemptions to fetch.
   */
  where?: Prisma.coupon_redemptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of coupon_redemptions to fetch.
   */
  orderBy?: Prisma.coupon_redemptionsOrderByWithRelationInput | Prisma.coupon_redemptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for coupon_redemptions.
   */
  cursor?: Prisma.coupon_redemptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` coupon_redemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` coupon_redemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of coupon_redemptions.
   */
  distinct?: Prisma.Coupon_redemptionsScalarFieldEnum | Prisma.Coupon_redemptionsScalarFieldEnum[]
}

/**
 * coupon_redemptions findMany
 */
export type coupon_redemptionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which coupon_redemptions to fetch.
   */
  where?: Prisma.coupon_redemptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of coupon_redemptions to fetch.
   */
  orderBy?: Prisma.coupon_redemptionsOrderByWithRelationInput | Prisma.coupon_redemptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing coupon_redemptions.
   */
  cursor?: Prisma.coupon_redemptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` coupon_redemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` coupon_redemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of coupon_redemptions.
   */
  distinct?: Prisma.Coupon_redemptionsScalarFieldEnum | Prisma.Coupon_redemptionsScalarFieldEnum[]
}

/**
 * coupon_redemptions create
 */
export type coupon_redemptionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * The data needed to create a coupon_redemptions.
   */
  data: Prisma.XOR<Prisma.coupon_redemptionsCreateInput, Prisma.coupon_redemptionsUncheckedCreateInput>
}

/**
 * coupon_redemptions createMany
 */
export type coupon_redemptionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many coupon_redemptions.
   */
  data: Prisma.coupon_redemptionsCreateManyInput | Prisma.coupon_redemptionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * coupon_redemptions createManyAndReturn
 */
export type coupon_redemptionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * The data used to create many coupon_redemptions.
   */
  data: Prisma.coupon_redemptionsCreateManyInput | Prisma.coupon_redemptionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * coupon_redemptions update
 */
export type coupon_redemptionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * The data needed to update a coupon_redemptions.
   */
  data: Prisma.XOR<Prisma.coupon_redemptionsUpdateInput, Prisma.coupon_redemptionsUncheckedUpdateInput>
  /**
   * Choose, which coupon_redemptions to update.
   */
  where: Prisma.coupon_redemptionsWhereUniqueInput
}

/**
 * coupon_redemptions updateMany
 */
export type coupon_redemptionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update coupon_redemptions.
   */
  data: Prisma.XOR<Prisma.coupon_redemptionsUpdateManyMutationInput, Prisma.coupon_redemptionsUncheckedUpdateManyInput>
  /**
   * Filter which coupon_redemptions to update
   */
  where?: Prisma.coupon_redemptionsWhereInput
  /**
   * Limit how many coupon_redemptions to update.
   */
  limit?: number
}

/**
 * coupon_redemptions updateManyAndReturn
 */
export type coupon_redemptionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * The data used to update coupon_redemptions.
   */
  data: Prisma.XOR<Prisma.coupon_redemptionsUpdateManyMutationInput, Prisma.coupon_redemptionsUncheckedUpdateManyInput>
  /**
   * Filter which coupon_redemptions to update
   */
  where?: Prisma.coupon_redemptionsWhereInput
  /**
   * Limit how many coupon_redemptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * coupon_redemptions upsert
 */
export type coupon_redemptionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * The filter to search for the coupon_redemptions to update in case it exists.
   */
  where: Prisma.coupon_redemptionsWhereUniqueInput
  /**
   * In case the coupon_redemptions found by the `where` argument doesn't exist, create a new coupon_redemptions with this data.
   */
  create: Prisma.XOR<Prisma.coupon_redemptionsCreateInput, Prisma.coupon_redemptionsUncheckedCreateInput>
  /**
   * In case the coupon_redemptions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.coupon_redemptionsUpdateInput, Prisma.coupon_redemptionsUncheckedUpdateInput>
}

/**
 * coupon_redemptions delete
 */
export type coupon_redemptionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
  /**
   * Filter which coupon_redemptions to delete.
   */
  where: Prisma.coupon_redemptionsWhereUniqueInput
}

/**
 * coupon_redemptions deleteMany
 */
export type coupon_redemptionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which coupon_redemptions to delete
   */
  where?: Prisma.coupon_redemptionsWhereInput
  /**
   * Limit how many coupon_redemptions to delete.
   */
  limit?: number
}

/**
 * coupon_redemptions.coupon_codes
 */
export type coupon_redemptions$coupon_codesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_codes
   */
  select?: Prisma.coupon_codesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_codes
   */
  omit?: Prisma.coupon_codesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_codesInclude<ExtArgs> | null
  where?: Prisma.coupon_codesWhereInput
}

/**
 * coupon_redemptions.users
 */
export type coupon_redemptions$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * coupon_redemptions without action
 */
export type coupon_redemptionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coupon_redemptions
   */
  select?: Prisma.coupon_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coupon_redemptions
   */
  omit?: Prisma.coupon_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coupon_redemptionsInclude<ExtArgs> | null
}
