
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `join_requests` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model join_requests
 * 
 */
export type join_requestsModel = runtime.Types.Result.DefaultSelection<Prisma.$join_requestsPayload>

export type AggregateJoin_requests = {
  _count: Join_requestsCountAggregateOutputType | null
  _avg: Join_requestsAvgAggregateOutputType | null
  _sum: Join_requestsSumAggregateOutputType | null
  _min: Join_requestsMinAggregateOutputType | null
  _max: Join_requestsMaxAggregateOutputType | null
}

export type Join_requestsAvgAggregateOutputType = {
  id: number | null
  user_id: number | null
}

export type Join_requestsSumAggregateOutputType = {
  id: number | null
  user_id: number | null
}

export type Join_requestsMinAggregateOutputType = {
  id: number | null
  user_id: number | null
  organization_id: string | null
  status: string | null
  requested_at: Date | null
}

export type Join_requestsMaxAggregateOutputType = {
  id: number | null
  user_id: number | null
  organization_id: string | null
  status: string | null
  requested_at: Date | null
}

export type Join_requestsCountAggregateOutputType = {
  id: number
  user_id: number
  organization_id: number
  status: number
  requested_at: number
  _all: number
}


export type Join_requestsAvgAggregateInputType = {
  id?: true
  user_id?: true
}

export type Join_requestsSumAggregateInputType = {
  id?: true
  user_id?: true
}

export type Join_requestsMinAggregateInputType = {
  id?: true
  user_id?: true
  organization_id?: true
  status?: true
  requested_at?: true
}

export type Join_requestsMaxAggregateInputType = {
  id?: true
  user_id?: true
  organization_id?: true
  status?: true
  requested_at?: true
}

export type Join_requestsCountAggregateInputType = {
  id?: true
  user_id?: true
  organization_id?: true
  status?: true
  requested_at?: true
  _all?: true
}

export type Join_requestsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which join_requests to aggregate.
   */
  where?: Prisma.join_requestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of join_requests to fetch.
   */
  orderBy?: Prisma.join_requestsOrderByWithRelationInput | Prisma.join_requestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.join_requestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` join_requests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` join_requests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned join_requests
  **/
  _count?: true | Join_requestsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Join_requestsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Join_requestsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Join_requestsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Join_requestsMaxAggregateInputType
}

export type GetJoin_requestsAggregateType<T extends Join_requestsAggregateArgs> = {
      [P in keyof T & keyof AggregateJoin_requests]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJoin_requests[P]>
    : Prisma.GetScalarType<T[P], AggregateJoin_requests[P]>
}




export type join_requestsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.join_requestsWhereInput
  orderBy?: Prisma.join_requestsOrderByWithAggregationInput | Prisma.join_requestsOrderByWithAggregationInput[]
  by: Prisma.Join_requestsScalarFieldEnum[] | Prisma.Join_requestsScalarFieldEnum
  having?: Prisma.join_requestsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Join_requestsCountAggregateInputType | true
  _avg?: Join_requestsAvgAggregateInputType
  _sum?: Join_requestsSumAggregateInputType
  _min?: Join_requestsMinAggregateInputType
  _max?: Join_requestsMaxAggregateInputType
}

export type Join_requestsGroupByOutputType = {
  id: number
  user_id: number | null
  organization_id: string | null
  status: string | null
  requested_at: Date | null
  _count: Join_requestsCountAggregateOutputType | null
  _avg: Join_requestsAvgAggregateOutputType | null
  _sum: Join_requestsSumAggregateOutputType | null
  _min: Join_requestsMinAggregateOutputType | null
  _max: Join_requestsMaxAggregateOutputType | null
}

type GetJoin_requestsGroupByPayload<T extends join_requestsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Join_requestsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Join_requestsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Join_requestsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Join_requestsGroupByOutputType[P]>
      }
    >
  >



export type join_requestsWhereInput = {
  AND?: Prisma.join_requestsWhereInput | Prisma.join_requestsWhereInput[]
  OR?: Prisma.join_requestsWhereInput[]
  NOT?: Prisma.join_requestsWhereInput | Prisma.join_requestsWhereInput[]
  id?: Prisma.IntFilter<"join_requests"> | number
  user_id?: Prisma.IntNullableFilter<"join_requests"> | number | null
  organization_id?: Prisma.UuidNullableFilter<"join_requests"> | string | null
  status?: Prisma.StringNullableFilter<"join_requests"> | string | null
  requested_at?: Prisma.DateTimeNullableFilter<"join_requests"> | Date | string | null
  organizations?: Prisma.XOR<Prisma.OrganizationsNullableScalarRelationFilter, Prisma.organizationsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}

export type join_requestsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  organization_id?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  requested_at?: Prisma.SortOrderInput | Prisma.SortOrder
  organizations?: Prisma.organizationsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type join_requestsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  user_id_organization_id?: Prisma.join_requestsUser_idOrganization_idCompoundUniqueInput
  AND?: Prisma.join_requestsWhereInput | Prisma.join_requestsWhereInput[]
  OR?: Prisma.join_requestsWhereInput[]
  NOT?: Prisma.join_requestsWhereInput | Prisma.join_requestsWhereInput[]
  user_id?: Prisma.IntNullableFilter<"join_requests"> | number | null
  organization_id?: Prisma.UuidNullableFilter<"join_requests"> | string | null
  status?: Prisma.StringNullableFilter<"join_requests"> | string | null
  requested_at?: Prisma.DateTimeNullableFilter<"join_requests"> | Date | string | null
  organizations?: Prisma.XOR<Prisma.OrganizationsNullableScalarRelationFilter, Prisma.organizationsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}, "id" | "user_id_organization_id">

export type join_requestsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  organization_id?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  requested_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.join_requestsCountOrderByAggregateInput
  _avg?: Prisma.join_requestsAvgOrderByAggregateInput
  _max?: Prisma.join_requestsMaxOrderByAggregateInput
  _min?: Prisma.join_requestsMinOrderByAggregateInput
  _sum?: Prisma.join_requestsSumOrderByAggregateInput
}

export type join_requestsScalarWhereWithAggregatesInput = {
  AND?: Prisma.join_requestsScalarWhereWithAggregatesInput | Prisma.join_requestsScalarWhereWithAggregatesInput[]
  OR?: Prisma.join_requestsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.join_requestsScalarWhereWithAggregatesInput | Prisma.join_requestsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"join_requests"> | number
  user_id?: Prisma.IntNullableWithAggregatesFilter<"join_requests"> | number | null
  organization_id?: Prisma.UuidNullableWithAggregatesFilter<"join_requests"> | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"join_requests"> | string | null
  requested_at?: Prisma.DateTimeNullableWithAggregatesFilter<"join_requests"> | Date | string | null
}

export type join_requestsCreateInput = {
  status?: string | null
  requested_at?: Date | string | null
  organizations?: Prisma.organizationsCreateNestedOneWithoutJoin_requestsInput
  users?: Prisma.usersCreateNestedOneWithoutJoin_requestsInput
}

export type join_requestsUncheckedCreateInput = {
  id?: number
  user_id?: number | null
  organization_id?: string | null
  status?: string | null
  requested_at?: Date | string | null
}

export type join_requestsUpdateInput = {
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  organizations?: Prisma.organizationsUpdateOneWithoutJoin_requestsNestedInput
  users?: Prisma.usersUpdateOneWithoutJoin_requestsNestedInput
}

export type join_requestsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  organization_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type join_requestsCreateManyInput = {
  id?: number
  user_id?: number | null
  organization_id?: string | null
  status?: string | null
  requested_at?: Date | string | null
}

export type join_requestsUpdateManyMutationInput = {
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type join_requestsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  organization_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type join_requestsUser_idOrganization_idCompoundUniqueInput = {
  user_id: number
  organization_id: string
}

export type join_requestsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  requested_at?: Prisma.SortOrder
}

export type join_requestsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type join_requestsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  requested_at?: Prisma.SortOrder
}

export type join_requestsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  requested_at?: Prisma.SortOrder
}

export type join_requestsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type Join_requestsListRelationFilter = {
  every?: Prisma.join_requestsWhereInput
  some?: Prisma.join_requestsWhereInput
  none?: Prisma.join_requestsWhereInput
}

export type join_requestsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type join_requestsCreateNestedManyWithoutOrganizationsInput = {
  create?: Prisma.XOR<Prisma.join_requestsCreateWithoutOrganizationsInput, Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput> | Prisma.join_requestsCreateWithoutOrganizationsInput[] | Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.join_requestsCreateOrConnectWithoutOrganizationsInput | Prisma.join_requestsCreateOrConnectWithoutOrganizationsInput[]
  createMany?: Prisma.join_requestsCreateManyOrganizationsInputEnvelope
  connect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
}

export type join_requestsUncheckedCreateNestedManyWithoutOrganizationsInput = {
  create?: Prisma.XOR<Prisma.join_requestsCreateWithoutOrganizationsInput, Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput> | Prisma.join_requestsCreateWithoutOrganizationsInput[] | Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.join_requestsCreateOrConnectWithoutOrganizationsInput | Prisma.join_requestsCreateOrConnectWithoutOrganizationsInput[]
  createMany?: Prisma.join_requestsCreateManyOrganizationsInputEnvelope
  connect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
}

export type join_requestsUpdateManyWithoutOrganizationsNestedInput = {
  create?: Prisma.XOR<Prisma.join_requestsCreateWithoutOrganizationsInput, Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput> | Prisma.join_requestsCreateWithoutOrganizationsInput[] | Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.join_requestsCreateOrConnectWithoutOrganizationsInput | Prisma.join_requestsCreateOrConnectWithoutOrganizationsInput[]
  upsert?: Prisma.join_requestsUpsertWithWhereUniqueWithoutOrganizationsInput | Prisma.join_requestsUpsertWithWhereUniqueWithoutOrganizationsInput[]
  createMany?: Prisma.join_requestsCreateManyOrganizationsInputEnvelope
  set?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  disconnect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  delete?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  connect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  update?: Prisma.join_requestsUpdateWithWhereUniqueWithoutOrganizationsInput | Prisma.join_requestsUpdateWithWhereUniqueWithoutOrganizationsInput[]
  updateMany?: Prisma.join_requestsUpdateManyWithWhereWithoutOrganizationsInput | Prisma.join_requestsUpdateManyWithWhereWithoutOrganizationsInput[]
  deleteMany?: Prisma.join_requestsScalarWhereInput | Prisma.join_requestsScalarWhereInput[]
}

export type join_requestsUncheckedUpdateManyWithoutOrganizationsNestedInput = {
  create?: Prisma.XOR<Prisma.join_requestsCreateWithoutOrganizationsInput, Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput> | Prisma.join_requestsCreateWithoutOrganizationsInput[] | Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.join_requestsCreateOrConnectWithoutOrganizationsInput | Prisma.join_requestsCreateOrConnectWithoutOrganizationsInput[]
  upsert?: Prisma.join_requestsUpsertWithWhereUniqueWithoutOrganizationsInput | Prisma.join_requestsUpsertWithWhereUniqueWithoutOrganizationsInput[]
  createMany?: Prisma.join_requestsCreateManyOrganizationsInputEnvelope
  set?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  disconnect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  delete?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  connect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  update?: Prisma.join_requestsUpdateWithWhereUniqueWithoutOrganizationsInput | Prisma.join_requestsUpdateWithWhereUniqueWithoutOrganizationsInput[]
  updateMany?: Prisma.join_requestsUpdateManyWithWhereWithoutOrganizationsInput | Prisma.join_requestsUpdateManyWithWhereWithoutOrganizationsInput[]
  deleteMany?: Prisma.join_requestsScalarWhereInput | Prisma.join_requestsScalarWhereInput[]
}

export type join_requestsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.join_requestsCreateWithoutUsersInput, Prisma.join_requestsUncheckedCreateWithoutUsersInput> | Prisma.join_requestsCreateWithoutUsersInput[] | Prisma.join_requestsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.join_requestsCreateOrConnectWithoutUsersInput | Prisma.join_requestsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.join_requestsCreateManyUsersInputEnvelope
  connect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
}

export type join_requestsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.join_requestsCreateWithoutUsersInput, Prisma.join_requestsUncheckedCreateWithoutUsersInput> | Prisma.join_requestsCreateWithoutUsersInput[] | Prisma.join_requestsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.join_requestsCreateOrConnectWithoutUsersInput | Prisma.join_requestsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.join_requestsCreateManyUsersInputEnvelope
  connect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
}

export type join_requestsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.join_requestsCreateWithoutUsersInput, Prisma.join_requestsUncheckedCreateWithoutUsersInput> | Prisma.join_requestsCreateWithoutUsersInput[] | Prisma.join_requestsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.join_requestsCreateOrConnectWithoutUsersInput | Prisma.join_requestsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.join_requestsUpsertWithWhereUniqueWithoutUsersInput | Prisma.join_requestsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.join_requestsCreateManyUsersInputEnvelope
  set?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  disconnect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  delete?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  connect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  update?: Prisma.join_requestsUpdateWithWhereUniqueWithoutUsersInput | Prisma.join_requestsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.join_requestsUpdateManyWithWhereWithoutUsersInput | Prisma.join_requestsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.join_requestsScalarWhereInput | Prisma.join_requestsScalarWhereInput[]
}

export type join_requestsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.join_requestsCreateWithoutUsersInput, Prisma.join_requestsUncheckedCreateWithoutUsersInput> | Prisma.join_requestsCreateWithoutUsersInput[] | Prisma.join_requestsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.join_requestsCreateOrConnectWithoutUsersInput | Prisma.join_requestsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.join_requestsUpsertWithWhereUniqueWithoutUsersInput | Prisma.join_requestsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.join_requestsCreateManyUsersInputEnvelope
  set?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  disconnect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  delete?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  connect?: Prisma.join_requestsWhereUniqueInput | Prisma.join_requestsWhereUniqueInput[]
  update?: Prisma.join_requestsUpdateWithWhereUniqueWithoutUsersInput | Prisma.join_requestsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.join_requestsUpdateManyWithWhereWithoutUsersInput | Prisma.join_requestsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.join_requestsScalarWhereInput | Prisma.join_requestsScalarWhereInput[]
}

export type join_requestsCreateWithoutOrganizationsInput = {
  status?: string | null
  requested_at?: Date | string | null
  users?: Prisma.usersCreateNestedOneWithoutJoin_requestsInput
}

export type join_requestsUncheckedCreateWithoutOrganizationsInput = {
  id?: number
  user_id?: number | null
  status?: string | null
  requested_at?: Date | string | null
}

export type join_requestsCreateOrConnectWithoutOrganizationsInput = {
  where: Prisma.join_requestsWhereUniqueInput
  create: Prisma.XOR<Prisma.join_requestsCreateWithoutOrganizationsInput, Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput>
}

export type join_requestsCreateManyOrganizationsInputEnvelope = {
  data: Prisma.join_requestsCreateManyOrganizationsInput | Prisma.join_requestsCreateManyOrganizationsInput[]
  skipDuplicates?: boolean
}

export type join_requestsUpsertWithWhereUniqueWithoutOrganizationsInput = {
  where: Prisma.join_requestsWhereUniqueInput
  update: Prisma.XOR<Prisma.join_requestsUpdateWithoutOrganizationsInput, Prisma.join_requestsUncheckedUpdateWithoutOrganizationsInput>
  create: Prisma.XOR<Prisma.join_requestsCreateWithoutOrganizationsInput, Prisma.join_requestsUncheckedCreateWithoutOrganizationsInput>
}

export type join_requestsUpdateWithWhereUniqueWithoutOrganizationsInput = {
  where: Prisma.join_requestsWhereUniqueInput
  data: Prisma.XOR<Prisma.join_requestsUpdateWithoutOrganizationsInput, Prisma.join_requestsUncheckedUpdateWithoutOrganizationsInput>
}

export type join_requestsUpdateManyWithWhereWithoutOrganizationsInput = {
  where: Prisma.join_requestsScalarWhereInput
  data: Prisma.XOR<Prisma.join_requestsUpdateManyMutationInput, Prisma.join_requestsUncheckedUpdateManyWithoutOrganizationsInput>
}

export type join_requestsScalarWhereInput = {
  AND?: Prisma.join_requestsScalarWhereInput | Prisma.join_requestsScalarWhereInput[]
  OR?: Prisma.join_requestsScalarWhereInput[]
  NOT?: Prisma.join_requestsScalarWhereInput | Prisma.join_requestsScalarWhereInput[]
  id?: Prisma.IntFilter<"join_requests"> | number
  user_id?: Prisma.IntNullableFilter<"join_requests"> | number | null
  organization_id?: Prisma.UuidNullableFilter<"join_requests"> | string | null
  status?: Prisma.StringNullableFilter<"join_requests"> | string | null
  requested_at?: Prisma.DateTimeNullableFilter<"join_requests"> | Date | string | null
}

export type join_requestsCreateWithoutUsersInput = {
  status?: string | null
  requested_at?: Date | string | null
  organizations?: Prisma.organizationsCreateNestedOneWithoutJoin_requestsInput
}

export type join_requestsUncheckedCreateWithoutUsersInput = {
  id?: number
  organization_id?: string | null
  status?: string | null
  requested_at?: Date | string | null
}

export type join_requestsCreateOrConnectWithoutUsersInput = {
  where: Prisma.join_requestsWhereUniqueInput
  create: Prisma.XOR<Prisma.join_requestsCreateWithoutUsersInput, Prisma.join_requestsUncheckedCreateWithoutUsersInput>
}

export type join_requestsCreateManyUsersInputEnvelope = {
  data: Prisma.join_requestsCreateManyUsersInput | Prisma.join_requestsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type join_requestsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.join_requestsWhereUniqueInput
  update: Prisma.XOR<Prisma.join_requestsUpdateWithoutUsersInput, Prisma.join_requestsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.join_requestsCreateWithoutUsersInput, Prisma.join_requestsUncheckedCreateWithoutUsersInput>
}

export type join_requestsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.join_requestsWhereUniqueInput
  data: Prisma.XOR<Prisma.join_requestsUpdateWithoutUsersInput, Prisma.join_requestsUncheckedUpdateWithoutUsersInput>
}

export type join_requestsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.join_requestsScalarWhereInput
  data: Prisma.XOR<Prisma.join_requestsUpdateManyMutationInput, Prisma.join_requestsUncheckedUpdateManyWithoutUsersInput>
}

export type join_requestsCreateManyOrganizationsInput = {
  id?: number
  user_id?: number | null
  status?: string | null
  requested_at?: Date | string | null
}

export type join_requestsUpdateWithoutOrganizationsInput = {
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneWithoutJoin_requestsNestedInput
}

export type join_requestsUncheckedUpdateWithoutOrganizationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type join_requestsUncheckedUpdateManyWithoutOrganizationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type join_requestsCreateManyUsersInput = {
  id?: number
  organization_id?: string | null
  status?: string | null
  requested_at?: Date | string | null
}

export type join_requestsUpdateWithoutUsersInput = {
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  organizations?: Prisma.organizationsUpdateOneWithoutJoin_requestsNestedInput
}

export type join_requestsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  organization_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type join_requestsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  organization_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requested_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type join_requestsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  organization_id?: boolean
  status?: boolean
  requested_at?: boolean
  organizations?: boolean | Prisma.join_requests$organizationsArgs<ExtArgs>
  users?: boolean | Prisma.join_requests$usersArgs<ExtArgs>
}, ExtArgs["result"]["join_requests"]>

export type join_requestsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  organization_id?: boolean
  status?: boolean
  requested_at?: boolean
  organizations?: boolean | Prisma.join_requests$organizationsArgs<ExtArgs>
  users?: boolean | Prisma.join_requests$usersArgs<ExtArgs>
}, ExtArgs["result"]["join_requests"]>

export type join_requestsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  organization_id?: boolean
  status?: boolean
  requested_at?: boolean
  organizations?: boolean | Prisma.join_requests$organizationsArgs<ExtArgs>
  users?: boolean | Prisma.join_requests$usersArgs<ExtArgs>
}, ExtArgs["result"]["join_requests"]>

export type join_requestsSelectScalar = {
  id?: boolean
  user_id?: boolean
  organization_id?: boolean
  status?: boolean
  requested_at?: boolean
}

export type join_requestsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "organization_id" | "status" | "requested_at", ExtArgs["result"]["join_requests"]>
export type join_requestsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organizations?: boolean | Prisma.join_requests$organizationsArgs<ExtArgs>
  users?: boolean | Prisma.join_requests$usersArgs<ExtArgs>
}
export type join_requestsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organizations?: boolean | Prisma.join_requests$organizationsArgs<ExtArgs>
  users?: boolean | Prisma.join_requests$usersArgs<ExtArgs>
}
export type join_requestsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organizations?: boolean | Prisma.join_requests$organizationsArgs<ExtArgs>
  users?: boolean | Prisma.join_requests$usersArgs<ExtArgs>
}

export type $join_requestsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "join_requests"
  objects: {
    organizations: Prisma.$organizationsPayload<ExtArgs> | null
    users: Prisma.$usersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_id: number | null
    organization_id: string | null
    status: string | null
    requested_at: Date | null
  }, ExtArgs["result"]["join_requests"]>
  composites: {}
}

export type join_requestsGetPayload<S extends boolean | null | undefined | join_requestsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$join_requestsPayload, S>

export type join_requestsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<join_requestsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Join_requestsCountAggregateInputType | true
  }

export interface join_requestsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['join_requests'], meta: { name: 'join_requests' } }
  /**
   * Find zero or one Join_requests that matches the filter.
   * @param {join_requestsFindUniqueArgs} args - Arguments to find a Join_requests
   * @example
   * // Get one Join_requests
   * const join_requests = await prisma.join_requests.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends join_requestsFindUniqueArgs>(args: Prisma.SelectSubset<T, join_requestsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__join_requestsClient<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Join_requests that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {join_requestsFindUniqueOrThrowArgs} args - Arguments to find a Join_requests
   * @example
   * // Get one Join_requests
   * const join_requests = await prisma.join_requests.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends join_requestsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, join_requestsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__join_requestsClient<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Join_requests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {join_requestsFindFirstArgs} args - Arguments to find a Join_requests
   * @example
   * // Get one Join_requests
   * const join_requests = await prisma.join_requests.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends join_requestsFindFirstArgs>(args?: Prisma.SelectSubset<T, join_requestsFindFirstArgs<ExtArgs>>): Prisma.Prisma__join_requestsClient<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Join_requests that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {join_requestsFindFirstOrThrowArgs} args - Arguments to find a Join_requests
   * @example
   * // Get one Join_requests
   * const join_requests = await prisma.join_requests.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends join_requestsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, join_requestsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__join_requestsClient<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Join_requests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {join_requestsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Join_requests
   * const join_requests = await prisma.join_requests.findMany()
   * 
   * // Get first 10 Join_requests
   * const join_requests = await prisma.join_requests.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const join_requestsWithIdOnly = await prisma.join_requests.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends join_requestsFindManyArgs>(args?: Prisma.SelectSubset<T, join_requestsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Join_requests.
   * @param {join_requestsCreateArgs} args - Arguments to create a Join_requests.
   * @example
   * // Create one Join_requests
   * const Join_requests = await prisma.join_requests.create({
   *   data: {
   *     // ... data to create a Join_requests
   *   }
   * })
   * 
   */
  create<T extends join_requestsCreateArgs>(args: Prisma.SelectSubset<T, join_requestsCreateArgs<ExtArgs>>): Prisma.Prisma__join_requestsClient<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Join_requests.
   * @param {join_requestsCreateManyArgs} args - Arguments to create many Join_requests.
   * @example
   * // Create many Join_requests
   * const join_requests = await prisma.join_requests.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends join_requestsCreateManyArgs>(args?: Prisma.SelectSubset<T, join_requestsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Join_requests and returns the data saved in the database.
   * @param {join_requestsCreateManyAndReturnArgs} args - Arguments to create many Join_requests.
   * @example
   * // Create many Join_requests
   * const join_requests = await prisma.join_requests.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Join_requests and only return the `id`
   * const join_requestsWithIdOnly = await prisma.join_requests.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends join_requestsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, join_requestsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Join_requests.
   * @param {join_requestsDeleteArgs} args - Arguments to delete one Join_requests.
   * @example
   * // Delete one Join_requests
   * const Join_requests = await prisma.join_requests.delete({
   *   where: {
   *     // ... filter to delete one Join_requests
   *   }
   * })
   * 
   */
  delete<T extends join_requestsDeleteArgs>(args: Prisma.SelectSubset<T, join_requestsDeleteArgs<ExtArgs>>): Prisma.Prisma__join_requestsClient<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Join_requests.
   * @param {join_requestsUpdateArgs} args - Arguments to update one Join_requests.
   * @example
   * // Update one Join_requests
   * const join_requests = await prisma.join_requests.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends join_requestsUpdateArgs>(args: Prisma.SelectSubset<T, join_requestsUpdateArgs<ExtArgs>>): Prisma.Prisma__join_requestsClient<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Join_requests.
   * @param {join_requestsDeleteManyArgs} args - Arguments to filter Join_requests to delete.
   * @example
   * // Delete a few Join_requests
   * const { count } = await prisma.join_requests.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends join_requestsDeleteManyArgs>(args?: Prisma.SelectSubset<T, join_requestsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Join_requests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {join_requestsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Join_requests
   * const join_requests = await prisma.join_requests.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends join_requestsUpdateManyArgs>(args: Prisma.SelectSubset<T, join_requestsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Join_requests and returns the data updated in the database.
   * @param {join_requestsUpdateManyAndReturnArgs} args - Arguments to update many Join_requests.
   * @example
   * // Update many Join_requests
   * const join_requests = await prisma.join_requests.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Join_requests and only return the `id`
   * const join_requestsWithIdOnly = await prisma.join_requests.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends join_requestsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, join_requestsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Join_requests.
   * @param {join_requestsUpsertArgs} args - Arguments to update or create a Join_requests.
   * @example
   * // Update or create a Join_requests
   * const join_requests = await prisma.join_requests.upsert({
   *   create: {
   *     // ... data to create a Join_requests
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Join_requests we want to update
   *   }
   * })
   */
  upsert<T extends join_requestsUpsertArgs>(args: Prisma.SelectSubset<T, join_requestsUpsertArgs<ExtArgs>>): Prisma.Prisma__join_requestsClient<runtime.Types.Result.GetResult<Prisma.$join_requestsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Join_requests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {join_requestsCountArgs} args - Arguments to filter Join_requests to count.
   * @example
   * // Count the number of Join_requests
   * const count = await prisma.join_requests.count({
   *   where: {
   *     // ... the filter for the Join_requests we want to count
   *   }
   * })
  **/
  count<T extends join_requestsCountArgs>(
    args?: Prisma.Subset<T, join_requestsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Join_requestsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Join_requests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Join_requestsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Join_requestsAggregateArgs>(args: Prisma.Subset<T, Join_requestsAggregateArgs>): Prisma.PrismaPromise<GetJoin_requestsAggregateType<T>>

  /**
   * Group by Join_requests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {join_requestsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends join_requestsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: join_requestsGroupByArgs['orderBy'] }
      : { orderBy?: join_requestsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, join_requestsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJoin_requestsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the join_requests model
 */
readonly fields: join_requestsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for join_requests.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__join_requestsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organizations<T extends Prisma.join_requests$organizationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.join_requests$organizationsArgs<ExtArgs>>): Prisma.Prisma__organizationsClient<runtime.Types.Result.GetResult<Prisma.$organizationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.join_requests$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.join_requests$usersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the join_requests model
 */
export interface join_requestsFieldRefs {
  readonly id: Prisma.FieldRef<"join_requests", 'Int'>
  readonly user_id: Prisma.FieldRef<"join_requests", 'Int'>
  readonly organization_id: Prisma.FieldRef<"join_requests", 'String'>
  readonly status: Prisma.FieldRef<"join_requests", 'String'>
  readonly requested_at: Prisma.FieldRef<"join_requests", 'DateTime'>
}
    

// Custom InputTypes
/**
 * join_requests findUnique
 */
export type join_requestsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * Filter, which join_requests to fetch.
   */
  where: Prisma.join_requestsWhereUniqueInput
}

/**
 * join_requests findUniqueOrThrow
 */
export type join_requestsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * Filter, which join_requests to fetch.
   */
  where: Prisma.join_requestsWhereUniqueInput
}

/**
 * join_requests findFirst
 */
export type join_requestsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * Filter, which join_requests to fetch.
   */
  where?: Prisma.join_requestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of join_requests to fetch.
   */
  orderBy?: Prisma.join_requestsOrderByWithRelationInput | Prisma.join_requestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for join_requests.
   */
  cursor?: Prisma.join_requestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` join_requests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` join_requests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of join_requests.
   */
  distinct?: Prisma.Join_requestsScalarFieldEnum | Prisma.Join_requestsScalarFieldEnum[]
}

/**
 * join_requests findFirstOrThrow
 */
export type join_requestsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * Filter, which join_requests to fetch.
   */
  where?: Prisma.join_requestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of join_requests to fetch.
   */
  orderBy?: Prisma.join_requestsOrderByWithRelationInput | Prisma.join_requestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for join_requests.
   */
  cursor?: Prisma.join_requestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` join_requests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` join_requests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of join_requests.
   */
  distinct?: Prisma.Join_requestsScalarFieldEnum | Prisma.Join_requestsScalarFieldEnum[]
}

/**
 * join_requests findMany
 */
export type join_requestsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * Filter, which join_requests to fetch.
   */
  where?: Prisma.join_requestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of join_requests to fetch.
   */
  orderBy?: Prisma.join_requestsOrderByWithRelationInput | Prisma.join_requestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing join_requests.
   */
  cursor?: Prisma.join_requestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` join_requests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` join_requests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of join_requests.
   */
  distinct?: Prisma.Join_requestsScalarFieldEnum | Prisma.Join_requestsScalarFieldEnum[]
}

/**
 * join_requests create
 */
export type join_requestsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * The data needed to create a join_requests.
   */
  data?: Prisma.XOR<Prisma.join_requestsCreateInput, Prisma.join_requestsUncheckedCreateInput>
}

/**
 * join_requests createMany
 */
export type join_requestsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many join_requests.
   */
  data: Prisma.join_requestsCreateManyInput | Prisma.join_requestsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * join_requests createManyAndReturn
 */
export type join_requestsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * The data used to create many join_requests.
   */
  data: Prisma.join_requestsCreateManyInput | Prisma.join_requestsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * join_requests update
 */
export type join_requestsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * The data needed to update a join_requests.
   */
  data: Prisma.XOR<Prisma.join_requestsUpdateInput, Prisma.join_requestsUncheckedUpdateInput>
  /**
   * Choose, which join_requests to update.
   */
  where: Prisma.join_requestsWhereUniqueInput
}

/**
 * join_requests updateMany
 */
export type join_requestsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update join_requests.
   */
  data: Prisma.XOR<Prisma.join_requestsUpdateManyMutationInput, Prisma.join_requestsUncheckedUpdateManyInput>
  /**
   * Filter which join_requests to update
   */
  where?: Prisma.join_requestsWhereInput
  /**
   * Limit how many join_requests to update.
   */
  limit?: number
}

/**
 * join_requests updateManyAndReturn
 */
export type join_requestsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * The data used to update join_requests.
   */
  data: Prisma.XOR<Prisma.join_requestsUpdateManyMutationInput, Prisma.join_requestsUncheckedUpdateManyInput>
  /**
   * Filter which join_requests to update
   */
  where?: Prisma.join_requestsWhereInput
  /**
   * Limit how many join_requests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * join_requests upsert
 */
export type join_requestsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * The filter to search for the join_requests to update in case it exists.
   */
  where: Prisma.join_requestsWhereUniqueInput
  /**
   * In case the join_requests found by the `where` argument doesn't exist, create a new join_requests with this data.
   */
  create: Prisma.XOR<Prisma.join_requestsCreateInput, Prisma.join_requestsUncheckedCreateInput>
  /**
   * In case the join_requests was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.join_requestsUpdateInput, Prisma.join_requestsUncheckedUpdateInput>
}

/**
 * join_requests delete
 */
export type join_requestsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
  /**
   * Filter which join_requests to delete.
   */
  where: Prisma.join_requestsWhereUniqueInput
}

/**
 * join_requests deleteMany
 */
export type join_requestsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which join_requests to delete
   */
  where?: Prisma.join_requestsWhereInput
  /**
   * Limit how many join_requests to delete.
   */
  limit?: number
}

/**
 * join_requests.organizations
 */
export type join_requests$organizationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the organizations
   */
  select?: Prisma.organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the organizations
   */
  omit?: Prisma.organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.organizationsInclude<ExtArgs> | null
  where?: Prisma.organizationsWhereInput
}

/**
 * join_requests.users
 */
export type join_requests$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * join_requests without action
 */
export type join_requestsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the join_requests
   */
  select?: Prisma.join_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the join_requests
   */
  omit?: Prisma.join_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.join_requestsInclude<ExtArgs> | null
}
