
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `user_organizations` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model user_organizations
 * 
 */
export type user_organizationsModel = runtime.Types.Result.DefaultSelection<Prisma.$user_organizationsPayload>

export type AggregateUser_organizations = {
  _count: User_organizationsCountAggregateOutputType | null
  _avg: User_organizationsAvgAggregateOutputType | null
  _sum: User_organizationsSumAggregateOutputType | null
  _min: User_organizationsMinAggregateOutputType | null
  _max: User_organizationsMaxAggregateOutputType | null
}

export type User_organizationsAvgAggregateOutputType = {
  user_id: number | null
}

export type User_organizationsSumAggregateOutputType = {
  user_id: number | null
}

export type User_organizationsMinAggregateOutputType = {
  user_id: number | null
  organization_id: string | null
  membership_tier_id: string | null
  payment_status: string | null
  joined_at: Date | null
  role: string | null
}

export type User_organizationsMaxAggregateOutputType = {
  user_id: number | null
  organization_id: string | null
  membership_tier_id: string | null
  payment_status: string | null
  joined_at: Date | null
  role: string | null
}

export type User_organizationsCountAggregateOutputType = {
  user_id: number
  organization_id: number
  membership_tier_id: number
  payment_status: number
  joined_at: number
  role: number
  _all: number
}


export type User_organizationsAvgAggregateInputType = {
  user_id?: true
}

export type User_organizationsSumAggregateInputType = {
  user_id?: true
}

export type User_organizationsMinAggregateInputType = {
  user_id?: true
  organization_id?: true
  membership_tier_id?: true
  payment_status?: true
  joined_at?: true
  role?: true
}

export type User_organizationsMaxAggregateInputType = {
  user_id?: true
  organization_id?: true
  membership_tier_id?: true
  payment_status?: true
  joined_at?: true
  role?: true
}

export type User_organizationsCountAggregateInputType = {
  user_id?: true
  organization_id?: true
  membership_tier_id?: true
  payment_status?: true
  joined_at?: true
  role?: true
  _all?: true
}

export type User_organizationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_organizations to aggregate.
   */
  where?: Prisma.user_organizationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_organizations to fetch.
   */
  orderBy?: Prisma.user_organizationsOrderByWithRelationInput | Prisma.user_organizationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.user_organizationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_organizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_organizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned user_organizations
  **/
  _count?: true | User_organizationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: User_organizationsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: User_organizationsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: User_organizationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: User_organizationsMaxAggregateInputType
}

export type GetUser_organizationsAggregateType<T extends User_organizationsAggregateArgs> = {
      [P in keyof T & keyof AggregateUser_organizations]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser_organizations[P]>
    : Prisma.GetScalarType<T[P], AggregateUser_organizations[P]>
}




export type user_organizationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_organizationsWhereInput
  orderBy?: Prisma.user_organizationsOrderByWithAggregationInput | Prisma.user_organizationsOrderByWithAggregationInput[]
  by: Prisma.User_organizationsScalarFieldEnum[] | Prisma.User_organizationsScalarFieldEnum
  having?: Prisma.user_organizationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: User_organizationsCountAggregateInputType | true
  _avg?: User_organizationsAvgAggregateInputType
  _sum?: User_organizationsSumAggregateInputType
  _min?: User_organizationsMinAggregateInputType
  _max?: User_organizationsMaxAggregateInputType
}

export type User_organizationsGroupByOutputType = {
  user_id: number
  organization_id: string
  membership_tier_id: string | null
  payment_status: string | null
  joined_at: Date | null
  role: string | null
  _count: User_organizationsCountAggregateOutputType | null
  _avg: User_organizationsAvgAggregateOutputType | null
  _sum: User_organizationsSumAggregateOutputType | null
  _min: User_organizationsMinAggregateOutputType | null
  _max: User_organizationsMaxAggregateOutputType | null
}

type GetUser_organizationsGroupByPayload<T extends user_organizationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<User_organizationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof User_organizationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], User_organizationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], User_organizationsGroupByOutputType[P]>
      }
    >
  >



export type user_organizationsWhereInput = {
  AND?: Prisma.user_organizationsWhereInput | Prisma.user_organizationsWhereInput[]
  OR?: Prisma.user_organizationsWhereInput[]
  NOT?: Prisma.user_organizationsWhereInput | Prisma.user_organizationsWhereInput[]
  user_id?: Prisma.IntFilter<"user_organizations"> | number
  organization_id?: Prisma.UuidFilter<"user_organizations"> | string
  membership_tier_id?: Prisma.UuidNullableFilter<"user_organizations"> | string | null
  payment_status?: Prisma.StringNullableFilter<"user_organizations"> | string | null
  joined_at?: Prisma.DateTimeNullableFilter<"user_organizations"> | Date | string | null
  role?: Prisma.StringNullableFilter<"user_organizations"> | string | null
  membership_tiers?: Prisma.XOR<Prisma.Membership_tiersNullableScalarRelationFilter, Prisma.membership_tiersWhereInput> | null
  organizations?: Prisma.XOR<Prisma.OrganizationsScalarRelationFilter, Prisma.organizationsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type user_organizationsOrderByWithRelationInput = {
  user_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  membership_tier_id?: Prisma.SortOrderInput | Prisma.SortOrder
  payment_status?: Prisma.SortOrderInput | Prisma.SortOrder
  joined_at?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrderInput | Prisma.SortOrder
  membership_tiers?: Prisma.membership_tiersOrderByWithRelationInput
  organizations?: Prisma.organizationsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type user_organizationsWhereUniqueInput = Prisma.AtLeast<{
  user_id_organization_id?: Prisma.user_organizationsUser_idOrganization_idCompoundUniqueInput
  AND?: Prisma.user_organizationsWhereInput | Prisma.user_organizationsWhereInput[]
  OR?: Prisma.user_organizationsWhereInput[]
  NOT?: Prisma.user_organizationsWhereInput | Prisma.user_organizationsWhereInput[]
  user_id?: Prisma.IntFilter<"user_organizations"> | number
  organization_id?: Prisma.UuidFilter<"user_organizations"> | string
  membership_tier_id?: Prisma.UuidNullableFilter<"user_organizations"> | string | null
  payment_status?: Prisma.StringNullableFilter<"user_organizations"> | string | null
  joined_at?: Prisma.DateTimeNullableFilter<"user_organizations"> | Date | string | null
  role?: Prisma.StringNullableFilter<"user_organizations"> | string | null
  membership_tiers?: Prisma.XOR<Prisma.Membership_tiersNullableScalarRelationFilter, Prisma.membership_tiersWhereInput> | null
  organizations?: Prisma.XOR<Prisma.OrganizationsScalarRelationFilter, Prisma.organizationsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "user_id_organization_id">

export type user_organizationsOrderByWithAggregationInput = {
  user_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  membership_tier_id?: Prisma.SortOrderInput | Prisma.SortOrder
  payment_status?: Prisma.SortOrderInput | Prisma.SortOrder
  joined_at?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.user_organizationsCountOrderByAggregateInput
  _avg?: Prisma.user_organizationsAvgOrderByAggregateInput
  _max?: Prisma.user_organizationsMaxOrderByAggregateInput
  _min?: Prisma.user_organizationsMinOrderByAggregateInput
  _sum?: Prisma.user_organizationsSumOrderByAggregateInput
}

export type user_organizationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.user_organizationsScalarWhereWithAggregatesInput | Prisma.user_organizationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.user_organizationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.user_organizationsScalarWhereWithAggregatesInput | Prisma.user_organizationsScalarWhereWithAggregatesInput[]
  user_id?: Prisma.IntWithAggregatesFilter<"user_organizations"> | number
  organization_id?: Prisma.UuidWithAggregatesFilter<"user_organizations"> | string
  membership_tier_id?: Prisma.UuidNullableWithAggregatesFilter<"user_organizations"> | string | null
  payment_status?: Prisma.StringNullableWithAggregatesFilter<"user_organizations"> | string | null
  joined_at?: Prisma.DateTimeNullableWithAggregatesFilter<"user_organizations"> | Date | string | null
  role?: Prisma.StringNullableWithAggregatesFilter<"user_organizations"> | string | null
}

export type user_organizationsCreateInput = {
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
  membership_tiers?: Prisma.membership_tiersCreateNestedOneWithoutUser_organizationsInput
  organizations: Prisma.organizationsCreateNestedOneWithoutUser_organizationsInput
  users: Prisma.usersCreateNestedOneWithoutUser_organizationsInput
}

export type user_organizationsUncheckedCreateInput = {
  user_id: number
  organization_id: string
  membership_tier_id?: string | null
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
}

export type user_organizationsUpdateInput = {
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  membership_tiers?: Prisma.membership_tiersUpdateOneWithoutUser_organizationsNestedInput
  organizations?: Prisma.organizationsUpdateOneRequiredWithoutUser_organizationsNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutUser_organizationsNestedInput
}

export type user_organizationsUncheckedUpdateInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  membership_tier_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type user_organizationsCreateManyInput = {
  user_id: number
  organization_id: string
  membership_tier_id?: string | null
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
}

export type user_organizationsUpdateManyMutationInput = {
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type user_organizationsUncheckedUpdateManyInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  membership_tier_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type User_organizationsListRelationFilter = {
  every?: Prisma.user_organizationsWhereInput
  some?: Prisma.user_organizationsWhereInput
  none?: Prisma.user_organizationsWhereInput
}

export type user_organizationsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type user_organizationsUser_idOrganization_idCompoundUniqueInput = {
  user_id: number
  organization_id: string
}

export type user_organizationsCountOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  membership_tier_id?: Prisma.SortOrder
  payment_status?: Prisma.SortOrder
  joined_at?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type user_organizationsAvgOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
}

export type user_organizationsMaxOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  membership_tier_id?: Prisma.SortOrder
  payment_status?: Prisma.SortOrder
  joined_at?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type user_organizationsMinOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  membership_tier_id?: Prisma.SortOrder
  payment_status?: Prisma.SortOrder
  joined_at?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type user_organizationsSumOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
}

export type user_organizationsCreateNestedManyWithoutMembership_tiersInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutMembership_tiersInput, Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput> | Prisma.user_organizationsCreateWithoutMembership_tiersInput[] | Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutMembership_tiersInput | Prisma.user_organizationsCreateOrConnectWithoutMembership_tiersInput[]
  createMany?: Prisma.user_organizationsCreateManyMembership_tiersInputEnvelope
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
}

export type user_organizationsUncheckedCreateNestedManyWithoutMembership_tiersInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutMembership_tiersInput, Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput> | Prisma.user_organizationsCreateWithoutMembership_tiersInput[] | Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutMembership_tiersInput | Prisma.user_organizationsCreateOrConnectWithoutMembership_tiersInput[]
  createMany?: Prisma.user_organizationsCreateManyMembership_tiersInputEnvelope
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
}

export type user_organizationsUpdateManyWithoutMembership_tiersNestedInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutMembership_tiersInput, Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput> | Prisma.user_organizationsCreateWithoutMembership_tiersInput[] | Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutMembership_tiersInput | Prisma.user_organizationsCreateOrConnectWithoutMembership_tiersInput[]
  upsert?: Prisma.user_organizationsUpsertWithWhereUniqueWithoutMembership_tiersInput | Prisma.user_organizationsUpsertWithWhereUniqueWithoutMembership_tiersInput[]
  createMany?: Prisma.user_organizationsCreateManyMembership_tiersInputEnvelope
  set?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  disconnect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  delete?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  update?: Prisma.user_organizationsUpdateWithWhereUniqueWithoutMembership_tiersInput | Prisma.user_organizationsUpdateWithWhereUniqueWithoutMembership_tiersInput[]
  updateMany?: Prisma.user_organizationsUpdateManyWithWhereWithoutMembership_tiersInput | Prisma.user_organizationsUpdateManyWithWhereWithoutMembership_tiersInput[]
  deleteMany?: Prisma.user_organizationsScalarWhereInput | Prisma.user_organizationsScalarWhereInput[]
}

export type user_organizationsUncheckedUpdateManyWithoutMembership_tiersNestedInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutMembership_tiersInput, Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput> | Prisma.user_organizationsCreateWithoutMembership_tiersInput[] | Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutMembership_tiersInput | Prisma.user_organizationsCreateOrConnectWithoutMembership_tiersInput[]
  upsert?: Prisma.user_organizationsUpsertWithWhereUniqueWithoutMembership_tiersInput | Prisma.user_organizationsUpsertWithWhereUniqueWithoutMembership_tiersInput[]
  createMany?: Prisma.user_organizationsCreateManyMembership_tiersInputEnvelope
  set?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  disconnect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  delete?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  update?: Prisma.user_organizationsUpdateWithWhereUniqueWithoutMembership_tiersInput | Prisma.user_organizationsUpdateWithWhereUniqueWithoutMembership_tiersInput[]
  updateMany?: Prisma.user_organizationsUpdateManyWithWhereWithoutMembership_tiersInput | Prisma.user_organizationsUpdateManyWithWhereWithoutMembership_tiersInput[]
  deleteMany?: Prisma.user_organizationsScalarWhereInput | Prisma.user_organizationsScalarWhereInput[]
}

export type user_organizationsCreateNestedManyWithoutOrganizationsInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutOrganizationsInput, Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput> | Prisma.user_organizationsCreateWithoutOrganizationsInput[] | Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutOrganizationsInput | Prisma.user_organizationsCreateOrConnectWithoutOrganizationsInput[]
  createMany?: Prisma.user_organizationsCreateManyOrganizationsInputEnvelope
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
}

export type user_organizationsUncheckedCreateNestedManyWithoutOrganizationsInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutOrganizationsInput, Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput> | Prisma.user_organizationsCreateWithoutOrganizationsInput[] | Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutOrganizationsInput | Prisma.user_organizationsCreateOrConnectWithoutOrganizationsInput[]
  createMany?: Prisma.user_organizationsCreateManyOrganizationsInputEnvelope
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
}

export type user_organizationsUpdateManyWithoutOrganizationsNestedInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutOrganizationsInput, Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput> | Prisma.user_organizationsCreateWithoutOrganizationsInput[] | Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutOrganizationsInput | Prisma.user_organizationsCreateOrConnectWithoutOrganizationsInput[]
  upsert?: Prisma.user_organizationsUpsertWithWhereUniqueWithoutOrganizationsInput | Prisma.user_organizationsUpsertWithWhereUniqueWithoutOrganizationsInput[]
  createMany?: Prisma.user_organizationsCreateManyOrganizationsInputEnvelope
  set?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  disconnect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  delete?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  update?: Prisma.user_organizationsUpdateWithWhereUniqueWithoutOrganizationsInput | Prisma.user_organizationsUpdateWithWhereUniqueWithoutOrganizationsInput[]
  updateMany?: Prisma.user_organizationsUpdateManyWithWhereWithoutOrganizationsInput | Prisma.user_organizationsUpdateManyWithWhereWithoutOrganizationsInput[]
  deleteMany?: Prisma.user_organizationsScalarWhereInput | Prisma.user_organizationsScalarWhereInput[]
}

export type user_organizationsUncheckedUpdateManyWithoutOrganizationsNestedInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutOrganizationsInput, Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput> | Prisma.user_organizationsCreateWithoutOrganizationsInput[] | Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutOrganizationsInput | Prisma.user_organizationsCreateOrConnectWithoutOrganizationsInput[]
  upsert?: Prisma.user_organizationsUpsertWithWhereUniqueWithoutOrganizationsInput | Prisma.user_organizationsUpsertWithWhereUniqueWithoutOrganizationsInput[]
  createMany?: Prisma.user_organizationsCreateManyOrganizationsInputEnvelope
  set?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  disconnect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  delete?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  update?: Prisma.user_organizationsUpdateWithWhereUniqueWithoutOrganizationsInput | Prisma.user_organizationsUpdateWithWhereUniqueWithoutOrganizationsInput[]
  updateMany?: Prisma.user_organizationsUpdateManyWithWhereWithoutOrganizationsInput | Prisma.user_organizationsUpdateManyWithWhereWithoutOrganizationsInput[]
  deleteMany?: Prisma.user_organizationsScalarWhereInput | Prisma.user_organizationsScalarWhereInput[]
}

export type user_organizationsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutUsersInput, Prisma.user_organizationsUncheckedCreateWithoutUsersInput> | Prisma.user_organizationsCreateWithoutUsersInput[] | Prisma.user_organizationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutUsersInput | Prisma.user_organizationsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.user_organizationsCreateManyUsersInputEnvelope
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
}

export type user_organizationsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutUsersInput, Prisma.user_organizationsUncheckedCreateWithoutUsersInput> | Prisma.user_organizationsCreateWithoutUsersInput[] | Prisma.user_organizationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutUsersInput | Prisma.user_organizationsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.user_organizationsCreateManyUsersInputEnvelope
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
}

export type user_organizationsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutUsersInput, Prisma.user_organizationsUncheckedCreateWithoutUsersInput> | Prisma.user_organizationsCreateWithoutUsersInput[] | Prisma.user_organizationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutUsersInput | Prisma.user_organizationsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.user_organizationsUpsertWithWhereUniqueWithoutUsersInput | Prisma.user_organizationsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.user_organizationsCreateManyUsersInputEnvelope
  set?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  disconnect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  delete?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  update?: Prisma.user_organizationsUpdateWithWhereUniqueWithoutUsersInput | Prisma.user_organizationsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.user_organizationsUpdateManyWithWhereWithoutUsersInput | Prisma.user_organizationsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.user_organizationsScalarWhereInput | Prisma.user_organizationsScalarWhereInput[]
}

export type user_organizationsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.user_organizationsCreateWithoutUsersInput, Prisma.user_organizationsUncheckedCreateWithoutUsersInput> | Prisma.user_organizationsCreateWithoutUsersInput[] | Prisma.user_organizationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_organizationsCreateOrConnectWithoutUsersInput | Prisma.user_organizationsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.user_organizationsUpsertWithWhereUniqueWithoutUsersInput | Prisma.user_organizationsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.user_organizationsCreateManyUsersInputEnvelope
  set?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  disconnect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  delete?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  connect?: Prisma.user_organizationsWhereUniqueInput | Prisma.user_organizationsWhereUniqueInput[]
  update?: Prisma.user_organizationsUpdateWithWhereUniqueWithoutUsersInput | Prisma.user_organizationsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.user_organizationsUpdateManyWithWhereWithoutUsersInput | Prisma.user_organizationsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.user_organizationsScalarWhereInput | Prisma.user_organizationsScalarWhereInput[]
}

export type user_organizationsCreateWithoutMembership_tiersInput = {
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
  organizations: Prisma.organizationsCreateNestedOneWithoutUser_organizationsInput
  users: Prisma.usersCreateNestedOneWithoutUser_organizationsInput
}

export type user_organizationsUncheckedCreateWithoutMembership_tiersInput = {
  user_id: number
  organization_id: string
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
}

export type user_organizationsCreateOrConnectWithoutMembership_tiersInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  create: Prisma.XOR<Prisma.user_organizationsCreateWithoutMembership_tiersInput, Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput>
}

export type user_organizationsCreateManyMembership_tiersInputEnvelope = {
  data: Prisma.user_organizationsCreateManyMembership_tiersInput | Prisma.user_organizationsCreateManyMembership_tiersInput[]
  skipDuplicates?: boolean
}

export type user_organizationsUpsertWithWhereUniqueWithoutMembership_tiersInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  update: Prisma.XOR<Prisma.user_organizationsUpdateWithoutMembership_tiersInput, Prisma.user_organizationsUncheckedUpdateWithoutMembership_tiersInput>
  create: Prisma.XOR<Prisma.user_organizationsCreateWithoutMembership_tiersInput, Prisma.user_organizationsUncheckedCreateWithoutMembership_tiersInput>
}

export type user_organizationsUpdateWithWhereUniqueWithoutMembership_tiersInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  data: Prisma.XOR<Prisma.user_organizationsUpdateWithoutMembership_tiersInput, Prisma.user_organizationsUncheckedUpdateWithoutMembership_tiersInput>
}

export type user_organizationsUpdateManyWithWhereWithoutMembership_tiersInput = {
  where: Prisma.user_organizationsScalarWhereInput
  data: Prisma.XOR<Prisma.user_organizationsUpdateManyMutationInput, Prisma.user_organizationsUncheckedUpdateManyWithoutMembership_tiersInput>
}

export type user_organizationsScalarWhereInput = {
  AND?: Prisma.user_organizationsScalarWhereInput | Prisma.user_organizationsScalarWhereInput[]
  OR?: Prisma.user_organizationsScalarWhereInput[]
  NOT?: Prisma.user_organizationsScalarWhereInput | Prisma.user_organizationsScalarWhereInput[]
  user_id?: Prisma.IntFilter<"user_organizations"> | number
  organization_id?: Prisma.UuidFilter<"user_organizations"> | string
  membership_tier_id?: Prisma.UuidNullableFilter<"user_organizations"> | string | null
  payment_status?: Prisma.StringNullableFilter<"user_organizations"> | string | null
  joined_at?: Prisma.DateTimeNullableFilter<"user_organizations"> | Date | string | null
  role?: Prisma.StringNullableFilter<"user_organizations"> | string | null
}

export type user_organizationsCreateWithoutOrganizationsInput = {
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
  membership_tiers?: Prisma.membership_tiersCreateNestedOneWithoutUser_organizationsInput
  users: Prisma.usersCreateNestedOneWithoutUser_organizationsInput
}

export type user_organizationsUncheckedCreateWithoutOrganizationsInput = {
  user_id: number
  membership_tier_id?: string | null
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
}

export type user_organizationsCreateOrConnectWithoutOrganizationsInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  create: Prisma.XOR<Prisma.user_organizationsCreateWithoutOrganizationsInput, Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput>
}

export type user_organizationsCreateManyOrganizationsInputEnvelope = {
  data: Prisma.user_organizationsCreateManyOrganizationsInput | Prisma.user_organizationsCreateManyOrganizationsInput[]
  skipDuplicates?: boolean
}

export type user_organizationsUpsertWithWhereUniqueWithoutOrganizationsInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  update: Prisma.XOR<Prisma.user_organizationsUpdateWithoutOrganizationsInput, Prisma.user_organizationsUncheckedUpdateWithoutOrganizationsInput>
  create: Prisma.XOR<Prisma.user_organizationsCreateWithoutOrganizationsInput, Prisma.user_organizationsUncheckedCreateWithoutOrganizationsInput>
}

export type user_organizationsUpdateWithWhereUniqueWithoutOrganizationsInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  data: Prisma.XOR<Prisma.user_organizationsUpdateWithoutOrganizationsInput, Prisma.user_organizationsUncheckedUpdateWithoutOrganizationsInput>
}

export type user_organizationsUpdateManyWithWhereWithoutOrganizationsInput = {
  where: Prisma.user_organizationsScalarWhereInput
  data: Prisma.XOR<Prisma.user_organizationsUpdateManyMutationInput, Prisma.user_organizationsUncheckedUpdateManyWithoutOrganizationsInput>
}

export type user_organizationsCreateWithoutUsersInput = {
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
  membership_tiers?: Prisma.membership_tiersCreateNestedOneWithoutUser_organizationsInput
  organizations: Prisma.organizationsCreateNestedOneWithoutUser_organizationsInput
}

export type user_organizationsUncheckedCreateWithoutUsersInput = {
  organization_id: string
  membership_tier_id?: string | null
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
}

export type user_organizationsCreateOrConnectWithoutUsersInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  create: Prisma.XOR<Prisma.user_organizationsCreateWithoutUsersInput, Prisma.user_organizationsUncheckedCreateWithoutUsersInput>
}

export type user_organizationsCreateManyUsersInputEnvelope = {
  data: Prisma.user_organizationsCreateManyUsersInput | Prisma.user_organizationsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type user_organizationsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  update: Prisma.XOR<Prisma.user_organizationsUpdateWithoutUsersInput, Prisma.user_organizationsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.user_organizationsCreateWithoutUsersInput, Prisma.user_organizationsUncheckedCreateWithoutUsersInput>
}

export type user_organizationsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.user_organizationsWhereUniqueInput
  data: Prisma.XOR<Prisma.user_organizationsUpdateWithoutUsersInput, Prisma.user_organizationsUncheckedUpdateWithoutUsersInput>
}

export type user_organizationsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.user_organizationsScalarWhereInput
  data: Prisma.XOR<Prisma.user_organizationsUpdateManyMutationInput, Prisma.user_organizationsUncheckedUpdateManyWithoutUsersInput>
}

export type user_organizationsCreateManyMembership_tiersInput = {
  user_id: number
  organization_id: string
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
}

export type user_organizationsUpdateWithoutMembership_tiersInput = {
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizations?: Prisma.organizationsUpdateOneRequiredWithoutUser_organizationsNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutUser_organizationsNestedInput
}

export type user_organizationsUncheckedUpdateWithoutMembership_tiersInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type user_organizationsUncheckedUpdateManyWithoutMembership_tiersInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type user_organizationsCreateManyOrganizationsInput = {
  user_id: number
  membership_tier_id?: string | null
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
}

export type user_organizationsUpdateWithoutOrganizationsInput = {
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  membership_tiers?: Prisma.membership_tiersUpdateOneWithoutUser_organizationsNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutUser_organizationsNestedInput
}

export type user_organizationsUncheckedUpdateWithoutOrganizationsInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type user_organizationsUncheckedUpdateManyWithoutOrganizationsInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type user_organizationsCreateManyUsersInput = {
  organization_id: string
  membership_tier_id?: string | null
  payment_status?: string | null
  joined_at?: Date | string | null
  role?: string | null
}

export type user_organizationsUpdateWithoutUsersInput = {
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  membership_tiers?: Prisma.membership_tiersUpdateOneWithoutUser_organizationsNestedInput
  organizations?: Prisma.organizationsUpdateOneRequiredWithoutUser_organizationsNestedInput
}

export type user_organizationsUncheckedUpdateWithoutUsersInput = {
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  membership_tier_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type user_organizationsUncheckedUpdateManyWithoutUsersInput = {
  organization_id?: Prisma.StringFieldUpdateOperationsInput | string
  membership_tier_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  joined_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type user_organizationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  organization_id?: boolean
  membership_tier_id?: boolean
  payment_status?: boolean
  joined_at?: boolean
  role?: boolean
  membership_tiers?: boolean | Prisma.user_organizations$membership_tiersArgs<ExtArgs>
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_organizations"]>

export type user_organizationsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  organization_id?: boolean
  membership_tier_id?: boolean
  payment_status?: boolean
  joined_at?: boolean
  role?: boolean
  membership_tiers?: boolean | Prisma.user_organizations$membership_tiersArgs<ExtArgs>
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_organizations"]>

export type user_organizationsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  organization_id?: boolean
  membership_tier_id?: boolean
  payment_status?: boolean
  joined_at?: boolean
  role?: boolean
  membership_tiers?: boolean | Prisma.user_organizations$membership_tiersArgs<ExtArgs>
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_organizations"]>

export type user_organizationsSelectScalar = {
  user_id?: boolean
  organization_id?: boolean
  membership_tier_id?: boolean
  payment_status?: boolean
  joined_at?: boolean
  role?: boolean
}

export type user_organizationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_id" | "organization_id" | "membership_tier_id" | "payment_status" | "joined_at" | "role", ExtArgs["result"]["user_organizations"]>
export type user_organizationsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  membership_tiers?: boolean | Prisma.user_organizations$membership_tiersArgs<ExtArgs>
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type user_organizationsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  membership_tiers?: boolean | Prisma.user_organizations$membership_tiersArgs<ExtArgs>
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type user_organizationsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  membership_tiers?: boolean | Prisma.user_organizations$membership_tiersArgs<ExtArgs>
  organizations?: boolean | Prisma.organizationsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $user_organizationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "user_organizations"
  objects: {
    membership_tiers: Prisma.$membership_tiersPayload<ExtArgs> | null
    organizations: Prisma.$organizationsPayload<ExtArgs>
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_id: number
    organization_id: string
    membership_tier_id: string | null
    payment_status: string | null
    joined_at: Date | null
    role: string | null
  }, ExtArgs["result"]["user_organizations"]>
  composites: {}
}

export type user_organizationsGetPayload<S extends boolean | null | undefined | user_organizationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload, S>

export type user_organizationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<user_organizationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: User_organizationsCountAggregateInputType | true
  }

export interface user_organizationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['user_organizations'], meta: { name: 'user_organizations' } }
  /**
   * Find zero or one User_organizations that matches the filter.
   * @param {user_organizationsFindUniqueArgs} args - Arguments to find a User_organizations
   * @example
   * // Get one User_organizations
   * const user_organizations = await prisma.user_organizations.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends user_organizationsFindUniqueArgs>(args: Prisma.SelectSubset<T, user_organizationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__user_organizationsClient<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User_organizations that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {user_organizationsFindUniqueOrThrowArgs} args - Arguments to find a User_organizations
   * @example
   * // Get one User_organizations
   * const user_organizations = await prisma.user_organizations.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends user_organizationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, user_organizationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_organizationsClient<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_organizations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_organizationsFindFirstArgs} args - Arguments to find a User_organizations
   * @example
   * // Get one User_organizations
   * const user_organizations = await prisma.user_organizations.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends user_organizationsFindFirstArgs>(args?: Prisma.SelectSubset<T, user_organizationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__user_organizationsClient<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_organizations that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_organizationsFindFirstOrThrowArgs} args - Arguments to find a User_organizations
   * @example
   * // Get one User_organizations
   * const user_organizations = await prisma.user_organizations.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends user_organizationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, user_organizationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_organizationsClient<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more User_organizations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_organizationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all User_organizations
   * const user_organizations = await prisma.user_organizations.findMany()
   * 
   * // Get first 10 User_organizations
   * const user_organizations = await prisma.user_organizations.findMany({ take: 10 })
   * 
   * // Only select the `user_id`
   * const user_organizationsWithUser_idOnly = await prisma.user_organizations.findMany({ select: { user_id: true } })
   * 
   */
  findMany<T extends user_organizationsFindManyArgs>(args?: Prisma.SelectSubset<T, user_organizationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User_organizations.
   * @param {user_organizationsCreateArgs} args - Arguments to create a User_organizations.
   * @example
   * // Create one User_organizations
   * const User_organizations = await prisma.user_organizations.create({
   *   data: {
   *     // ... data to create a User_organizations
   *   }
   * })
   * 
   */
  create<T extends user_organizationsCreateArgs>(args: Prisma.SelectSubset<T, user_organizationsCreateArgs<ExtArgs>>): Prisma.Prisma__user_organizationsClient<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many User_organizations.
   * @param {user_organizationsCreateManyArgs} args - Arguments to create many User_organizations.
   * @example
   * // Create many User_organizations
   * const user_organizations = await prisma.user_organizations.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends user_organizationsCreateManyArgs>(args?: Prisma.SelectSubset<T, user_organizationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many User_organizations and returns the data saved in the database.
   * @param {user_organizationsCreateManyAndReturnArgs} args - Arguments to create many User_organizations.
   * @example
   * // Create many User_organizations
   * const user_organizations = await prisma.user_organizations.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many User_organizations and only return the `user_id`
   * const user_organizationsWithUser_idOnly = await prisma.user_organizations.createManyAndReturn({
   *   select: { user_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends user_organizationsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, user_organizationsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User_organizations.
   * @param {user_organizationsDeleteArgs} args - Arguments to delete one User_organizations.
   * @example
   * // Delete one User_organizations
   * const User_organizations = await prisma.user_organizations.delete({
   *   where: {
   *     // ... filter to delete one User_organizations
   *   }
   * })
   * 
   */
  delete<T extends user_organizationsDeleteArgs>(args: Prisma.SelectSubset<T, user_organizationsDeleteArgs<ExtArgs>>): Prisma.Prisma__user_organizationsClient<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User_organizations.
   * @param {user_organizationsUpdateArgs} args - Arguments to update one User_organizations.
   * @example
   * // Update one User_organizations
   * const user_organizations = await prisma.user_organizations.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends user_organizationsUpdateArgs>(args: Prisma.SelectSubset<T, user_organizationsUpdateArgs<ExtArgs>>): Prisma.Prisma__user_organizationsClient<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more User_organizations.
   * @param {user_organizationsDeleteManyArgs} args - Arguments to filter User_organizations to delete.
   * @example
   * // Delete a few User_organizations
   * const { count } = await prisma.user_organizations.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends user_organizationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, user_organizationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_organizations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_organizationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many User_organizations
   * const user_organizations = await prisma.user_organizations.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends user_organizationsUpdateManyArgs>(args: Prisma.SelectSubset<T, user_organizationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_organizations and returns the data updated in the database.
   * @param {user_organizationsUpdateManyAndReturnArgs} args - Arguments to update many User_organizations.
   * @example
   * // Update many User_organizations
   * const user_organizations = await prisma.user_organizations.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more User_organizations and only return the `user_id`
   * const user_organizationsWithUser_idOnly = await prisma.user_organizations.updateManyAndReturn({
   *   select: { user_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends user_organizationsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, user_organizationsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User_organizations.
   * @param {user_organizationsUpsertArgs} args - Arguments to update or create a User_organizations.
   * @example
   * // Update or create a User_organizations
   * const user_organizations = await prisma.user_organizations.upsert({
   *   create: {
   *     // ... data to create a User_organizations
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User_organizations we want to update
   *   }
   * })
   */
  upsert<T extends user_organizationsUpsertArgs>(args: Prisma.SelectSubset<T, user_organizationsUpsertArgs<ExtArgs>>): Prisma.Prisma__user_organizationsClient<runtime.Types.Result.GetResult<Prisma.$user_organizationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of User_organizations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_organizationsCountArgs} args - Arguments to filter User_organizations to count.
   * @example
   * // Count the number of User_organizations
   * const count = await prisma.user_organizations.count({
   *   where: {
   *     // ... the filter for the User_organizations we want to count
   *   }
   * })
  **/
  count<T extends user_organizationsCountArgs>(
    args?: Prisma.Subset<T, user_organizationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], User_organizationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User_organizations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {User_organizationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends User_organizationsAggregateArgs>(args: Prisma.Subset<T, User_organizationsAggregateArgs>): Prisma.PrismaPromise<GetUser_organizationsAggregateType<T>>

  /**
   * Group by User_organizations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_organizationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends user_organizationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: user_organizationsGroupByArgs['orderBy'] }
      : { orderBy?: user_organizationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, user_organizationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUser_organizationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the user_organizations model
 */
readonly fields: user_organizationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for user_organizations.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__user_organizationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  membership_tiers<T extends Prisma.user_organizations$membership_tiersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.user_organizations$membership_tiersArgs<ExtArgs>>): Prisma.Prisma__membership_tiersClient<runtime.Types.Result.GetResult<Prisma.$membership_tiersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  organizations<T extends Prisma.organizationsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.organizationsDefaultArgs<ExtArgs>>): Prisma.Prisma__organizationsClient<runtime.Types.Result.GetResult<Prisma.$organizationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the user_organizations model
 */
export interface user_organizationsFieldRefs {
  readonly user_id: Prisma.FieldRef<"user_organizations", 'Int'>
  readonly organization_id: Prisma.FieldRef<"user_organizations", 'String'>
  readonly membership_tier_id: Prisma.FieldRef<"user_organizations", 'String'>
  readonly payment_status: Prisma.FieldRef<"user_organizations", 'String'>
  readonly joined_at: Prisma.FieldRef<"user_organizations", 'DateTime'>
  readonly role: Prisma.FieldRef<"user_organizations", 'String'>
}
    

// Custom InputTypes
/**
 * user_organizations findUnique
 */
export type user_organizationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * Filter, which user_organizations to fetch.
   */
  where: Prisma.user_organizationsWhereUniqueInput
}

/**
 * user_organizations findUniqueOrThrow
 */
export type user_organizationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * Filter, which user_organizations to fetch.
   */
  where: Prisma.user_organizationsWhereUniqueInput
}

/**
 * user_organizations findFirst
 */
export type user_organizationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * Filter, which user_organizations to fetch.
   */
  where?: Prisma.user_organizationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_organizations to fetch.
   */
  orderBy?: Prisma.user_organizationsOrderByWithRelationInput | Prisma.user_organizationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_organizations.
   */
  cursor?: Prisma.user_organizationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_organizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_organizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_organizations.
   */
  distinct?: Prisma.User_organizationsScalarFieldEnum | Prisma.User_organizationsScalarFieldEnum[]
}

/**
 * user_organizations findFirstOrThrow
 */
export type user_organizationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * Filter, which user_organizations to fetch.
   */
  where?: Prisma.user_organizationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_organizations to fetch.
   */
  orderBy?: Prisma.user_organizationsOrderByWithRelationInput | Prisma.user_organizationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_organizations.
   */
  cursor?: Prisma.user_organizationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_organizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_organizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_organizations.
   */
  distinct?: Prisma.User_organizationsScalarFieldEnum | Prisma.User_organizationsScalarFieldEnum[]
}

/**
 * user_organizations findMany
 */
export type user_organizationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * Filter, which user_organizations to fetch.
   */
  where?: Prisma.user_organizationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_organizations to fetch.
   */
  orderBy?: Prisma.user_organizationsOrderByWithRelationInput | Prisma.user_organizationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing user_organizations.
   */
  cursor?: Prisma.user_organizationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_organizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_organizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_organizations.
   */
  distinct?: Prisma.User_organizationsScalarFieldEnum | Prisma.User_organizationsScalarFieldEnum[]
}

/**
 * user_organizations create
 */
export type user_organizationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * The data needed to create a user_organizations.
   */
  data: Prisma.XOR<Prisma.user_organizationsCreateInput, Prisma.user_organizationsUncheckedCreateInput>
}

/**
 * user_organizations createMany
 */
export type user_organizationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many user_organizations.
   */
  data: Prisma.user_organizationsCreateManyInput | Prisma.user_organizationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * user_organizations createManyAndReturn
 */
export type user_organizationsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * The data used to create many user_organizations.
   */
  data: Prisma.user_organizationsCreateManyInput | Prisma.user_organizationsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * user_organizations update
 */
export type user_organizationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * The data needed to update a user_organizations.
   */
  data: Prisma.XOR<Prisma.user_organizationsUpdateInput, Prisma.user_organizationsUncheckedUpdateInput>
  /**
   * Choose, which user_organizations to update.
   */
  where: Prisma.user_organizationsWhereUniqueInput
}

/**
 * user_organizations updateMany
 */
export type user_organizationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update user_organizations.
   */
  data: Prisma.XOR<Prisma.user_organizationsUpdateManyMutationInput, Prisma.user_organizationsUncheckedUpdateManyInput>
  /**
   * Filter which user_organizations to update
   */
  where?: Prisma.user_organizationsWhereInput
  /**
   * Limit how many user_organizations to update.
   */
  limit?: number
}

/**
 * user_organizations updateManyAndReturn
 */
export type user_organizationsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * The data used to update user_organizations.
   */
  data: Prisma.XOR<Prisma.user_organizationsUpdateManyMutationInput, Prisma.user_organizationsUncheckedUpdateManyInput>
  /**
   * Filter which user_organizations to update
   */
  where?: Prisma.user_organizationsWhereInput
  /**
   * Limit how many user_organizations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * user_organizations upsert
 */
export type user_organizationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * The filter to search for the user_organizations to update in case it exists.
   */
  where: Prisma.user_organizationsWhereUniqueInput
  /**
   * In case the user_organizations found by the `where` argument doesn't exist, create a new user_organizations with this data.
   */
  create: Prisma.XOR<Prisma.user_organizationsCreateInput, Prisma.user_organizationsUncheckedCreateInput>
  /**
   * In case the user_organizations was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.user_organizationsUpdateInput, Prisma.user_organizationsUncheckedUpdateInput>
}

/**
 * user_organizations delete
 */
export type user_organizationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
  /**
   * Filter which user_organizations to delete.
   */
  where: Prisma.user_organizationsWhereUniqueInput
}

/**
 * user_organizations deleteMany
 */
export type user_organizationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_organizations to delete
   */
  where?: Prisma.user_organizationsWhereInput
  /**
   * Limit how many user_organizations to delete.
   */
  limit?: number
}

/**
 * user_organizations.membership_tiers
 */
export type user_organizations$membership_tiersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the membership_tiers
   */
  select?: Prisma.membership_tiersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the membership_tiers
   */
  omit?: Prisma.membership_tiersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membership_tiersInclude<ExtArgs> | null
  where?: Prisma.membership_tiersWhereInput
}

/**
 * user_organizations without action
 */
export type user_organizationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_organizations
   */
  select?: Prisma.user_organizationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_organizations
   */
  omit?: Prisma.user_organizationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_organizationsInclude<ExtArgs> | null
}
