
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ai_interactions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ai_interactions
 * 
 */
export type ai_interactionsModel = runtime.Types.Result.DefaultSelection<Prisma.$ai_interactionsPayload>

export type AggregateAi_interactions = {
  _count: Ai_interactionsCountAggregateOutputType | null
  _avg: Ai_interactionsAvgAggregateOutputType | null
  _sum: Ai_interactionsSumAggregateOutputType | null
  _min: Ai_interactionsMinAggregateOutputType | null
  _max: Ai_interactionsMaxAggregateOutputType | null
}

export type Ai_interactionsAvgAggregateOutputType = {
  confidence_score: runtime.Decimal | null
}

export type Ai_interactionsSumAggregateOutputType = {
  confidence_score: runtime.Decimal | null
}

export type Ai_interactionsMinAggregateOutputType = {
  interaction_id: string | null
  case_id: string | null
  episode_id: string | null
  user_query: string | null
  jana_response: string | null
  language: string | null
  confidence_score: runtime.Decimal | null
  created_at: Date | null
}

export type Ai_interactionsMaxAggregateOutputType = {
  interaction_id: string | null
  case_id: string | null
  episode_id: string | null
  user_query: string | null
  jana_response: string | null
  language: string | null
  confidence_score: runtime.Decimal | null
  created_at: Date | null
}

export type Ai_interactionsCountAggregateOutputType = {
  interaction_id: number
  case_id: number
  episode_id: number
  user_query: number
  jana_response: number
  language: number
  confidence_score: number
  created_at: number
  _all: number
}


export type Ai_interactionsAvgAggregateInputType = {
  confidence_score?: true
}

export type Ai_interactionsSumAggregateInputType = {
  confidence_score?: true
}

export type Ai_interactionsMinAggregateInputType = {
  interaction_id?: true
  case_id?: true
  episode_id?: true
  user_query?: true
  jana_response?: true
  language?: true
  confidence_score?: true
  created_at?: true
}

export type Ai_interactionsMaxAggregateInputType = {
  interaction_id?: true
  case_id?: true
  episode_id?: true
  user_query?: true
  jana_response?: true
  language?: true
  confidence_score?: true
  created_at?: true
}

export type Ai_interactionsCountAggregateInputType = {
  interaction_id?: true
  case_id?: true
  episode_id?: true
  user_query?: true
  jana_response?: true
  language?: true
  confidence_score?: true
  created_at?: true
  _all?: true
}

export type Ai_interactionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ai_interactions to aggregate.
   */
  where?: Prisma.ai_interactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ai_interactions to fetch.
   */
  orderBy?: Prisma.ai_interactionsOrderByWithRelationInput | Prisma.ai_interactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ai_interactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ai_interactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ai_interactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ai_interactions
  **/
  _count?: true | Ai_interactionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Ai_interactionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Ai_interactionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Ai_interactionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Ai_interactionsMaxAggregateInputType
}

export type GetAi_interactionsAggregateType<T extends Ai_interactionsAggregateArgs> = {
      [P in keyof T & keyof AggregateAi_interactions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAi_interactions[P]>
    : Prisma.GetScalarType<T[P], AggregateAi_interactions[P]>
}




export type ai_interactionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ai_interactionsWhereInput
  orderBy?: Prisma.ai_interactionsOrderByWithAggregationInput | Prisma.ai_interactionsOrderByWithAggregationInput[]
  by: Prisma.Ai_interactionsScalarFieldEnum[] | Prisma.Ai_interactionsScalarFieldEnum
  having?: Prisma.ai_interactionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Ai_interactionsCountAggregateInputType | true
  _avg?: Ai_interactionsAvgAggregateInputType
  _sum?: Ai_interactionsSumAggregateInputType
  _min?: Ai_interactionsMinAggregateInputType
  _max?: Ai_interactionsMaxAggregateInputType
}

export type Ai_interactionsGroupByOutputType = {
  interaction_id: string
  case_id: string | null
  episode_id: string | null
  user_query: string
  jana_response: string
  language: string | null
  confidence_score: runtime.Decimal | null
  created_at: Date | null
  _count: Ai_interactionsCountAggregateOutputType | null
  _avg: Ai_interactionsAvgAggregateOutputType | null
  _sum: Ai_interactionsSumAggregateOutputType | null
  _min: Ai_interactionsMinAggregateOutputType | null
  _max: Ai_interactionsMaxAggregateOutputType | null
}

type GetAi_interactionsGroupByPayload<T extends ai_interactionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Ai_interactionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Ai_interactionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Ai_interactionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Ai_interactionsGroupByOutputType[P]>
      }
    >
  >



export type ai_interactionsWhereInput = {
  AND?: Prisma.ai_interactionsWhereInput | Prisma.ai_interactionsWhereInput[]
  OR?: Prisma.ai_interactionsWhereInput[]
  NOT?: Prisma.ai_interactionsWhereInput | Prisma.ai_interactionsWhereInput[]
  interaction_id?: Prisma.UuidFilter<"ai_interactions"> | string
  case_id?: Prisma.UuidNullableFilter<"ai_interactions"> | string | null
  episode_id?: Prisma.UuidNullableFilter<"ai_interactions"> | string | null
  user_query?: Prisma.StringFilter<"ai_interactions"> | string
  jana_response?: Prisma.StringFilter<"ai_interactions"> | string
  language?: Prisma.StringNullableFilter<"ai_interactions"> | string | null
  confidence_score?: Prisma.DecimalNullableFilter<"ai_interactions"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.DateTimeNullableFilter<"ai_interactions"> | Date | string | null
  ai_escalations?: Prisma.Ai_escalationsListRelationFilter
  cases?: Prisma.XOR<Prisma.CasesNullableScalarRelationFilter, Prisma.casesWhereInput> | null
  episodes?: Prisma.XOR<Prisma.EpisodesNullableScalarRelationFilter, Prisma.episodesWhereInput> | null
}

export type ai_interactionsOrderByWithRelationInput = {
  interaction_id?: Prisma.SortOrder
  case_id?: Prisma.SortOrderInput | Prisma.SortOrder
  episode_id?: Prisma.SortOrderInput | Prisma.SortOrder
  user_query?: Prisma.SortOrder
  jana_response?: Prisma.SortOrder
  language?: Prisma.SortOrderInput | Prisma.SortOrder
  confidence_score?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  ai_escalations?: Prisma.ai_escalationsOrderByRelationAggregateInput
  cases?: Prisma.casesOrderByWithRelationInput
  episodes?: Prisma.episodesOrderByWithRelationInput
}

export type ai_interactionsWhereUniqueInput = Prisma.AtLeast<{
  interaction_id?: string
  AND?: Prisma.ai_interactionsWhereInput | Prisma.ai_interactionsWhereInput[]
  OR?: Prisma.ai_interactionsWhereInput[]
  NOT?: Prisma.ai_interactionsWhereInput | Prisma.ai_interactionsWhereInput[]
  case_id?: Prisma.UuidNullableFilter<"ai_interactions"> | string | null
  episode_id?: Prisma.UuidNullableFilter<"ai_interactions"> | string | null
  user_query?: Prisma.StringFilter<"ai_interactions"> | string
  jana_response?: Prisma.StringFilter<"ai_interactions"> | string
  language?: Prisma.StringNullableFilter<"ai_interactions"> | string | null
  confidence_score?: Prisma.DecimalNullableFilter<"ai_interactions"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.DateTimeNullableFilter<"ai_interactions"> | Date | string | null
  ai_escalations?: Prisma.Ai_escalationsListRelationFilter
  cases?: Prisma.XOR<Prisma.CasesNullableScalarRelationFilter, Prisma.casesWhereInput> | null
  episodes?: Prisma.XOR<Prisma.EpisodesNullableScalarRelationFilter, Prisma.episodesWhereInput> | null
}, "interaction_id">

export type ai_interactionsOrderByWithAggregationInput = {
  interaction_id?: Prisma.SortOrder
  case_id?: Prisma.SortOrderInput | Prisma.SortOrder
  episode_id?: Prisma.SortOrderInput | Prisma.SortOrder
  user_query?: Prisma.SortOrder
  jana_response?: Prisma.SortOrder
  language?: Prisma.SortOrderInput | Prisma.SortOrder
  confidence_score?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ai_interactionsCountOrderByAggregateInput
  _avg?: Prisma.ai_interactionsAvgOrderByAggregateInput
  _max?: Prisma.ai_interactionsMaxOrderByAggregateInput
  _min?: Prisma.ai_interactionsMinOrderByAggregateInput
  _sum?: Prisma.ai_interactionsSumOrderByAggregateInput
}

export type ai_interactionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ai_interactionsScalarWhereWithAggregatesInput | Prisma.ai_interactionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ai_interactionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ai_interactionsScalarWhereWithAggregatesInput | Prisma.ai_interactionsScalarWhereWithAggregatesInput[]
  interaction_id?: Prisma.UuidWithAggregatesFilter<"ai_interactions"> | string
  case_id?: Prisma.UuidNullableWithAggregatesFilter<"ai_interactions"> | string | null
  episode_id?: Prisma.UuidNullableWithAggregatesFilter<"ai_interactions"> | string | null
  user_query?: Prisma.StringWithAggregatesFilter<"ai_interactions"> | string
  jana_response?: Prisma.StringWithAggregatesFilter<"ai_interactions"> | string
  language?: Prisma.StringNullableWithAggregatesFilter<"ai_interactions"> | string | null
  confidence_score?: Prisma.DecimalNullableWithAggregatesFilter<"ai_interactions"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"ai_interactions"> | Date | string | null
}

export type ai_interactionsCreateInput = {
  interaction_id?: string
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
  ai_escalations?: Prisma.ai_escalationsCreateNestedManyWithoutAi_interactionsInput
  cases?: Prisma.casesCreateNestedOneWithoutAi_interactionsInput
  episodes?: Prisma.episodesCreateNestedOneWithoutAi_interactionsInput
}

export type ai_interactionsUncheckedCreateInput = {
  interaction_id?: string
  case_id?: string | null
  episode_id?: string | null
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
  ai_escalations?: Prisma.ai_escalationsUncheckedCreateNestedManyWithoutAi_interactionsInput
}

export type ai_interactionsUpdateInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ai_escalations?: Prisma.ai_escalationsUpdateManyWithoutAi_interactionsNestedInput
  cases?: Prisma.casesUpdateOneWithoutAi_interactionsNestedInput
  episodes?: Prisma.episodesUpdateOneWithoutAi_interactionsNestedInput
}

export type ai_interactionsUncheckedUpdateInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  case_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episode_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ai_escalations?: Prisma.ai_escalationsUncheckedUpdateManyWithoutAi_interactionsNestedInput
}

export type ai_interactionsCreateManyInput = {
  interaction_id?: string
  case_id?: string | null
  episode_id?: string | null
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
}

export type ai_interactionsUpdateManyMutationInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ai_interactionsUncheckedUpdateManyInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  case_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episode_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Ai_interactionsScalarRelationFilter = {
  is?: Prisma.ai_interactionsWhereInput
  isNot?: Prisma.ai_interactionsWhereInput
}

export type ai_interactionsCountOrderByAggregateInput = {
  interaction_id?: Prisma.SortOrder
  case_id?: Prisma.SortOrder
  episode_id?: Prisma.SortOrder
  user_query?: Prisma.SortOrder
  jana_response?: Prisma.SortOrder
  language?: Prisma.SortOrder
  confidence_score?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ai_interactionsAvgOrderByAggregateInput = {
  confidence_score?: Prisma.SortOrder
}

export type ai_interactionsMaxOrderByAggregateInput = {
  interaction_id?: Prisma.SortOrder
  case_id?: Prisma.SortOrder
  episode_id?: Prisma.SortOrder
  user_query?: Prisma.SortOrder
  jana_response?: Prisma.SortOrder
  language?: Prisma.SortOrder
  confidence_score?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ai_interactionsMinOrderByAggregateInput = {
  interaction_id?: Prisma.SortOrder
  case_id?: Prisma.SortOrder
  episode_id?: Prisma.SortOrder
  user_query?: Prisma.SortOrder
  jana_response?: Prisma.SortOrder
  language?: Prisma.SortOrder
  confidence_score?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ai_interactionsSumOrderByAggregateInput = {
  confidence_score?: Prisma.SortOrder
}

export type Ai_interactionsListRelationFilter = {
  every?: Prisma.ai_interactionsWhereInput
  some?: Prisma.ai_interactionsWhereInput
  none?: Prisma.ai_interactionsWhereInput
}

export type ai_interactionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ai_interactionsCreateNestedOneWithoutAi_escalationsInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutAi_escalationsInput, Prisma.ai_interactionsUncheckedCreateWithoutAi_escalationsInput>
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutAi_escalationsInput
  connect?: Prisma.ai_interactionsWhereUniqueInput
}

export type ai_interactionsUpdateOneRequiredWithoutAi_escalationsNestedInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutAi_escalationsInput, Prisma.ai_interactionsUncheckedCreateWithoutAi_escalationsInput>
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutAi_escalationsInput
  upsert?: Prisma.ai_interactionsUpsertWithoutAi_escalationsInput
  connect?: Prisma.ai_interactionsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ai_interactionsUpdateToOneWithWhereWithoutAi_escalationsInput, Prisma.ai_interactionsUpdateWithoutAi_escalationsInput>, Prisma.ai_interactionsUncheckedUpdateWithoutAi_escalationsInput>
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ai_interactionsCreateNestedManyWithoutCasesInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutCasesInput, Prisma.ai_interactionsUncheckedCreateWithoutCasesInput> | Prisma.ai_interactionsCreateWithoutCasesInput[] | Prisma.ai_interactionsUncheckedCreateWithoutCasesInput[]
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutCasesInput | Prisma.ai_interactionsCreateOrConnectWithoutCasesInput[]
  createMany?: Prisma.ai_interactionsCreateManyCasesInputEnvelope
  connect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
}

export type ai_interactionsUncheckedCreateNestedManyWithoutCasesInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutCasesInput, Prisma.ai_interactionsUncheckedCreateWithoutCasesInput> | Prisma.ai_interactionsCreateWithoutCasesInput[] | Prisma.ai_interactionsUncheckedCreateWithoutCasesInput[]
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutCasesInput | Prisma.ai_interactionsCreateOrConnectWithoutCasesInput[]
  createMany?: Prisma.ai_interactionsCreateManyCasesInputEnvelope
  connect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
}

export type ai_interactionsUpdateManyWithoutCasesNestedInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutCasesInput, Prisma.ai_interactionsUncheckedCreateWithoutCasesInput> | Prisma.ai_interactionsCreateWithoutCasesInput[] | Prisma.ai_interactionsUncheckedCreateWithoutCasesInput[]
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutCasesInput | Prisma.ai_interactionsCreateOrConnectWithoutCasesInput[]
  upsert?: Prisma.ai_interactionsUpsertWithWhereUniqueWithoutCasesInput | Prisma.ai_interactionsUpsertWithWhereUniqueWithoutCasesInput[]
  createMany?: Prisma.ai_interactionsCreateManyCasesInputEnvelope
  set?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  disconnect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  delete?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  connect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  update?: Prisma.ai_interactionsUpdateWithWhereUniqueWithoutCasesInput | Prisma.ai_interactionsUpdateWithWhereUniqueWithoutCasesInput[]
  updateMany?: Prisma.ai_interactionsUpdateManyWithWhereWithoutCasesInput | Prisma.ai_interactionsUpdateManyWithWhereWithoutCasesInput[]
  deleteMany?: Prisma.ai_interactionsScalarWhereInput | Prisma.ai_interactionsScalarWhereInput[]
}

export type ai_interactionsUncheckedUpdateManyWithoutCasesNestedInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutCasesInput, Prisma.ai_interactionsUncheckedCreateWithoutCasesInput> | Prisma.ai_interactionsCreateWithoutCasesInput[] | Prisma.ai_interactionsUncheckedCreateWithoutCasesInput[]
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutCasesInput | Prisma.ai_interactionsCreateOrConnectWithoutCasesInput[]
  upsert?: Prisma.ai_interactionsUpsertWithWhereUniqueWithoutCasesInput | Prisma.ai_interactionsUpsertWithWhereUniqueWithoutCasesInput[]
  createMany?: Prisma.ai_interactionsCreateManyCasesInputEnvelope
  set?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  disconnect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  delete?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  connect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  update?: Prisma.ai_interactionsUpdateWithWhereUniqueWithoutCasesInput | Prisma.ai_interactionsUpdateWithWhereUniqueWithoutCasesInput[]
  updateMany?: Prisma.ai_interactionsUpdateManyWithWhereWithoutCasesInput | Prisma.ai_interactionsUpdateManyWithWhereWithoutCasesInput[]
  deleteMany?: Prisma.ai_interactionsScalarWhereInput | Prisma.ai_interactionsScalarWhereInput[]
}

export type ai_interactionsCreateNestedManyWithoutEpisodesInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutEpisodesInput, Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput> | Prisma.ai_interactionsCreateWithoutEpisodesInput[] | Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput[]
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutEpisodesInput | Prisma.ai_interactionsCreateOrConnectWithoutEpisodesInput[]
  createMany?: Prisma.ai_interactionsCreateManyEpisodesInputEnvelope
  connect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
}

export type ai_interactionsUncheckedCreateNestedManyWithoutEpisodesInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutEpisodesInput, Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput> | Prisma.ai_interactionsCreateWithoutEpisodesInput[] | Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput[]
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutEpisodesInput | Prisma.ai_interactionsCreateOrConnectWithoutEpisodesInput[]
  createMany?: Prisma.ai_interactionsCreateManyEpisodesInputEnvelope
  connect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
}

export type ai_interactionsUpdateManyWithoutEpisodesNestedInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutEpisodesInput, Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput> | Prisma.ai_interactionsCreateWithoutEpisodesInput[] | Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput[]
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutEpisodesInput | Prisma.ai_interactionsCreateOrConnectWithoutEpisodesInput[]
  upsert?: Prisma.ai_interactionsUpsertWithWhereUniqueWithoutEpisodesInput | Prisma.ai_interactionsUpsertWithWhereUniqueWithoutEpisodesInput[]
  createMany?: Prisma.ai_interactionsCreateManyEpisodesInputEnvelope
  set?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  disconnect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  delete?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  connect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  update?: Prisma.ai_interactionsUpdateWithWhereUniqueWithoutEpisodesInput | Prisma.ai_interactionsUpdateWithWhereUniqueWithoutEpisodesInput[]
  updateMany?: Prisma.ai_interactionsUpdateManyWithWhereWithoutEpisodesInput | Prisma.ai_interactionsUpdateManyWithWhereWithoutEpisodesInput[]
  deleteMany?: Prisma.ai_interactionsScalarWhereInput | Prisma.ai_interactionsScalarWhereInput[]
}

export type ai_interactionsUncheckedUpdateManyWithoutEpisodesNestedInput = {
  create?: Prisma.XOR<Prisma.ai_interactionsCreateWithoutEpisodesInput, Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput> | Prisma.ai_interactionsCreateWithoutEpisodesInput[] | Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput[]
  connectOrCreate?: Prisma.ai_interactionsCreateOrConnectWithoutEpisodesInput | Prisma.ai_interactionsCreateOrConnectWithoutEpisodesInput[]
  upsert?: Prisma.ai_interactionsUpsertWithWhereUniqueWithoutEpisodesInput | Prisma.ai_interactionsUpsertWithWhereUniqueWithoutEpisodesInput[]
  createMany?: Prisma.ai_interactionsCreateManyEpisodesInputEnvelope
  set?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  disconnect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  delete?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  connect?: Prisma.ai_interactionsWhereUniqueInput | Prisma.ai_interactionsWhereUniqueInput[]
  update?: Prisma.ai_interactionsUpdateWithWhereUniqueWithoutEpisodesInput | Prisma.ai_interactionsUpdateWithWhereUniqueWithoutEpisodesInput[]
  updateMany?: Prisma.ai_interactionsUpdateManyWithWhereWithoutEpisodesInput | Prisma.ai_interactionsUpdateManyWithWhereWithoutEpisodesInput[]
  deleteMany?: Prisma.ai_interactionsScalarWhereInput | Prisma.ai_interactionsScalarWhereInput[]
}

export type ai_interactionsCreateWithoutAi_escalationsInput = {
  interaction_id?: string
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
  cases?: Prisma.casesCreateNestedOneWithoutAi_interactionsInput
  episodes?: Prisma.episodesCreateNestedOneWithoutAi_interactionsInput
}

export type ai_interactionsUncheckedCreateWithoutAi_escalationsInput = {
  interaction_id?: string
  case_id?: string | null
  episode_id?: string | null
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
}

export type ai_interactionsCreateOrConnectWithoutAi_escalationsInput = {
  where: Prisma.ai_interactionsWhereUniqueInput
  create: Prisma.XOR<Prisma.ai_interactionsCreateWithoutAi_escalationsInput, Prisma.ai_interactionsUncheckedCreateWithoutAi_escalationsInput>
}

export type ai_interactionsUpsertWithoutAi_escalationsInput = {
  update: Prisma.XOR<Prisma.ai_interactionsUpdateWithoutAi_escalationsInput, Prisma.ai_interactionsUncheckedUpdateWithoutAi_escalationsInput>
  create: Prisma.XOR<Prisma.ai_interactionsCreateWithoutAi_escalationsInput, Prisma.ai_interactionsUncheckedCreateWithoutAi_escalationsInput>
  where?: Prisma.ai_interactionsWhereInput
}

export type ai_interactionsUpdateToOneWithWhereWithoutAi_escalationsInput = {
  where?: Prisma.ai_interactionsWhereInput
  data: Prisma.XOR<Prisma.ai_interactionsUpdateWithoutAi_escalationsInput, Prisma.ai_interactionsUncheckedUpdateWithoutAi_escalationsInput>
}

export type ai_interactionsUpdateWithoutAi_escalationsInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cases?: Prisma.casesUpdateOneWithoutAi_interactionsNestedInput
  episodes?: Prisma.episodesUpdateOneWithoutAi_interactionsNestedInput
}

export type ai_interactionsUncheckedUpdateWithoutAi_escalationsInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  case_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episode_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ai_interactionsCreateWithoutCasesInput = {
  interaction_id?: string
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
  ai_escalations?: Prisma.ai_escalationsCreateNestedManyWithoutAi_interactionsInput
  episodes?: Prisma.episodesCreateNestedOneWithoutAi_interactionsInput
}

export type ai_interactionsUncheckedCreateWithoutCasesInput = {
  interaction_id?: string
  episode_id?: string | null
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
  ai_escalations?: Prisma.ai_escalationsUncheckedCreateNestedManyWithoutAi_interactionsInput
}

export type ai_interactionsCreateOrConnectWithoutCasesInput = {
  where: Prisma.ai_interactionsWhereUniqueInput
  create: Prisma.XOR<Prisma.ai_interactionsCreateWithoutCasesInput, Prisma.ai_interactionsUncheckedCreateWithoutCasesInput>
}

export type ai_interactionsCreateManyCasesInputEnvelope = {
  data: Prisma.ai_interactionsCreateManyCasesInput | Prisma.ai_interactionsCreateManyCasesInput[]
  skipDuplicates?: boolean
}

export type ai_interactionsUpsertWithWhereUniqueWithoutCasesInput = {
  where: Prisma.ai_interactionsWhereUniqueInput
  update: Prisma.XOR<Prisma.ai_interactionsUpdateWithoutCasesInput, Prisma.ai_interactionsUncheckedUpdateWithoutCasesInput>
  create: Prisma.XOR<Prisma.ai_interactionsCreateWithoutCasesInput, Prisma.ai_interactionsUncheckedCreateWithoutCasesInput>
}

export type ai_interactionsUpdateWithWhereUniqueWithoutCasesInput = {
  where: Prisma.ai_interactionsWhereUniqueInput
  data: Prisma.XOR<Prisma.ai_interactionsUpdateWithoutCasesInput, Prisma.ai_interactionsUncheckedUpdateWithoutCasesInput>
}

export type ai_interactionsUpdateManyWithWhereWithoutCasesInput = {
  where: Prisma.ai_interactionsScalarWhereInput
  data: Prisma.XOR<Prisma.ai_interactionsUpdateManyMutationInput, Prisma.ai_interactionsUncheckedUpdateManyWithoutCasesInput>
}

export type ai_interactionsScalarWhereInput = {
  AND?: Prisma.ai_interactionsScalarWhereInput | Prisma.ai_interactionsScalarWhereInput[]
  OR?: Prisma.ai_interactionsScalarWhereInput[]
  NOT?: Prisma.ai_interactionsScalarWhereInput | Prisma.ai_interactionsScalarWhereInput[]
  interaction_id?: Prisma.UuidFilter<"ai_interactions"> | string
  case_id?: Prisma.UuidNullableFilter<"ai_interactions"> | string | null
  episode_id?: Prisma.UuidNullableFilter<"ai_interactions"> | string | null
  user_query?: Prisma.StringFilter<"ai_interactions"> | string
  jana_response?: Prisma.StringFilter<"ai_interactions"> | string
  language?: Prisma.StringNullableFilter<"ai_interactions"> | string | null
  confidence_score?: Prisma.DecimalNullableFilter<"ai_interactions"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.DateTimeNullableFilter<"ai_interactions"> | Date | string | null
}

export type ai_interactionsCreateWithoutEpisodesInput = {
  interaction_id?: string
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
  ai_escalations?: Prisma.ai_escalationsCreateNestedManyWithoutAi_interactionsInput
  cases?: Prisma.casesCreateNestedOneWithoutAi_interactionsInput
}

export type ai_interactionsUncheckedCreateWithoutEpisodesInput = {
  interaction_id?: string
  case_id?: string | null
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
  ai_escalations?: Prisma.ai_escalationsUncheckedCreateNestedManyWithoutAi_interactionsInput
}

export type ai_interactionsCreateOrConnectWithoutEpisodesInput = {
  where: Prisma.ai_interactionsWhereUniqueInput
  create: Prisma.XOR<Prisma.ai_interactionsCreateWithoutEpisodesInput, Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput>
}

export type ai_interactionsCreateManyEpisodesInputEnvelope = {
  data: Prisma.ai_interactionsCreateManyEpisodesInput | Prisma.ai_interactionsCreateManyEpisodesInput[]
  skipDuplicates?: boolean
}

export type ai_interactionsUpsertWithWhereUniqueWithoutEpisodesInput = {
  where: Prisma.ai_interactionsWhereUniqueInput
  update: Prisma.XOR<Prisma.ai_interactionsUpdateWithoutEpisodesInput, Prisma.ai_interactionsUncheckedUpdateWithoutEpisodesInput>
  create: Prisma.XOR<Prisma.ai_interactionsCreateWithoutEpisodesInput, Prisma.ai_interactionsUncheckedCreateWithoutEpisodesInput>
}

export type ai_interactionsUpdateWithWhereUniqueWithoutEpisodesInput = {
  where: Prisma.ai_interactionsWhereUniqueInput
  data: Prisma.XOR<Prisma.ai_interactionsUpdateWithoutEpisodesInput, Prisma.ai_interactionsUncheckedUpdateWithoutEpisodesInput>
}

export type ai_interactionsUpdateManyWithWhereWithoutEpisodesInput = {
  where: Prisma.ai_interactionsScalarWhereInput
  data: Prisma.XOR<Prisma.ai_interactionsUpdateManyMutationInput, Prisma.ai_interactionsUncheckedUpdateManyWithoutEpisodesInput>
}

export type ai_interactionsCreateManyCasesInput = {
  interaction_id?: string
  episode_id?: string | null
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
}

export type ai_interactionsUpdateWithoutCasesInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ai_escalations?: Prisma.ai_escalationsUpdateManyWithoutAi_interactionsNestedInput
  episodes?: Prisma.episodesUpdateOneWithoutAi_interactionsNestedInput
}

export type ai_interactionsUncheckedUpdateWithoutCasesInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  episode_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ai_escalations?: Prisma.ai_escalationsUncheckedUpdateManyWithoutAi_interactionsNestedInput
}

export type ai_interactionsUncheckedUpdateManyWithoutCasesInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  episode_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ai_interactionsCreateManyEpisodesInput = {
  interaction_id?: string
  case_id?: string | null
  user_query: string
  jana_response: string
  language?: string | null
  confidence_score?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Date | string | null
}

export type ai_interactionsUpdateWithoutEpisodesInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ai_escalations?: Prisma.ai_escalationsUpdateManyWithoutAi_interactionsNestedInput
  cases?: Prisma.casesUpdateOneWithoutAi_interactionsNestedInput
}

export type ai_interactionsUncheckedUpdateWithoutEpisodesInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  case_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ai_escalations?: Prisma.ai_escalationsUncheckedUpdateManyWithoutAi_interactionsNestedInput
}

export type ai_interactionsUncheckedUpdateManyWithoutEpisodesInput = {
  interaction_id?: Prisma.StringFieldUpdateOperationsInput | string
  case_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_query?: Prisma.StringFieldUpdateOperationsInput | string
  jana_response?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence_score?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type Ai_interactionsCountOutputType
 */

export type Ai_interactionsCountOutputType = {
  ai_escalations: number
}

export type Ai_interactionsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ai_escalations?: boolean | Ai_interactionsCountOutputTypeCountAi_escalationsArgs
}

/**
 * Ai_interactionsCountOutputType without action
 */
export type Ai_interactionsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ai_interactionsCountOutputType
   */
  select?: Prisma.Ai_interactionsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Ai_interactionsCountOutputType without action
 */
export type Ai_interactionsCountOutputTypeCountAi_escalationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ai_escalationsWhereInput
}


export type ai_interactionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  interaction_id?: boolean
  case_id?: boolean
  episode_id?: boolean
  user_query?: boolean
  jana_response?: boolean
  language?: boolean
  confidence_score?: boolean
  created_at?: boolean
  ai_escalations?: boolean | Prisma.ai_interactions$ai_escalationsArgs<ExtArgs>
  cases?: boolean | Prisma.ai_interactions$casesArgs<ExtArgs>
  episodes?: boolean | Prisma.ai_interactions$episodesArgs<ExtArgs>
  _count?: boolean | Prisma.Ai_interactionsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ai_interactions"]>

export type ai_interactionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  interaction_id?: boolean
  case_id?: boolean
  episode_id?: boolean
  user_query?: boolean
  jana_response?: boolean
  language?: boolean
  confidence_score?: boolean
  created_at?: boolean
  cases?: boolean | Prisma.ai_interactions$casesArgs<ExtArgs>
  episodes?: boolean | Prisma.ai_interactions$episodesArgs<ExtArgs>
}, ExtArgs["result"]["ai_interactions"]>

export type ai_interactionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  interaction_id?: boolean
  case_id?: boolean
  episode_id?: boolean
  user_query?: boolean
  jana_response?: boolean
  language?: boolean
  confidence_score?: boolean
  created_at?: boolean
  cases?: boolean | Prisma.ai_interactions$casesArgs<ExtArgs>
  episodes?: boolean | Prisma.ai_interactions$episodesArgs<ExtArgs>
}, ExtArgs["result"]["ai_interactions"]>

export type ai_interactionsSelectScalar = {
  interaction_id?: boolean
  case_id?: boolean
  episode_id?: boolean
  user_query?: boolean
  jana_response?: boolean
  language?: boolean
  confidence_score?: boolean
  created_at?: boolean
}

export type ai_interactionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"interaction_id" | "case_id" | "episode_id" | "user_query" | "jana_response" | "language" | "confidence_score" | "created_at", ExtArgs["result"]["ai_interactions"]>
export type ai_interactionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ai_escalations?: boolean | Prisma.ai_interactions$ai_escalationsArgs<ExtArgs>
  cases?: boolean | Prisma.ai_interactions$casesArgs<ExtArgs>
  episodes?: boolean | Prisma.ai_interactions$episodesArgs<ExtArgs>
  _count?: boolean | Prisma.Ai_interactionsCountOutputTypeDefaultArgs<ExtArgs>
}
export type ai_interactionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cases?: boolean | Prisma.ai_interactions$casesArgs<ExtArgs>
  episodes?: boolean | Prisma.ai_interactions$episodesArgs<ExtArgs>
}
export type ai_interactionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cases?: boolean | Prisma.ai_interactions$casesArgs<ExtArgs>
  episodes?: boolean | Prisma.ai_interactions$episodesArgs<ExtArgs>
}

export type $ai_interactionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ai_interactions"
  objects: {
    ai_escalations: Prisma.$ai_escalationsPayload<ExtArgs>[]
    cases: Prisma.$casesPayload<ExtArgs> | null
    episodes: Prisma.$episodesPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    interaction_id: string
    case_id: string | null
    episode_id: string | null
    user_query: string
    jana_response: string
    language: string | null
    confidence_score: runtime.Decimal | null
    created_at: Date | null
  }, ExtArgs["result"]["ai_interactions"]>
  composites: {}
}

export type ai_interactionsGetPayload<S extends boolean | null | undefined | ai_interactionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload, S>

export type ai_interactionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ai_interactionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Ai_interactionsCountAggregateInputType | true
  }

export interface ai_interactionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ai_interactions'], meta: { name: 'ai_interactions' } }
  /**
   * Find zero or one Ai_interactions that matches the filter.
   * @param {ai_interactionsFindUniqueArgs} args - Arguments to find a Ai_interactions
   * @example
   * // Get one Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ai_interactionsFindUniqueArgs>(args: Prisma.SelectSubset<T, ai_interactionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ai_interactionsClient<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ai_interactions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ai_interactionsFindUniqueOrThrowArgs} args - Arguments to find a Ai_interactions
   * @example
   * // Get one Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ai_interactionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ai_interactionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ai_interactionsClient<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ai_interactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ai_interactionsFindFirstArgs} args - Arguments to find a Ai_interactions
   * @example
   * // Get one Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ai_interactionsFindFirstArgs>(args?: Prisma.SelectSubset<T, ai_interactionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ai_interactionsClient<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ai_interactions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ai_interactionsFindFirstOrThrowArgs} args - Arguments to find a Ai_interactions
   * @example
   * // Get one Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ai_interactionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ai_interactionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ai_interactionsClient<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Ai_interactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ai_interactionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.findMany()
   * 
   * // Get first 10 Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.findMany({ take: 10 })
   * 
   * // Only select the `interaction_id`
   * const ai_interactionsWithInteraction_idOnly = await prisma.ai_interactions.findMany({ select: { interaction_id: true } })
   * 
   */
  findMany<T extends ai_interactionsFindManyArgs>(args?: Prisma.SelectSubset<T, ai_interactionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ai_interactions.
   * @param {ai_interactionsCreateArgs} args - Arguments to create a Ai_interactions.
   * @example
   * // Create one Ai_interactions
   * const Ai_interactions = await prisma.ai_interactions.create({
   *   data: {
   *     // ... data to create a Ai_interactions
   *   }
   * })
   * 
   */
  create<T extends ai_interactionsCreateArgs>(args: Prisma.SelectSubset<T, ai_interactionsCreateArgs<ExtArgs>>): Prisma.Prisma__ai_interactionsClient<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Ai_interactions.
   * @param {ai_interactionsCreateManyArgs} args - Arguments to create many Ai_interactions.
   * @example
   * // Create many Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ai_interactionsCreateManyArgs>(args?: Prisma.SelectSubset<T, ai_interactionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Ai_interactions and returns the data saved in the database.
   * @param {ai_interactionsCreateManyAndReturnArgs} args - Arguments to create many Ai_interactions.
   * @example
   * // Create many Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Ai_interactions and only return the `interaction_id`
   * const ai_interactionsWithInteraction_idOnly = await prisma.ai_interactions.createManyAndReturn({
   *   select: { interaction_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ai_interactionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ai_interactionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Ai_interactions.
   * @param {ai_interactionsDeleteArgs} args - Arguments to delete one Ai_interactions.
   * @example
   * // Delete one Ai_interactions
   * const Ai_interactions = await prisma.ai_interactions.delete({
   *   where: {
   *     // ... filter to delete one Ai_interactions
   *   }
   * })
   * 
   */
  delete<T extends ai_interactionsDeleteArgs>(args: Prisma.SelectSubset<T, ai_interactionsDeleteArgs<ExtArgs>>): Prisma.Prisma__ai_interactionsClient<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ai_interactions.
   * @param {ai_interactionsUpdateArgs} args - Arguments to update one Ai_interactions.
   * @example
   * // Update one Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ai_interactionsUpdateArgs>(args: Prisma.SelectSubset<T, ai_interactionsUpdateArgs<ExtArgs>>): Prisma.Prisma__ai_interactionsClient<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Ai_interactions.
   * @param {ai_interactionsDeleteManyArgs} args - Arguments to filter Ai_interactions to delete.
   * @example
   * // Delete a few Ai_interactions
   * const { count } = await prisma.ai_interactions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ai_interactionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ai_interactionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ai_interactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ai_interactionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ai_interactionsUpdateManyArgs>(args: Prisma.SelectSubset<T, ai_interactionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ai_interactions and returns the data updated in the database.
   * @param {ai_interactionsUpdateManyAndReturnArgs} args - Arguments to update many Ai_interactions.
   * @example
   * // Update many Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Ai_interactions and only return the `interaction_id`
   * const ai_interactionsWithInteraction_idOnly = await prisma.ai_interactions.updateManyAndReturn({
   *   select: { interaction_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ai_interactionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ai_interactionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Ai_interactions.
   * @param {ai_interactionsUpsertArgs} args - Arguments to update or create a Ai_interactions.
   * @example
   * // Update or create a Ai_interactions
   * const ai_interactions = await prisma.ai_interactions.upsert({
   *   create: {
   *     // ... data to create a Ai_interactions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ai_interactions we want to update
   *   }
   * })
   */
  upsert<T extends ai_interactionsUpsertArgs>(args: Prisma.SelectSubset<T, ai_interactionsUpsertArgs<ExtArgs>>): Prisma.Prisma__ai_interactionsClient<runtime.Types.Result.GetResult<Prisma.$ai_interactionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Ai_interactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ai_interactionsCountArgs} args - Arguments to filter Ai_interactions to count.
   * @example
   * // Count the number of Ai_interactions
   * const count = await prisma.ai_interactions.count({
   *   where: {
   *     // ... the filter for the Ai_interactions we want to count
   *   }
   * })
  **/
  count<T extends ai_interactionsCountArgs>(
    args?: Prisma.Subset<T, ai_interactionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Ai_interactionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ai_interactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Ai_interactionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Ai_interactionsAggregateArgs>(args: Prisma.Subset<T, Ai_interactionsAggregateArgs>): Prisma.PrismaPromise<GetAi_interactionsAggregateType<T>>

  /**
   * Group by Ai_interactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ai_interactionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ai_interactionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ai_interactionsGroupByArgs['orderBy'] }
      : { orderBy?: ai_interactionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ai_interactionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAi_interactionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ai_interactions model
 */
readonly fields: ai_interactionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ai_interactions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ai_interactionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ai_escalations<T extends Prisma.ai_interactions$ai_escalationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ai_interactions$ai_escalationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ai_escalationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  cases<T extends Prisma.ai_interactions$casesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ai_interactions$casesArgs<ExtArgs>>): Prisma.Prisma__casesClient<runtime.Types.Result.GetResult<Prisma.$casesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  episodes<T extends Prisma.ai_interactions$episodesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ai_interactions$episodesArgs<ExtArgs>>): Prisma.Prisma__episodesClient<runtime.Types.Result.GetResult<Prisma.$episodesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ai_interactions model
 */
export interface ai_interactionsFieldRefs {
  readonly interaction_id: Prisma.FieldRef<"ai_interactions", 'String'>
  readonly case_id: Prisma.FieldRef<"ai_interactions", 'String'>
  readonly episode_id: Prisma.FieldRef<"ai_interactions", 'String'>
  readonly user_query: Prisma.FieldRef<"ai_interactions", 'String'>
  readonly jana_response: Prisma.FieldRef<"ai_interactions", 'String'>
  readonly language: Prisma.FieldRef<"ai_interactions", 'String'>
  readonly confidence_score: Prisma.FieldRef<"ai_interactions", 'Decimal'>
  readonly created_at: Prisma.FieldRef<"ai_interactions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ai_interactions findUnique
 */
export type ai_interactionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * Filter, which ai_interactions to fetch.
   */
  where: Prisma.ai_interactionsWhereUniqueInput
}

/**
 * ai_interactions findUniqueOrThrow
 */
export type ai_interactionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * Filter, which ai_interactions to fetch.
   */
  where: Prisma.ai_interactionsWhereUniqueInput
}

/**
 * ai_interactions findFirst
 */
export type ai_interactionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * Filter, which ai_interactions to fetch.
   */
  where?: Prisma.ai_interactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ai_interactions to fetch.
   */
  orderBy?: Prisma.ai_interactionsOrderByWithRelationInput | Prisma.ai_interactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ai_interactions.
   */
  cursor?: Prisma.ai_interactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ai_interactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ai_interactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ai_interactions.
   */
  distinct?: Prisma.Ai_interactionsScalarFieldEnum | Prisma.Ai_interactionsScalarFieldEnum[]
}

/**
 * ai_interactions findFirstOrThrow
 */
export type ai_interactionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * Filter, which ai_interactions to fetch.
   */
  where?: Prisma.ai_interactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ai_interactions to fetch.
   */
  orderBy?: Prisma.ai_interactionsOrderByWithRelationInput | Prisma.ai_interactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ai_interactions.
   */
  cursor?: Prisma.ai_interactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ai_interactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ai_interactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ai_interactions.
   */
  distinct?: Prisma.Ai_interactionsScalarFieldEnum | Prisma.Ai_interactionsScalarFieldEnum[]
}

/**
 * ai_interactions findMany
 */
export type ai_interactionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * Filter, which ai_interactions to fetch.
   */
  where?: Prisma.ai_interactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ai_interactions to fetch.
   */
  orderBy?: Prisma.ai_interactionsOrderByWithRelationInput | Prisma.ai_interactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ai_interactions.
   */
  cursor?: Prisma.ai_interactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ai_interactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ai_interactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ai_interactions.
   */
  distinct?: Prisma.Ai_interactionsScalarFieldEnum | Prisma.Ai_interactionsScalarFieldEnum[]
}

/**
 * ai_interactions create
 */
export type ai_interactionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * The data needed to create a ai_interactions.
   */
  data: Prisma.XOR<Prisma.ai_interactionsCreateInput, Prisma.ai_interactionsUncheckedCreateInput>
}

/**
 * ai_interactions createMany
 */
export type ai_interactionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ai_interactions.
   */
  data: Prisma.ai_interactionsCreateManyInput | Prisma.ai_interactionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ai_interactions createManyAndReturn
 */
export type ai_interactionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * The data used to create many ai_interactions.
   */
  data: Prisma.ai_interactionsCreateManyInput | Prisma.ai_interactionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ai_interactions update
 */
export type ai_interactionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * The data needed to update a ai_interactions.
   */
  data: Prisma.XOR<Prisma.ai_interactionsUpdateInput, Prisma.ai_interactionsUncheckedUpdateInput>
  /**
   * Choose, which ai_interactions to update.
   */
  where: Prisma.ai_interactionsWhereUniqueInput
}

/**
 * ai_interactions updateMany
 */
export type ai_interactionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ai_interactions.
   */
  data: Prisma.XOR<Prisma.ai_interactionsUpdateManyMutationInput, Prisma.ai_interactionsUncheckedUpdateManyInput>
  /**
   * Filter which ai_interactions to update
   */
  where?: Prisma.ai_interactionsWhereInput
  /**
   * Limit how many ai_interactions to update.
   */
  limit?: number
}

/**
 * ai_interactions updateManyAndReturn
 */
export type ai_interactionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * The data used to update ai_interactions.
   */
  data: Prisma.XOR<Prisma.ai_interactionsUpdateManyMutationInput, Prisma.ai_interactionsUncheckedUpdateManyInput>
  /**
   * Filter which ai_interactions to update
   */
  where?: Prisma.ai_interactionsWhereInput
  /**
   * Limit how many ai_interactions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ai_interactions upsert
 */
export type ai_interactionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * The filter to search for the ai_interactions to update in case it exists.
   */
  where: Prisma.ai_interactionsWhereUniqueInput
  /**
   * In case the ai_interactions found by the `where` argument doesn't exist, create a new ai_interactions with this data.
   */
  create: Prisma.XOR<Prisma.ai_interactionsCreateInput, Prisma.ai_interactionsUncheckedCreateInput>
  /**
   * In case the ai_interactions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ai_interactionsUpdateInput, Prisma.ai_interactionsUncheckedUpdateInput>
}

/**
 * ai_interactions delete
 */
export type ai_interactionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
  /**
   * Filter which ai_interactions to delete.
   */
  where: Prisma.ai_interactionsWhereUniqueInput
}

/**
 * ai_interactions deleteMany
 */
export type ai_interactionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ai_interactions to delete
   */
  where?: Prisma.ai_interactionsWhereInput
  /**
   * Limit how many ai_interactions to delete.
   */
  limit?: number
}

/**
 * ai_interactions.ai_escalations
 */
export type ai_interactions$ai_escalationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_escalations
   */
  select?: Prisma.ai_escalationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_escalations
   */
  omit?: Prisma.ai_escalationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_escalationsInclude<ExtArgs> | null
  where?: Prisma.ai_escalationsWhereInput
  orderBy?: Prisma.ai_escalationsOrderByWithRelationInput | Prisma.ai_escalationsOrderByWithRelationInput[]
  cursor?: Prisma.ai_escalationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Ai_escalationsScalarFieldEnum | Prisma.Ai_escalationsScalarFieldEnum[]
}

/**
 * ai_interactions.cases
 */
export type ai_interactions$casesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the cases
   */
  select?: Prisma.casesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the cases
   */
  omit?: Prisma.casesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.casesInclude<ExtArgs> | null
  where?: Prisma.casesWhereInput
}

/**
 * ai_interactions.episodes
 */
export type ai_interactions$episodesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the episodes
   */
  select?: Prisma.episodesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the episodes
   */
  omit?: Prisma.episodesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.episodesInclude<ExtArgs> | null
  where?: Prisma.episodesWhereInput
}

/**
 * ai_interactions without action
 */
export type ai_interactionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ai_interactions
   */
  select?: Prisma.ai_interactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ai_interactions
   */
  omit?: Prisma.ai_interactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ai_interactionsInclude<ExtArgs> | null
}
