
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `user_events` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model user_events
 * 
 */
export type user_eventsModel = runtime.Types.Result.DefaultSelection<Prisma.$user_eventsPayload>

export type AggregateUser_events = {
  _count: User_eventsCountAggregateOutputType | null
  _avg: User_eventsAvgAggregateOutputType | null
  _sum: User_eventsSumAggregateOutputType | null
  _min: User_eventsMinAggregateOutputType | null
  _max: User_eventsMaxAggregateOutputType | null
}

export type User_eventsAvgAggregateOutputType = {
  user_id: number | null
}

export type User_eventsSumAggregateOutputType = {
  user_id: number | null
}

export type User_eventsMinAggregateOutputType = {
  user_id: number | null
  event_id: string | null
  registered_at: Date | null
}

export type User_eventsMaxAggregateOutputType = {
  user_id: number | null
  event_id: string | null
  registered_at: Date | null
}

export type User_eventsCountAggregateOutputType = {
  user_id: number
  event_id: number
  registered_at: number
  _all: number
}


export type User_eventsAvgAggregateInputType = {
  user_id?: true
}

export type User_eventsSumAggregateInputType = {
  user_id?: true
}

export type User_eventsMinAggregateInputType = {
  user_id?: true
  event_id?: true
  registered_at?: true
}

export type User_eventsMaxAggregateInputType = {
  user_id?: true
  event_id?: true
  registered_at?: true
}

export type User_eventsCountAggregateInputType = {
  user_id?: true
  event_id?: true
  registered_at?: true
  _all?: true
}

export type User_eventsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_events to aggregate.
   */
  where?: Prisma.user_eventsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_events to fetch.
   */
  orderBy?: Prisma.user_eventsOrderByWithRelationInput | Prisma.user_eventsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.user_eventsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_events from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_events.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned user_events
  **/
  _count?: true | User_eventsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: User_eventsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: User_eventsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: User_eventsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: User_eventsMaxAggregateInputType
}

export type GetUser_eventsAggregateType<T extends User_eventsAggregateArgs> = {
      [P in keyof T & keyof AggregateUser_events]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser_events[P]>
    : Prisma.GetScalarType<T[P], AggregateUser_events[P]>
}




export type user_eventsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_eventsWhereInput
  orderBy?: Prisma.user_eventsOrderByWithAggregationInput | Prisma.user_eventsOrderByWithAggregationInput[]
  by: Prisma.User_eventsScalarFieldEnum[] | Prisma.User_eventsScalarFieldEnum
  having?: Prisma.user_eventsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: User_eventsCountAggregateInputType | true
  _avg?: User_eventsAvgAggregateInputType
  _sum?: User_eventsSumAggregateInputType
  _min?: User_eventsMinAggregateInputType
  _max?: User_eventsMaxAggregateInputType
}

export type User_eventsGroupByOutputType = {
  user_id: number
  event_id: string
  registered_at: Date | null
  _count: User_eventsCountAggregateOutputType | null
  _avg: User_eventsAvgAggregateOutputType | null
  _sum: User_eventsSumAggregateOutputType | null
  _min: User_eventsMinAggregateOutputType | null
  _max: User_eventsMaxAggregateOutputType | null
}

type GetUser_eventsGroupByPayload<T extends user_eventsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<User_eventsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof User_eventsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], User_eventsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], User_eventsGroupByOutputType[P]>
      }
    >
  >



export type user_eventsWhereInput = {
  AND?: Prisma.user_eventsWhereInput | Prisma.user_eventsWhereInput[]
  OR?: Prisma.user_eventsWhereInput[]
  NOT?: Prisma.user_eventsWhereInput | Prisma.user_eventsWhereInput[]
  user_id?: Prisma.IntFilter<"user_events"> | number
  event_id?: Prisma.UuidFilter<"user_events"> | string
  registered_at?: Prisma.DateTimeNullableFilter<"user_events"> | Date | string | null
  events?: Prisma.XOR<Prisma.EventsScalarRelationFilter, Prisma.eventsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type user_eventsOrderByWithRelationInput = {
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  registered_at?: Prisma.SortOrderInput | Prisma.SortOrder
  events?: Prisma.eventsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type user_eventsWhereUniqueInput = Prisma.AtLeast<{
  user_id_event_id?: Prisma.user_eventsUser_idEvent_idCompoundUniqueInput
  AND?: Prisma.user_eventsWhereInput | Prisma.user_eventsWhereInput[]
  OR?: Prisma.user_eventsWhereInput[]
  NOT?: Prisma.user_eventsWhereInput | Prisma.user_eventsWhereInput[]
  user_id?: Prisma.IntFilter<"user_events"> | number
  event_id?: Prisma.UuidFilter<"user_events"> | string
  registered_at?: Prisma.DateTimeNullableFilter<"user_events"> | Date | string | null
  events?: Prisma.XOR<Prisma.EventsScalarRelationFilter, Prisma.eventsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "user_id_event_id">

export type user_eventsOrderByWithAggregationInput = {
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  registered_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.user_eventsCountOrderByAggregateInput
  _avg?: Prisma.user_eventsAvgOrderByAggregateInput
  _max?: Prisma.user_eventsMaxOrderByAggregateInput
  _min?: Prisma.user_eventsMinOrderByAggregateInput
  _sum?: Prisma.user_eventsSumOrderByAggregateInput
}

export type user_eventsScalarWhereWithAggregatesInput = {
  AND?: Prisma.user_eventsScalarWhereWithAggregatesInput | Prisma.user_eventsScalarWhereWithAggregatesInput[]
  OR?: Prisma.user_eventsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.user_eventsScalarWhereWithAggregatesInput | Prisma.user_eventsScalarWhereWithAggregatesInput[]
  user_id?: Prisma.IntWithAggregatesFilter<"user_events"> | number
  event_id?: Prisma.UuidWithAggregatesFilter<"user_events"> | string
  registered_at?: Prisma.DateTimeNullableWithAggregatesFilter<"user_events"> | Date | string | null
}

export type user_eventsCreateInput = {
  registered_at?: Date | string | null
  events: Prisma.eventsCreateNestedOneWithoutUser_eventsInput
  users: Prisma.usersCreateNestedOneWithoutUser_eventsInput
}

export type user_eventsUncheckedCreateInput = {
  user_id: number
  event_id: string
  registered_at?: Date | string | null
}

export type user_eventsUpdateInput = {
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  events?: Prisma.eventsUpdateOneRequiredWithoutUser_eventsNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutUser_eventsNestedInput
}

export type user_eventsUncheckedUpdateInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  event_id?: Prisma.StringFieldUpdateOperationsInput | string
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_eventsCreateManyInput = {
  user_id: number
  event_id: string
  registered_at?: Date | string | null
}

export type user_eventsUpdateManyMutationInput = {
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_eventsUncheckedUpdateManyInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  event_id?: Prisma.StringFieldUpdateOperationsInput | string
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type User_eventsListRelationFilter = {
  every?: Prisma.user_eventsWhereInput
  some?: Prisma.user_eventsWhereInput
  none?: Prisma.user_eventsWhereInput
}

export type user_eventsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type user_eventsUser_idEvent_idCompoundUniqueInput = {
  user_id: number
  event_id: string
}

export type user_eventsCountOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  registered_at?: Prisma.SortOrder
}

export type user_eventsAvgOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
}

export type user_eventsMaxOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  registered_at?: Prisma.SortOrder
}

export type user_eventsMinOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  event_id?: Prisma.SortOrder
  registered_at?: Prisma.SortOrder
}

export type user_eventsSumOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
}

export type user_eventsCreateNestedManyWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.user_eventsCreateWithoutEventsInput, Prisma.user_eventsUncheckedCreateWithoutEventsInput> | Prisma.user_eventsCreateWithoutEventsInput[] | Prisma.user_eventsUncheckedCreateWithoutEventsInput[]
  connectOrCreate?: Prisma.user_eventsCreateOrConnectWithoutEventsInput | Prisma.user_eventsCreateOrConnectWithoutEventsInput[]
  createMany?: Prisma.user_eventsCreateManyEventsInputEnvelope
  connect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
}

export type user_eventsUncheckedCreateNestedManyWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.user_eventsCreateWithoutEventsInput, Prisma.user_eventsUncheckedCreateWithoutEventsInput> | Prisma.user_eventsCreateWithoutEventsInput[] | Prisma.user_eventsUncheckedCreateWithoutEventsInput[]
  connectOrCreate?: Prisma.user_eventsCreateOrConnectWithoutEventsInput | Prisma.user_eventsCreateOrConnectWithoutEventsInput[]
  createMany?: Prisma.user_eventsCreateManyEventsInputEnvelope
  connect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
}

export type user_eventsUpdateManyWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.user_eventsCreateWithoutEventsInput, Prisma.user_eventsUncheckedCreateWithoutEventsInput> | Prisma.user_eventsCreateWithoutEventsInput[] | Prisma.user_eventsUncheckedCreateWithoutEventsInput[]
  connectOrCreate?: Prisma.user_eventsCreateOrConnectWithoutEventsInput | Prisma.user_eventsCreateOrConnectWithoutEventsInput[]
  upsert?: Prisma.user_eventsUpsertWithWhereUniqueWithoutEventsInput | Prisma.user_eventsUpsertWithWhereUniqueWithoutEventsInput[]
  createMany?: Prisma.user_eventsCreateManyEventsInputEnvelope
  set?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  disconnect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  delete?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  connect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  update?: Prisma.user_eventsUpdateWithWhereUniqueWithoutEventsInput | Prisma.user_eventsUpdateWithWhereUniqueWithoutEventsInput[]
  updateMany?: Prisma.user_eventsUpdateManyWithWhereWithoutEventsInput | Prisma.user_eventsUpdateManyWithWhereWithoutEventsInput[]
  deleteMany?: Prisma.user_eventsScalarWhereInput | Prisma.user_eventsScalarWhereInput[]
}

export type user_eventsUncheckedUpdateManyWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.user_eventsCreateWithoutEventsInput, Prisma.user_eventsUncheckedCreateWithoutEventsInput> | Prisma.user_eventsCreateWithoutEventsInput[] | Prisma.user_eventsUncheckedCreateWithoutEventsInput[]
  connectOrCreate?: Prisma.user_eventsCreateOrConnectWithoutEventsInput | Prisma.user_eventsCreateOrConnectWithoutEventsInput[]
  upsert?: Prisma.user_eventsUpsertWithWhereUniqueWithoutEventsInput | Prisma.user_eventsUpsertWithWhereUniqueWithoutEventsInput[]
  createMany?: Prisma.user_eventsCreateManyEventsInputEnvelope
  set?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  disconnect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  delete?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  connect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  update?: Prisma.user_eventsUpdateWithWhereUniqueWithoutEventsInput | Prisma.user_eventsUpdateWithWhereUniqueWithoutEventsInput[]
  updateMany?: Prisma.user_eventsUpdateManyWithWhereWithoutEventsInput | Prisma.user_eventsUpdateManyWithWhereWithoutEventsInput[]
  deleteMany?: Prisma.user_eventsScalarWhereInput | Prisma.user_eventsScalarWhereInput[]
}

export type user_eventsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.user_eventsCreateWithoutUsersInput, Prisma.user_eventsUncheckedCreateWithoutUsersInput> | Prisma.user_eventsCreateWithoutUsersInput[] | Prisma.user_eventsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_eventsCreateOrConnectWithoutUsersInput | Prisma.user_eventsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.user_eventsCreateManyUsersInputEnvelope
  connect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
}

export type user_eventsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.user_eventsCreateWithoutUsersInput, Prisma.user_eventsUncheckedCreateWithoutUsersInput> | Prisma.user_eventsCreateWithoutUsersInput[] | Prisma.user_eventsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_eventsCreateOrConnectWithoutUsersInput | Prisma.user_eventsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.user_eventsCreateManyUsersInputEnvelope
  connect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
}

export type user_eventsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.user_eventsCreateWithoutUsersInput, Prisma.user_eventsUncheckedCreateWithoutUsersInput> | Prisma.user_eventsCreateWithoutUsersInput[] | Prisma.user_eventsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_eventsCreateOrConnectWithoutUsersInput | Prisma.user_eventsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.user_eventsUpsertWithWhereUniqueWithoutUsersInput | Prisma.user_eventsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.user_eventsCreateManyUsersInputEnvelope
  set?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  disconnect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  delete?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  connect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  update?: Prisma.user_eventsUpdateWithWhereUniqueWithoutUsersInput | Prisma.user_eventsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.user_eventsUpdateManyWithWhereWithoutUsersInput | Prisma.user_eventsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.user_eventsScalarWhereInput | Prisma.user_eventsScalarWhereInput[]
}

export type user_eventsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.user_eventsCreateWithoutUsersInput, Prisma.user_eventsUncheckedCreateWithoutUsersInput> | Prisma.user_eventsCreateWithoutUsersInput[] | Prisma.user_eventsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_eventsCreateOrConnectWithoutUsersInput | Prisma.user_eventsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.user_eventsUpsertWithWhereUniqueWithoutUsersInput | Prisma.user_eventsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.user_eventsCreateManyUsersInputEnvelope
  set?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  disconnect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  delete?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  connect?: Prisma.user_eventsWhereUniqueInput | Prisma.user_eventsWhereUniqueInput[]
  update?: Prisma.user_eventsUpdateWithWhereUniqueWithoutUsersInput | Prisma.user_eventsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.user_eventsUpdateManyWithWhereWithoutUsersInput | Prisma.user_eventsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.user_eventsScalarWhereInput | Prisma.user_eventsScalarWhereInput[]
}

export type user_eventsCreateWithoutEventsInput = {
  registered_at?: Date | string | null
  users: Prisma.usersCreateNestedOneWithoutUser_eventsInput
}

export type user_eventsUncheckedCreateWithoutEventsInput = {
  user_id: number
  registered_at?: Date | string | null
}

export type user_eventsCreateOrConnectWithoutEventsInput = {
  where: Prisma.user_eventsWhereUniqueInput
  create: Prisma.XOR<Prisma.user_eventsCreateWithoutEventsInput, Prisma.user_eventsUncheckedCreateWithoutEventsInput>
}

export type user_eventsCreateManyEventsInputEnvelope = {
  data: Prisma.user_eventsCreateManyEventsInput | Prisma.user_eventsCreateManyEventsInput[]
  skipDuplicates?: boolean
}

export type user_eventsUpsertWithWhereUniqueWithoutEventsInput = {
  where: Prisma.user_eventsWhereUniqueInput
  update: Prisma.XOR<Prisma.user_eventsUpdateWithoutEventsInput, Prisma.user_eventsUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.user_eventsCreateWithoutEventsInput, Prisma.user_eventsUncheckedCreateWithoutEventsInput>
}

export type user_eventsUpdateWithWhereUniqueWithoutEventsInput = {
  where: Prisma.user_eventsWhereUniqueInput
  data: Prisma.XOR<Prisma.user_eventsUpdateWithoutEventsInput, Prisma.user_eventsUncheckedUpdateWithoutEventsInput>
}

export type user_eventsUpdateManyWithWhereWithoutEventsInput = {
  where: Prisma.user_eventsScalarWhereInput
  data: Prisma.XOR<Prisma.user_eventsUpdateManyMutationInput, Prisma.user_eventsUncheckedUpdateManyWithoutEventsInput>
}

export type user_eventsScalarWhereInput = {
  AND?: Prisma.user_eventsScalarWhereInput | Prisma.user_eventsScalarWhereInput[]
  OR?: Prisma.user_eventsScalarWhereInput[]
  NOT?: Prisma.user_eventsScalarWhereInput | Prisma.user_eventsScalarWhereInput[]
  user_id?: Prisma.IntFilter<"user_events"> | number
  event_id?: Prisma.UuidFilter<"user_events"> | string
  registered_at?: Prisma.DateTimeNullableFilter<"user_events"> | Date | string | null
}

export type user_eventsCreateWithoutUsersInput = {
  registered_at?: Date | string | null
  events: Prisma.eventsCreateNestedOneWithoutUser_eventsInput
}

export type user_eventsUncheckedCreateWithoutUsersInput = {
  event_id: string
  registered_at?: Date | string | null
}

export type user_eventsCreateOrConnectWithoutUsersInput = {
  where: Prisma.user_eventsWhereUniqueInput
  create: Prisma.XOR<Prisma.user_eventsCreateWithoutUsersInput, Prisma.user_eventsUncheckedCreateWithoutUsersInput>
}

export type user_eventsCreateManyUsersInputEnvelope = {
  data: Prisma.user_eventsCreateManyUsersInput | Prisma.user_eventsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type user_eventsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.user_eventsWhereUniqueInput
  update: Prisma.XOR<Prisma.user_eventsUpdateWithoutUsersInput, Prisma.user_eventsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.user_eventsCreateWithoutUsersInput, Prisma.user_eventsUncheckedCreateWithoutUsersInput>
}

export type user_eventsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.user_eventsWhereUniqueInput
  data: Prisma.XOR<Prisma.user_eventsUpdateWithoutUsersInput, Prisma.user_eventsUncheckedUpdateWithoutUsersInput>
}

export type user_eventsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.user_eventsScalarWhereInput
  data: Prisma.XOR<Prisma.user_eventsUpdateManyMutationInput, Prisma.user_eventsUncheckedUpdateManyWithoutUsersInput>
}

export type user_eventsCreateManyEventsInput = {
  user_id: number
  registered_at?: Date | string | null
}

export type user_eventsUpdateWithoutEventsInput = {
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneRequiredWithoutUser_eventsNestedInput
}

export type user_eventsUncheckedUpdateWithoutEventsInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_eventsUncheckedUpdateManyWithoutEventsInput = {
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_eventsCreateManyUsersInput = {
  event_id: string
  registered_at?: Date | string | null
}

export type user_eventsUpdateWithoutUsersInput = {
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  events?: Prisma.eventsUpdateOneRequiredWithoutUser_eventsNestedInput
}

export type user_eventsUncheckedUpdateWithoutUsersInput = {
  event_id?: Prisma.StringFieldUpdateOperationsInput | string
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_eventsUncheckedUpdateManyWithoutUsersInput = {
  event_id?: Prisma.StringFieldUpdateOperationsInput | string
  registered_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type user_eventsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  event_id?: boolean
  registered_at?: boolean
  events?: boolean | Prisma.eventsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_events"]>

export type user_eventsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  event_id?: boolean
  registered_at?: boolean
  events?: boolean | Prisma.eventsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_events"]>

export type user_eventsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  event_id?: boolean
  registered_at?: boolean
  events?: boolean | Prisma.eventsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_events"]>

export type user_eventsSelectScalar = {
  user_id?: boolean
  event_id?: boolean
  registered_at?: boolean
}

export type user_eventsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_id" | "event_id" | "registered_at", ExtArgs["result"]["user_events"]>
export type user_eventsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | Prisma.eventsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type user_eventsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | Prisma.eventsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type user_eventsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | Prisma.eventsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $user_eventsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "user_events"
  objects: {
    events: Prisma.$eventsPayload<ExtArgs>
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_id: number
    event_id: string
    registered_at: Date | null
  }, ExtArgs["result"]["user_events"]>
  composites: {}
}

export type user_eventsGetPayload<S extends boolean | null | undefined | user_eventsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$user_eventsPayload, S>

export type user_eventsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<user_eventsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: User_eventsCountAggregateInputType | true
  }

export interface user_eventsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['user_events'], meta: { name: 'user_events' } }
  /**
   * Find zero or one User_events that matches the filter.
   * @param {user_eventsFindUniqueArgs} args - Arguments to find a User_events
   * @example
   * // Get one User_events
   * const user_events = await prisma.user_events.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends user_eventsFindUniqueArgs>(args: Prisma.SelectSubset<T, user_eventsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__user_eventsClient<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User_events that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {user_eventsFindUniqueOrThrowArgs} args - Arguments to find a User_events
   * @example
   * // Get one User_events
   * const user_events = await prisma.user_events.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends user_eventsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, user_eventsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_eventsClient<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_events that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_eventsFindFirstArgs} args - Arguments to find a User_events
   * @example
   * // Get one User_events
   * const user_events = await prisma.user_events.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends user_eventsFindFirstArgs>(args?: Prisma.SelectSubset<T, user_eventsFindFirstArgs<ExtArgs>>): Prisma.Prisma__user_eventsClient<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_events that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_eventsFindFirstOrThrowArgs} args - Arguments to find a User_events
   * @example
   * // Get one User_events
   * const user_events = await prisma.user_events.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends user_eventsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, user_eventsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_eventsClient<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more User_events that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_eventsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all User_events
   * const user_events = await prisma.user_events.findMany()
   * 
   * // Get first 10 User_events
   * const user_events = await prisma.user_events.findMany({ take: 10 })
   * 
   * // Only select the `user_id`
   * const user_eventsWithUser_idOnly = await prisma.user_events.findMany({ select: { user_id: true } })
   * 
   */
  findMany<T extends user_eventsFindManyArgs>(args?: Prisma.SelectSubset<T, user_eventsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User_events.
   * @param {user_eventsCreateArgs} args - Arguments to create a User_events.
   * @example
   * // Create one User_events
   * const User_events = await prisma.user_events.create({
   *   data: {
   *     // ... data to create a User_events
   *   }
   * })
   * 
   */
  create<T extends user_eventsCreateArgs>(args: Prisma.SelectSubset<T, user_eventsCreateArgs<ExtArgs>>): Prisma.Prisma__user_eventsClient<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many User_events.
   * @param {user_eventsCreateManyArgs} args - Arguments to create many User_events.
   * @example
   * // Create many User_events
   * const user_events = await prisma.user_events.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends user_eventsCreateManyArgs>(args?: Prisma.SelectSubset<T, user_eventsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many User_events and returns the data saved in the database.
   * @param {user_eventsCreateManyAndReturnArgs} args - Arguments to create many User_events.
   * @example
   * // Create many User_events
   * const user_events = await prisma.user_events.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many User_events and only return the `user_id`
   * const user_eventsWithUser_idOnly = await prisma.user_events.createManyAndReturn({
   *   select: { user_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends user_eventsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, user_eventsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User_events.
   * @param {user_eventsDeleteArgs} args - Arguments to delete one User_events.
   * @example
   * // Delete one User_events
   * const User_events = await prisma.user_events.delete({
   *   where: {
   *     // ... filter to delete one User_events
   *   }
   * })
   * 
   */
  delete<T extends user_eventsDeleteArgs>(args: Prisma.SelectSubset<T, user_eventsDeleteArgs<ExtArgs>>): Prisma.Prisma__user_eventsClient<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User_events.
   * @param {user_eventsUpdateArgs} args - Arguments to update one User_events.
   * @example
   * // Update one User_events
   * const user_events = await prisma.user_events.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends user_eventsUpdateArgs>(args: Prisma.SelectSubset<T, user_eventsUpdateArgs<ExtArgs>>): Prisma.Prisma__user_eventsClient<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more User_events.
   * @param {user_eventsDeleteManyArgs} args - Arguments to filter User_events to delete.
   * @example
   * // Delete a few User_events
   * const { count } = await prisma.user_events.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends user_eventsDeleteManyArgs>(args?: Prisma.SelectSubset<T, user_eventsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_events.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_eventsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many User_events
   * const user_events = await prisma.user_events.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends user_eventsUpdateManyArgs>(args: Prisma.SelectSubset<T, user_eventsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_events and returns the data updated in the database.
   * @param {user_eventsUpdateManyAndReturnArgs} args - Arguments to update many User_events.
   * @example
   * // Update many User_events
   * const user_events = await prisma.user_events.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more User_events and only return the `user_id`
   * const user_eventsWithUser_idOnly = await prisma.user_events.updateManyAndReturn({
   *   select: { user_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends user_eventsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, user_eventsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User_events.
   * @param {user_eventsUpsertArgs} args - Arguments to update or create a User_events.
   * @example
   * // Update or create a User_events
   * const user_events = await prisma.user_events.upsert({
   *   create: {
   *     // ... data to create a User_events
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User_events we want to update
   *   }
   * })
   */
  upsert<T extends user_eventsUpsertArgs>(args: Prisma.SelectSubset<T, user_eventsUpsertArgs<ExtArgs>>): Prisma.Prisma__user_eventsClient<runtime.Types.Result.GetResult<Prisma.$user_eventsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of User_events.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_eventsCountArgs} args - Arguments to filter User_events to count.
   * @example
   * // Count the number of User_events
   * const count = await prisma.user_events.count({
   *   where: {
   *     // ... the filter for the User_events we want to count
   *   }
   * })
  **/
  count<T extends user_eventsCountArgs>(
    args?: Prisma.Subset<T, user_eventsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], User_eventsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User_events.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {User_eventsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends User_eventsAggregateArgs>(args: Prisma.Subset<T, User_eventsAggregateArgs>): Prisma.PrismaPromise<GetUser_eventsAggregateType<T>>

  /**
   * Group by User_events.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_eventsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends user_eventsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: user_eventsGroupByArgs['orderBy'] }
      : { orderBy?: user_eventsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, user_eventsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUser_eventsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the user_events model
 */
readonly fields: user_eventsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for user_events.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__user_eventsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  events<T extends Prisma.eventsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.eventsDefaultArgs<ExtArgs>>): Prisma.Prisma__eventsClient<runtime.Types.Result.GetResult<Prisma.$eventsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the user_events model
 */
export interface user_eventsFieldRefs {
  readonly user_id: Prisma.FieldRef<"user_events", 'Int'>
  readonly event_id: Prisma.FieldRef<"user_events", 'String'>
  readonly registered_at: Prisma.FieldRef<"user_events", 'DateTime'>
}
    

// Custom InputTypes
/**
 * user_events findUnique
 */
export type user_eventsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * Filter, which user_events to fetch.
   */
  where: Prisma.user_eventsWhereUniqueInput
}

/**
 * user_events findUniqueOrThrow
 */
export type user_eventsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * Filter, which user_events to fetch.
   */
  where: Prisma.user_eventsWhereUniqueInput
}

/**
 * user_events findFirst
 */
export type user_eventsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * Filter, which user_events to fetch.
   */
  where?: Prisma.user_eventsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_events to fetch.
   */
  orderBy?: Prisma.user_eventsOrderByWithRelationInput | Prisma.user_eventsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_events.
   */
  cursor?: Prisma.user_eventsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_events from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_events.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_events.
   */
  distinct?: Prisma.User_eventsScalarFieldEnum | Prisma.User_eventsScalarFieldEnum[]
}

/**
 * user_events findFirstOrThrow
 */
export type user_eventsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * Filter, which user_events to fetch.
   */
  where?: Prisma.user_eventsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_events to fetch.
   */
  orderBy?: Prisma.user_eventsOrderByWithRelationInput | Prisma.user_eventsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_events.
   */
  cursor?: Prisma.user_eventsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_events from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_events.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_events.
   */
  distinct?: Prisma.User_eventsScalarFieldEnum | Prisma.User_eventsScalarFieldEnum[]
}

/**
 * user_events findMany
 */
export type user_eventsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * Filter, which user_events to fetch.
   */
  where?: Prisma.user_eventsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_events to fetch.
   */
  orderBy?: Prisma.user_eventsOrderByWithRelationInput | Prisma.user_eventsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing user_events.
   */
  cursor?: Prisma.user_eventsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_events from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_events.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_events.
   */
  distinct?: Prisma.User_eventsScalarFieldEnum | Prisma.User_eventsScalarFieldEnum[]
}

/**
 * user_events create
 */
export type user_eventsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * The data needed to create a user_events.
   */
  data: Prisma.XOR<Prisma.user_eventsCreateInput, Prisma.user_eventsUncheckedCreateInput>
}

/**
 * user_events createMany
 */
export type user_eventsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many user_events.
   */
  data: Prisma.user_eventsCreateManyInput | Prisma.user_eventsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * user_events createManyAndReturn
 */
export type user_eventsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * The data used to create many user_events.
   */
  data: Prisma.user_eventsCreateManyInput | Prisma.user_eventsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * user_events update
 */
export type user_eventsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * The data needed to update a user_events.
   */
  data: Prisma.XOR<Prisma.user_eventsUpdateInput, Prisma.user_eventsUncheckedUpdateInput>
  /**
   * Choose, which user_events to update.
   */
  where: Prisma.user_eventsWhereUniqueInput
}

/**
 * user_events updateMany
 */
export type user_eventsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update user_events.
   */
  data: Prisma.XOR<Prisma.user_eventsUpdateManyMutationInput, Prisma.user_eventsUncheckedUpdateManyInput>
  /**
   * Filter which user_events to update
   */
  where?: Prisma.user_eventsWhereInput
  /**
   * Limit how many user_events to update.
   */
  limit?: number
}

/**
 * user_events updateManyAndReturn
 */
export type user_eventsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * The data used to update user_events.
   */
  data: Prisma.XOR<Prisma.user_eventsUpdateManyMutationInput, Prisma.user_eventsUncheckedUpdateManyInput>
  /**
   * Filter which user_events to update
   */
  where?: Prisma.user_eventsWhereInput
  /**
   * Limit how many user_events to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * user_events upsert
 */
export type user_eventsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * The filter to search for the user_events to update in case it exists.
   */
  where: Prisma.user_eventsWhereUniqueInput
  /**
   * In case the user_events found by the `where` argument doesn't exist, create a new user_events with this data.
   */
  create: Prisma.XOR<Prisma.user_eventsCreateInput, Prisma.user_eventsUncheckedCreateInput>
  /**
   * In case the user_events was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.user_eventsUpdateInput, Prisma.user_eventsUncheckedUpdateInput>
}

/**
 * user_events delete
 */
export type user_eventsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
  /**
   * Filter which user_events to delete.
   */
  where: Prisma.user_eventsWhereUniqueInput
}

/**
 * user_events deleteMany
 */
export type user_eventsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_events to delete
   */
  where?: Prisma.user_eventsWhereInput
  /**
   * Limit how many user_events to delete.
   */
  limit?: number
}

/**
 * user_events without action
 */
export type user_eventsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_events
   */
  select?: Prisma.user_eventsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_events
   */
  omit?: Prisma.user_eventsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_eventsInclude<ExtArgs> | null
}
